### ISSUE TITLE
OLED keeps displaying Dongle after the dongle is disconnected

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#1002]
My UHK 80 is disconnected. Then I connect the dongle, and it switches to it as expected and shows it accordingly on the OLED. Then I disconnect the dongle, but the display keeps showing Dongle.

**Comment by kareltucek** [comment]
How are you disconnecting the dongle? 

If I just throw dongle's switch on the USB hub, it is still backpowered via debugging probes, and so it maintains (i believe) the bluetooth link. 

If I also throw the other two switches, dongle disconnects allright.

**Comment by mondalaci** [comment]
The debugging probes of the dongle are disconnected. Only the dongle is connected via USB. When I disconnect and thereby power it off, the OLED keeps showing the dongle. I've just reproduced this issue.

It's important to emphasize that the UHK mustn't be connected to USB, in which case it reverts to the USB connection when the dongle is powered off. The UHK should be in disconnected state. Then, power the dongle and power it off.

**Comment by kareltucek** [comment]
Nope. Can't reporduce.

**Comment by mhantsch** [comment]
I had a similar experience which I haven't filed separately:

When switching between Bluetooth and Dongle back and forth, the diplay continues to show `UHK Dongle` even after I have pulled the dongle (I pulled it out of the USB port) and the connection is now on Bluetooth.

**Comment by Zetaphor** [comment]
> When switching between Bluetooth and Dongle back and forth, the diplay continues to show UHK Dongle even after I have pulled the dongle (I pulled it out of the USB port) and the connection is now on Bluetooth.

Exact same situation here. I would have expected it to say "Bluetooth". It was for this reason I didn't know how to even to even initiate bluetooth pairing until I read this thread and tried scanning when it wasn't connected to anything else

**Comment by mondalaci** [comment]
@Zetaphor So, have you tried Bluetooth pairing but couldn't because the dongle was connected?

**Comment by Zetaphor** [comment]
Correct, I didn't understand that it was going into Bluetooth pairing mode when the dongle was disconnected because it always reads "UHK Dongle" when not connected to USB. I only figured that out from reading this thread

**Comment by kareltucek** [comment]
This is definitely not relevant any more. 

(If there is similar issue in the future, please open a new ticket.)
