### ISSUE TITLE
Mouse key scroll inconsistently firing

### ISSUE THREAD

**Issue by Zetaphor** [UltimateHackingKeyboard/firmware#1009]
I'm not sure if this is connected to a related issue, but I've noticed that there is inconsistency in the signal sent from the mouse scroll down key  (using mouse keys). This came up from subjective experience as I rely heavily on the mouse layer, then I tested it with some online key testers.

When I test the mouse down key here:
https://cps-check.com/mouse-buttons-test

I can see that while I keep the physical key pressed the signal the page receives is intermittent, but not at a regular frequency. Sometimes it stays held, but it mostly switches on and off.

However when I use the Page Down key, which is on the same layer on this page:
https://keyboard-test.space/

The key is held consistently and is only released when I physically release it.

Here's the mapping I'm using for this key in the Agent:

![image](https://github.com/user-attachments/assets/906ceb1a-d6ff-4203-80af-28605f9ddd7b)

I'm encountering this issue on both the USB dongle and USB cable

**Comment by Zetaphor** [comment]
Simple test code to verify this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scroll and Page Down Detector</title>
</head>
<body>
    <div id="output">Events will be displayed here</div>
    <div style="height: 2000px;">Scroll down this area</div>

    <script>
        const output = document.getElementById('output');
        let isScrolling = false;
        let scrollTimeout;

        function logEvent(message) {
            output.textContent = message;
            console.log(message);
        }

        // Detect scroll start
        window.addEventListener('wheel', (event) => {
            if (event.deltaY > 0 && !isScrolling) {
                isScrolling = true;
                logEvent('Mouse scroll down pressed');
            }
            
            clearTimeout(scrollTimeout);
            scrollTimeout = setTimeout(() => {
                if (isScrolling) {
                    isScrolling = false;
                    logEvent('Mouse scroll down released');
                }
            }, 150);
        });

        // Detect Page Down key press and release
        window.addEventListener('keydown', (event) => {
            if (event.key === 'PageDown') {
                logEvent('Page Down key pressed');
            }
        });

        window.addEventListener('keyup', (event) => {
            if (event.key === 'PageDown') {
                logEvent('Page Down key released');
            }
        });
    </script>
</body>
</html>
```

**Comment by mondalaci** [comment]
What's your OS?

Which mouse button are you using?

Is page down mapped to mouse move down, which is actually triggered?

**Comment by Zetaphor** [comment]
> What's your OS?

NixOS 24.05 and Windows 11, the behavior is the same on both.

> Which mouse button are you using?

Using the mouse scroll down and up as ~~indicated in the screenshot~~, mapped to a key on a layer. **Edit:** Sorry I just realized my screenshot shows mouse move instead of scroll. I'm referring to my use of the scroll mapping available in the Agent GUI.

> Is page down mapped to mouse move down, which is actually triggered?

The problem is when holding the key mapped to mouse scroll up/down, it fires intermittently. It stutters between being pressed and depressed, while I'm physically holding the key down without interruption.

However when I press the key mapped to page down (on the same layer as the mouse scroll down key), it stays held the entire time it's being physically pressed.

**Comment by Zetaphor** [comment]
I recorded a video that will hopefully help to demonstrate. When I am scrolling the page up or down, I'm holding the key the entire time and only releasing once I've reached the top/bottom of the page.

When I go to the mouse tester website, I'm holding the key down the entire time I'm there until I left the window to stop the recording.

I'm using the latest firmware from the master branch

http://share.zetaphor.com/u/V8LoXw.mp4

**Comment by Zetaphor** [comment]
The only reason I call out page up/down is because it serves a similar function and I have it on the same layer as the mouse scroll keys. It appears to be working as expected, the input remains pressed until I physically release the key.

**Comment by Zetaphor** [comment]
The test in that video was performed using the USB dongle with no bridge cable. I just did another test with the USB cable and bridge cable and while it's still intermittently releasing the input, it is happening significantly less

**Comment by Zetaphor** [comment]
Just ran another test with the USB cable removed, but the bridge cable still attached, it appears to be just as problematic as with the bridge cable removed, so the issue appears to be related to the use of the dongle.

**Comment by mondalaci** [comment]
Thanks for elaborating! I can confirm that scrolling is inconsistent.

**Comment by kareltucek** [comment]
@Zetaphor is this still relevant?

**Comment by Zetaphor** [comment]
It appears this issue has been resolved with the latest firmware.
