### ISSUE TITLE
Controller cannot resume connectable advertising.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#1015]
```
W: opcode 0x2005 status 0x0c
E: Controller cannot resume connectable advertising (-5)
```

Getting after I disconnect phone from UHK. This is tested on dongle_pairing4

**Comment by benedekkupper** [comment]
is this when the left is connected via BLE? maybe need to bump the BT_MAX_CONN by one?

**Comment by kareltucek** [comment]
Generally when something is failing, disconnecting all current connections helps
