### ISSUE TITLE
Touchpad issues with firmware 12.0.0

### ISSUE THREAD

**Issue by jay7x** [UltimateHackingKeyboard/firmware#1032]
Today I started UHK Agent and it asked me to update. I allowed it. Then it told me there is firmware upgrade pending (11.2.0 -> 12.0.0). I did the firmware upgrade. Udev rules were outdated, so I updated them also, following the procedure.

Then I realized that touchpad module sends no Left click on tap anymore. I tried to detach and reattach the touchpad module and left keyboard part disappears in the UHK agent. Though, when I re-re-mapped the Left Click on the touchpad module and saved the changes, left part appears again. But touchpad left click doesn't work anyway. `xev` see no click event at all.

I tried to disconnect and reconnect the keyboard with no luck.

Let me know if I miss anything obvious...

Agent version: 5.0.0
Right keyboard half firmware: UltimateHackingKeyboard/firmware: 12.0.0
Left keyboard half firmware: UltimateHackingKeyboard/firmware: 12.0.0
Key cluster firmware: UltimateHackingKeyboard/firmware: 12.0.0
Touchpad is detected, and its firmware is implemented by the right keyboard half.

Thank you!

**Comment by jay7x** [comment]
Left part disappearing is reproducible with every touchpad module "detach, reattach" cycle. Sometimes, Left part appears quickly and disappears immediately after reattaching touchpad again. Saving changes to keyboard always brings the Left part back.

**Comment by jay7x** [comment]
I watched the `journalctl -xef` output and found something I don't think is right. When touchpad is re-attached, I see this as part of the output. See module ID 5 md5 value below:
```json
"rightModuleInfo": {
  "firmwareVersion": "12.0.0",
  "deviceProtocolVersion": "4.11.0",
  "moduleProtocolVersion": "4.3.0",
  "userConfigVersion": "8.3.0",
  "hardwareConfigVersion": "1.0.0",
  "smartMacrosVersion": "3.0.0",
  "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
  "firmwareGitTag": "v12.0.0",
  "firmwareChecksum": "213375ab240c0d38e5259302e3d62263",
  "modules": {
    "1": {
      "md5": "c321d8fb65130ee74d6167d52caf205b"
    },
    "2": {
      "md5": "b9cd4660ab39398e130c14a4077135f7"
    },
    "5": {
      "md5": "  �\u001f\t\u0005"
    }
  }
}
```

Module ID 5 info:
```json
{
  "module": {
    "id": 5,
    "name": "Touchpad",
    "configPath": "/add-on/touchpad",
    "slotId": 3,
    "i2cAddress": 109,
    "firmwareUpgradeSupported": false
  },
  "info": {
    "moduleProtocolVersion": "0.0.0",
    "firmwareVersion": "0.0.0",
    "firmwareGitRepo": "",
    "firmwareGitTag": "",
    "firmwareChecksum": ""
  }
}
```

**Comment by jay7x** [comment]
More debugging info.

Both halves are present in the Agent, detaching touchpad module:
<details>

```
11:34:08.027 › [DeviceOperation] Read "leftHalf" version information
11:34:08.029 › [DeviceOperation] Read "leftHalf" repo information
11:34:08.034 › [DeviceOperation] Read "leftHalf" firmware checksum
11:34:08.035 › [DeviceOperation] Read "leftModule" version information
11:34:08.038 › [DeviceOperation] Read "leftModule" repo information
11:34:08.042 › [DeviceOperation] Read "leftModule" firmware checksum
11:34:08.049 › [DeviceService] Device connection state changed to: {
  "bootloaderActive": false,
  "bleDeviceConnected": false,
  "communicationInterfaceAvailable": true,
  "dongle": {
    "bootloaderActive": false,
    "multiDevice": false,
    "serialNumber": ""
  },
  "leftHalfBootloaderActive": false,
  "hasPermission": true,
  "halvesInfo": {
    "areHalvesMerged": false,
    "isLeftHalfConnected": true,
    "leftModuleSlot": 2,
    "rightModuleSlot": 0
  },
  "hardwareModules": {
    "moduleInfos": [
      {
        "module": {
          "id": 1,
          "name": "Left keyboard half",
          "slotId": 1,
          "i2cAddress": 16,
          "firmwareUpgradeSupported": true
        },
        "info": {
          "moduleProtocolVersion": "4.3.0",
          "firmwareVersion": "12.0.0",
          "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
          "firmwareGitTag": "v12.0.0",
          "firmwareChecksum": "c321d8fb65130ee74d6167d52caf205b"
        }
      },
      {
        "module": {
          "id": 2,
          "name": "Key cluster",
          "configPath": "/add-on/key-cluster",
          "slotId": 2,
          "i2cAddress": 32,
          "firmwareUpgradeSupported": true
        },
        "info": {
          "moduleProtocolVersion": "4.3.0",
          "firmwareVersion": "12.0.0",
          "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
          "firmwareGitTag": "v12.0.0",
          "firmwareChecksum": "b9cd4660ab39398e130c14a4077135f7"
        }
      }
    ],
    "rightModuleInfo": {
      "firmwareVersion": "12.0.0",
      "deviceProtocolVersion": "4.11.0",
      "moduleProtocolVersion": "4.3.0",
      "userConfigVersion": "8.3.0",
      "hardwareConfigVersion": "1.0.0",
      "smartMacrosVersion": "3.0.0",
      "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
      "firmwareGitTag": "v12.0.0",
      "firmwareChecksum": "213375ab240c0d38e5259302e3d62263",
      "modules": {
        "1": {
          "md5": "c321d8fb65130ee74d6167d52caf205b"
        },
        "2": {
          "md5": "b9cd4660ab39398e130c14a4077135f7"
        }
      }
    }
  },
  "isMacroStatusDirty": false,
  "leftHalfDetected": false,
  "multiDevice": false,
  "udevRulesInfo": "Ok",
  "connectedDevice": {
    "id": 2,
    "asCliArg": "uhk60v2",
    "firmwareUpgradeMethod": "kboot",
    "logName": "UHK 60 v2",
    "name": "UHK 60 v2",
    "keyboard": [
      {
        "vid": 7504,
        "pid": 24868
      },
      {
        "vid": 14248,
        "pid": 3
      }
    ],
    "bootloader": [
      {
        "vid": 7504,
        "pid": 24867
      }
    ],
    "buspal": [
      {
        "vid": 7504,
        "pid": 24865
      },
      {
        "vid": 14248,
        "pid": 2
      }
    ],
    "reportId": 0
  }
}
11:34:08.049 › [DeviceRendererService] dispatch action [device] connection state changed
11:34:08.051 › [DeviceOperation] status buffer segment:
11:34:08.055 › [SmartMacroDocRendererService] downloadDocumentation
11:34:08.056 › [SmartMacroService] start download firmware documentation {
  firmwareGitRepo: 'UltimateHackingKeyboard/firmware',
  firmwareGitTag: 'v12.0.0'
}
11:34:08.056 › [SmartMacroService] firmware documentation downloaded
11:34:08.057 › [SmartMacroService] reference manual downloaded
11:34:08.064 › [DeviceRendererService] dispatch action [device] Status buffer changed
11:34:08.065 › [SmartMacroDocRendererService] dispatch action: [smart-macro-doc] download documentation success
11:34:08.065 › [SmartMacroDocRendererService] dispatch action: [smart-macro-doc] reference manual changed
```
</details>

Touchpad module attached:
<details>

```
11:35:32.450 › [DeviceOperation] Read "rightModule" version information
11:35:32.453 › [DeviceOperation] Read "rightModule" repo information
11:35:32.458 › [DeviceOperation] Read "rightModule" firmware checksum
11:35:32.467 › [DeviceService] Device connection state changed to: {
  "bootloaderActive": false,
  "bleDeviceConnected": false,
  "communicationInterfaceAvailable": true,
  "dongle": {
    "bootloaderActive": false,
    "multiDevice": false,
    "serialNumber": ""
  },
  "leftHalfBootloaderActive": false,
  "hasPermission": true,
  "halvesInfo": {
    "areHalvesMerged": false,
    "isLeftHalfConnected": false,
    "leftModuleSlot": 0,
    "rightModuleSlot": 5
  },
  "hardwareModules": {
    "moduleInfos": [
      {
        "module": {
          "id": 1,
          "name": "Left keyboard half",
          "slotId": 1,
          "i2cAddress": 16,
          "firmwareUpgradeSupported": true
        },
        "info": {}
      },
      {
        "module": {
          "id": 5,
          "name": "Touchpad",
          "configPath": "/add-on/touchpad",
          "slotId": 3,
          "i2cAddress": 109,
          "firmwareUpgradeSupported": false
        },
        "info": {
          "moduleProtocolVersion": "0.0.0",
          "firmwareVersion": "0.0.0",
          "firmwareGitRepo": "",
          "firmwareGitTag": "",
          "firmwareChecksum": ""
        }
      }
    ],
    "rightModuleInfo": {
      "firmwareVersion": "12.0.0",
      "deviceProtocolVersion": "4.11.0",
      "moduleProtocolVersion": "4.3.0",
      "userConfigVersion": "8.3.0",
      "hardwareConfigVersion": "1.0.0",
      "smartMacrosVersion": "3.0.0",
      "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
      "firmwareGitTag": "v12.0.0",
      "firmwareChecksum": "213375ab240c0d38e5259302e3d62263",
      "modules": {
        "1": {
          "md5": "c321d8fb65130ee74d6167d52caf205b"
        },
        "5": {
          "md5": "  �\u001f\t\u0005"
        }
      }
    }
  },
  "isMacroStatusDirty": false,
  "leftHalfDetected": false,
  "multiDevice": false,
  "udevRulesInfo": "Ok",
  "connectedDevice": {
    "id": 2,
    "asCliArg": "uhk60v2",
    "firmwareUpgradeMethod": "kboot",
    "logName": "UHK 60 v2",
    "name": "UHK 60 v2",
    "keyboard": [
      {
        "vid": 7504,
        "pid": 24868
      },
      {
        "vid": 14248,
        "pid": 3
      }
    ],
    "bootloader": [
      {
        "vid": 7504,
        "pid": 24867
      }
    ],
    "buspal": [
      {
        "vid": 7504,
        "pid": 24865
      },
      {
        "vid": 14248,
        "pid": 2
      }
    ],
    "reportId": 0
  }
}
11:35:32.468 › [DeviceRendererService] dispatch action [device] connection state changed
11:35:32.470 › [DeviceService] I2C watchdog counter changed from 12 => 13
11:35:32.472 › [DeviceOperation] status buffer segment:
11:35:32.474 › [SmartMacroDocRendererService] downloadDocumentation
11:35:32.474 › [SmartMacroService] start download firmware documentation {
  firmwareGitRepo: 'UltimateHackingKeyboard/firmware',
  firmwareGitTag: 'v12.0.0'
}
11:35:32.475 › [SmartMacroService] firmware documentation downloaded
11:35:32.475 › [SmartMacroService] reference manual downloaded
11:35:32.488 › [DeviceRendererService] dispatch action [advanceSettings] i2c watchdog counter changed
11:35:32.488 › [DeviceRendererService] dispatch action [device] Status buffer changed
11:35:32.489 › [SmartMacroDocRendererService] dispatch action: [smart-macro-doc] download documentation success
11:35:32.490 › [SmartMacroDocRendererService] dispatch action: [smart-macro-doc] reference manual changed
```
</details>

Touchpad tap action is remapped to Left Click (no changes actually, just Remap Key is pressed. Changes are saved to keyboard:
<details>

```
11:36:33.729 › [AppService] set-config of "application-settings": {"errorPanelHeight":10,"checkForUpdateOnStartUp":true,"everAttemptedSavingToKeyboard":true,"animationEnabled":true,"appTheme":"system","backlightingColorPalette":[{"r":255,"g":0,"b":0},{"r":0,"g":255,"b":0},{"r":0,"g":0,"b":255}],"keyboardHalvesAlwaysJoined":false,"smartMacroPanelWidth":41}
11:36:33.832 › [DeviceService] stop poll UHK Device
11:36:33.932 › [DeviceService] stopped poll UHK Device
11:36:34.183 › Keyboard is busy, wait...
11:36:34.387 › Keyboard is busy, wait...
11:36:34.592 › [UhkHidDevice] Device communication closing.
11:36:34.592 › [UhkHidDevice] Device communication closed.
11:36:34.599 › [UhkHidDevice] Device communication closing.
11:36:34.599 › [DeviceService] start poll UHK Device
11:36:34.599 › [DeviceRendererService] dispatch action [user-config] Load user configuration history success
11:36:34.600 › [DeviceRendererService] dispatch action [device] save configuration reply
11:36:34.861 › [UhkHidDevice] Available devices unchanged
11:36:34.925 › [UhkHidDevice] Used device: {"vendorId":"0x37A8","productId":"0x3","path":"/dev/hidraw5","serialNumber":"0392443036","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":2,"interface":4,"usagePage":65280,"usage":1}
11:36:34.932 › [UhkHidDevice] protocol versions: {"firmwareVersion":"12.0.0","deviceProtocolVersion":"4.11.0","moduleProtocolVersion":"4.3.0","userConfigVersion":"8.3.0","hardwareConfigVersion":"1.0.0","smartMacrosVersion":"3.0.0"}
11:36:34.944 › [DeviceOperation] Read "leftHalf" version information
11:36:34.947 › [DeviceOperation] Read "leftHalf" repo information
11:36:34.955 › [DeviceOperation] Read "leftHalf" firmware checksum
11:36:34.959 › [DeviceOperation] Read "leftModule" version information
11:36:34.963 › [DeviceOperation] Read "leftModule" repo information
11:36:34.970 › [DeviceOperation] Read "leftModule" firmware checksum
11:36:34.974 › [DeviceOperation] Read "rightModule" version information
11:36:34.978 › [DeviceOperation] Read "rightModule" repo information
11:36:34.985 › [DeviceOperation] Read "rightModule" firmware checksum
11:36:34.998 › [DeviceService] Device connection state changed to: {
  "bootloaderActive": false,
  "bleDeviceConnected": false,
  "communicationInterfaceAvailable": true,
  "dongle": {
    "bootloaderActive": false,
    "multiDevice": false,
    "serialNumber": ""
  },
  "leftHalfBootloaderActive": false,
  "hasPermission": true,
  "halvesInfo": {
    "areHalvesMerged": false,
    "isLeftHalfConnected": true,
    "leftModuleSlot": 2,
    "rightModuleSlot": 5
  },
  "hardwareModules": {
    "moduleInfos": [
      {
        "module": {
          "id": 1,
          "name": "Left keyboard half",
          "slotId": 1,
          "i2cAddress": 16,
          "firmwareUpgradeSupported": true
        },
        "info": {
          "moduleProtocolVersion": "4.3.0",
          "firmwareVersion": "12.0.0",
          "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
          "firmwareGitTag": "v12.0.0",
          "firmwareChecksum": "c321d8fb65130ee74d6167d52caf205b"
        }
      },
      {
        "module": {
          "id": 2,
          "name": "Key cluster",
          "configPath": "/add-on/key-cluster",
          "slotId": 2,
          "i2cAddress": 32,
          "firmwareUpgradeSupported": true
        },
        "info": {
          "moduleProtocolVersion": "4.3.0",
          "firmwareVersion": "12.0.0",
          "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
          "firmwareGitTag": "v12.0.0",
          "firmwareChecksum": "b9cd4660ab39398e130c14a4077135f7"
        }
      },
      {
        "module": {
          "id": 5,
          "name": "Touchpad",
          "configPath": "/add-on/touchpad",
          "slotId": 3,
          "i2cAddress": 109,
          "firmwareUpgradeSupported": false
        },
        "info": {
          "moduleProtocolVersion": "0.0.0",
          "firmwareVersion": "0.0.0",
          "firmwareGitRepo": "",
          "firmwareGitTag": "",
          "firmwareChecksum": ""
        }
      }
    ],
    "rightModuleInfo": {
      "firmwareVersion": "12.0.0",
      "deviceProtocolVersion": "4.11.0",
      "moduleProtocolVersion": "4.3.0",
      "userConfigVersion": "8.3.0",
      "hardwareConfigVersion": "1.0.0",
      "smartMacrosVersion": "3.0.0",
      "firmwareGitRepo": "UltimateHackingKeyboard/firmware",
      "firmwareGitTag": "v12.0.0",
      "firmwareChecksum": "213375ab240c0d38e5259302e3d62263",
      "modules": {
        "1": {
          "md5": "c321d8fb65130ee74d6167d52caf205b"
        },
        "2": {
          "md5": "b9cd4660ab39398e130c14a4077135f7"
        },
        "5": {
          "md5": "  �\u001f\t\u0005"
        }
      }
    }
  },
  "isMacroStatusDirty": false,
  "leftHalfDetected": false,
  "multiDevice": false,
  "udevRulesInfo": "Ok",
  "connectedDevice": {
    "id": 2,
    "asCliArg": "uhk60v2",
    "firmwareUpgradeMethod": "kboot",
    "logName": "UHK 60 v2",
    "name": "UHK 60 v2",
    "keyboard": [
      {
        "vid": 7504,
        "pid": 24868
      },
      {
        "vid": 14248,
        "pid": 3
      }
    ],
    "bootloader": [
      {
        "vid": 7504,
        "pid": 24867
      }
    ],
    "buspal": [
      {
        "vid": 7504,
        "pid": 24865
      },
      {
        "vid": 14248,
        "pid": 2
      }
    ],
    "reportId": 0
  }
}
11:36:34.998 › [DeviceRendererService] dispatch action [device] connection state changed
11:36:35.006 › [DeviceOperation] status buffer segment:
11:36:35.029 › [SmartMacroDocRendererService] downloadDocumentation
11:36:35.030 › [SmartMacroService] start download firmware documentation {
  firmwareGitRepo: 'UltimateHackingKeyboard/firmware',
  firmwareGitTag: 'v12.0.0'
}
11:36:35.031 › [SmartMacroService] firmware documentation downloaded
11:36:35.032 › [SmartMacroService] reference manual downloaded
11:36:35.072 › [DeviceRendererService] dispatch action [device] Status buffer changed
11:36:35.073 › [SmartMacroDocRendererService] dispatch action: [smart-macro-doc] download documentation success
11:36:35.074 › [SmartMacroDocRendererService] dispatch action: [smart-macro-doc] reference manual changed
```
</details>

**Comment by jay7x** [comment]
Hmm.. after re-flashing the firmware, I was able to click **once** with the touchpad, after that it stops sending the event again.

Same happens when keyboard is re-connected to a USB port.

Nothing related in dmesg/journalctl output..

**Comment by Jopie01** [comment]
Same here, but with the trackball. I'm using the left click as a middle click on the MOD layer, but it doesn't work. Reverting back to the 11.2 firmware.

P.S. for anybody who wants to revert as well: The configuration has changed, so the UHK looks like it's bricked. Starting the agent will connect and tells you that the configuration is invalid. In order to revert back to the old configuration, you must downgrade the agent to 4.2.1 to fix the configuration. You probably are losing everything unless you have backed up your configuration. Personally I think this step should be in the agent so it forces you to save the old configuration somewhere.

**Comment by kareltucek** [comment]
@Jopie01, with trackball it is a different issue and I can't reproduce it - my trackball's buttons work just fine. Please, provide more detailed instructions, ideally in a new ticket and with a UserConfig ;-).

> You probably are losing everything unless you have backed up your configuration.

Do configs (those from before the upgrade) from your history (in Agent's Configuration tab) not work?

**Comment by mhantsch** [comment]
As @kareltucek wrote, Agent automatically stores history:

![image](https://github.com/user-attachments/assets/792637fa-2577-4191-a5c7-c426083de426)

**Comment by Jopie01** [comment]
This is my configuration ......

![Schermafdruk_20241216_193041](https://github.com/user-attachments/assets/4f50c478-d4e3-47ee-a338-686627f79dad)

As you can see all the configurations are overwritten. This is after I downgraded back to firmware 11.2 and agent 4.2.1 I'm just wondering if all the configurations were migrated to the new configuration version.

For the trackball issue I'm opening a new issue.

**Comment by mhantsch** [comment]
> I'm just wondering if all the configurations were migrated to the new configuration version

That's not good. That's maybe worth opening another issue for Agent v5.

**Comment by mondalaci** [comment]
> As you can see all the configurations are overwritten.

Do you mean that the configurations saved before upgrading to Agent 5.0.0 are no longer shown in Agent?

**Comment by Jopie01** [comment]
> Do you mean that the configurations saved before upgrading to Agent 5.0.0 are no longer shown in Agent?

When I upgraded to 5.0.0 I migrated to the new configuration version as well, but I walked into #1035 so I downgraded everything back to the previous state. But because of the new configuration version, I got the error `invalid configuration`. So I had to click on the button `fix configuration` which basically reset the configuration to default values.

They are shown in agent 4.2.1 but are invalid configurations, only the fixed current one it valid.

**Comment by mondalaci** [comment]
I see, but the configurations featured in the configuration history have not been overwritten. They are invalid until you upgrade to an Agent 5.0.0+ and firmware 12.0.0+ version.

**Comment by Jopie01** [comment]
> They are invalid until you upgrade to an Agent 5.0.0+ and firmware 12.0.0+ version.

I haven't dug into it but why are the ALL the configurations migrated to the new configuration version? Is it one big huge blob which contains all the configurations? I expected that only the configuration which was currently running was migrated and not the whole history as well. User are now basically unable to downgrade when they find some issues with the firmware, unless they have made a backup of the configuration before upgrading.

Generally speaking, it would be nice to add a big warning or backup button in the agent when upgrading the configuration version.

**Comment by mondalaci** [comment]
> I haven't dug into it but why are the ALL the configurations migrated to the new configuration version?

They aren't. Every configuration is saved in the actual format. Upon loading them, Agent automatically transforms the configuration to the most recent version. But it can't transform it to earlier versions, hence your issue.

> Is it one big huge blob which contains all the configurations?

These are separate files on the filesystem. See Settings -> "Open configuration folder" in Agent.

We could display which configuration history records are incompatible with the current firmware. But this issue is very rare and isn't worth much effort.

**Comment by mhantsch** [comment]
But when reverting back to an older version of Agent, should the user not be able to also load one if those older history configs? I understood from the previous messages that @Jopie01 experienced that the whole history had been converted, and none of the older configs could be loaded anymore even after reverting Agent. ???

**Comment by mondalaci** [comment]
This should not be the case. Older configurations should remain accessible. If the saved user configuration version is less or equal than the user configuration version of the firmware, the configuration should be reloadable.

**Comment by pcooke9** [comment]
Using **"UltimateHackingKeyboard/firmware: 12.0.0 #c48aa75"**; left-click now works, but assigning the touchpad to anything else (middle/right/back/forward, etc.) only outputs left-clicks. Even assigning "None" action still activates left-click.

Two-finger tap to right-click is also broken. You need to two-finger tap twice, or two-finger tap once, and then single-finger tap once to right-click. Very weird.

This affects both the UHK60 and UHK80.
___

Left half image still disappears from Agent when connecting/disconnecting touchpad module as well. This only happens with the UHK60 connected.

**Comment by kareltucek** [comment]
Well, I am confirming that something fishy is going on with history. 

I have just been trying to load my pre-12.0.0 uhk80 configs via history onto the post-12.0.0 uhk80 using agent80 5.0.0, and all my uhk80 configs dissapeared - there are not even the tabs of the devices present.

**Comment by mondalaci** [comment]
Does the https://github.com/UltimateHackingKeyboard/firmware/actions/runs/12392454444 build resolve your issues, guys?

**Comment by pcooke9** [comment]
> Does the https://github.com/UltimateHackingKeyboard/firmware/actions/runs/12392454444 build resolve your issues, guys?

Agent left-half image no longer disappears.

Reassigning TouchPad actions is fixed.

Left-click works normally.

But two-finger tap to right-click is still broken for me.

**Comment by kareltucek** [comment]
Can you share your user config? Two-finger tap works fine for me with my own config as well as factory settings.

**Comment by pcooke9** [comment]
> Can you share your user config?

Just going to bed now, but I reset my config to test it with defaults and it still happens. I'll try to gather more details for you later tonight or tomorrow.

**Comment by pcooke9** [comment]
@kareltucek Sorry it took so long, but here's a video showing the TouchPad's two-finger tap to right-click issue:
https://www.youtube.com/watch?v=iYxiAp6P91o

Using an online mouse tester, I finally discovered the two-finger tap's right-click is getting stuck and is being applied to the non-UHK mouse as well. Either tapping the TouchPad normally, or right-clicking the non-UHK mouse unsticks it.

This happens with both the UHK60 and UHK80.

EDIT: It kind of feels like it might be something like a tap & hold, but with right-click instead of left-click.🤷🏻‍♂️
