### ISSUE TITLE
Issue with the firmware 12.0.0 and trackball module

### ISSUE THREAD

**Issue by Jopie01** [UltimateHackingKeyboard/firmware#1035]
Today I upgraded the firmware and the agent to the latest versions:
- firmware: 12.0.0
- agent: 5.0.0

It seems there is also a new configuration version so I migrated to that as well. But now I walk into trouble with my trackball.

I have mapped the left button of the trackball on layer MOD as middle mouse click. See the screenshot from version 4.2.1
![Schermafdruk_20241216_194931](https://github.com/user-attachments/assets/a906f916-b5c7-443d-ac7d-75bde37a5e7c)

I did the same with the new configuration version, new firmware and agent, but cannot get it working.

**Comment by kareltucek** [comment]
Could you please export your UserConfiguration.json in the Configuration tab? You can rename it to .txt so that github accepts it...

**Comment by kareltucek** [comment]
Although, nevermind, this config looks pretty standard. Will try to test with a factory settings.

**Comment by Jopie01** [comment]
> Although, nevermind, this config looks pretty standard. Will try to test with a factory settings.

Yeah, I don't know what the `fix configuration` button in the agent does, but it seems it just sets a factory one. The only thing I changed was adding the middle click and lowered the led brightness.

**Comment by Totoro83** [comment]
Not sure if additional feedback is something you'd like to have, as I see that there is already a pull request that should solve the issue, but I have exactly the same issue (except that I mapped the buttons "backward" and "forward" in the mod layer.)

**Comment by mondalaci** [comment]
Does the https://github.com/UltimateHackingKeyboard/firmware/actions/runs/12392454444 build resolve your issues?

**Comment by Jopie01** [comment]
A very late response, but I want to let you know that the newest firmware 12.1.0 fixes this issue.

**Comment by Totoro83** [comment]
It does for me too.
