### ISSUE TITLE
Reboot Zephyr after flashing the firmware

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#1042]
Zephyr was rebooted after flashing the firmware before the NCS 2.8.0 port, but now, we have to manually reboot the boards. While not a critical issue, this reduces developer productivity, so I'd like Zephyr to be rebooted automatically after flashing the firmware.

@benedekkupper Please make this a priority.

**Comment by benedekkupper** [comment]
Please try by adding this modification to `.vscode/settings.json`:
```json
    "nrf-connect.applicationOptions": {
        "${workspaceFolder}/device": {
            "flash": {
                "softreset": true
            }
        }
    },
```

**Comment by mondalaci** [comment]
Works, thanks!

**Comment by kareltucek** [comment]
It seems this fixes the issue for vscode only. 

How does one reboot automatically when compiling from command line?

**Comment by benedekkupper** [comment]
Add the `--softreset` argument to the `west flash` command

**Comment by kareltucek** [comment]
Alright, thanks!
