### ISSUE TITLE
Key Cluster mapping lost when wake up in UHK80

### ISSUE THREAD

**Issue by multjiang** [UltimateHackingKeyboard/firmware#1061]
The key cluster was mapped with the UHK 80, but when the keyboard woke up (by reconnecting, as it doesn't wake up automanticly in Windows 11 like in #1060 ), the customized setting doesn't load with it.
LEDs work fine.
Restart the keyboard or re-attach the key cluster both don't solve the issue.
Open the Agent and it shows the mapping correctly. Save the mapping to the keyboard again make it work, but next time when wake up it is lost again.

Firmware 12.1.0

**Comment by kareltucek** [comment]
Thanks for report!
