### ISSUE TITLE
Double-Click "Locking" gets stuck on 8.3.0

### ISSUE THREAD

**Issue by opie4624** [UltimateHackingKeyboard/firmware#121]
What I expect: After double-clicking to lock a layer, single-clicking will unlock it.
What happens: Locked layers never unlock.

**Comment by mondalaci** [comment]
Yep, I was aware of that and I've been working on the fix recently. Just fixed by b0d85795f4390e2255ae99cf31ac5c64ca6b25d0, and released firmware 8.3.1 which contains the fix.

Thanks for the heads up!
