### ISSUE TITLE
Secondary-role layer switch causes weird alt-tab behaviour

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#125]
I assigned the left space to send Space scancode and secondary role to switch to the Mouse layer.
On the Mouse layer, I configured Tab to send LAlt-Tab.
When I press Space-Tab, the windows switch immediately (to the previously active window). If I keep holding down the Space key, I cannot keep tabbing through all the open windows.

When instead I use a primary role switch to the Mouse layer, everything works as intended, and I can tab through the open windows while keeping the layer switch key depressed. However, doing the same with a secondary role switch, UHK only seems to send a single LAlt-Tab and immediately releases LAlt although I keep that secondary role key depressed. I think it should keep the LAlt modifier depressed until I let go of the secondary role key.

**Comment by mhantsch** [comment]
This might be related to #69

**Comment by mondalaci** [comment]
Thanks for reporting! I can clearly reproduce this issue.

**Comment by TorC8** [comment]
That opens up the question of right behavior.  Certainly I think it should hold for repeated presses of the key, but what about the case of, while still holding $MOUSE, pressing a different key that doesn't have $ALT configured as part of its keycode?

My inclination is to think that the right thing is to drop the modifier at that point before sending the new keycode, but I can see arguments for both options.

**Comment by mondalaci** [comment]
I agree that dropping Alt is the right thing to do in the above case. I can't see why any other option would make sense.

**Comment by mhantsch** [comment]
Unless it's Shift; then you need to keep Alt held down because the user is trying to type Alt-Shift-Tab to cycle the windows backwards. So, I would argue: drop Alt only if the next keypress produces an actual character, macro, layer switch, or keymap switch; don't drop it on modifiers-only (Ctrl/Shift/Alt).

**Comment by mondalaci** [comment]
@mhantsch Yep, we're on the same page.

**Comment by mhantsch** [comment]
I can confirm that this is resolved with firmware 8.4.2.
