### ISSUE TITLE
The USB freeze bug is back

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#136]
@eltang @Lauszus I am shocked to see that the freeze bug is still an issue in https://github.com/UltimateHackingKeyboard/firmware/tree/v8.3.3

According to my findings, the bug only shows itself when the [USB test #ifdef clause](https://github.com/UltimateHackingKeyboard/firmware/blob/014addd77765bcf883673e5e07e8a8d188c7e540/right/src/usb_report_updater.c#L326) is 0, otherwise the firmware seems to be rock stable.

Any ideas?

**Comment by mondalaci** [comment]
Please don't dedicate a significant amount of time to this bug yet, guys. I'm in the process of testing older commits to see where it went wrong. If you have some quick ideas, you're welcome to throw them at me.

**Comment by eltang** [comment]
Does the freeze occur during idle? If so, is the amount of time it takes to happen consistent? I'm thinking the solution might be to send reports during idle.

**Comment by mondalaci** [comment]
The freeze occurs during typing. I'm not sure how consistent the amount of time is because now that the test code is disabled it's significantly harder to reproduce, but I don't think it's very consistent. I hardly believe that sending reports during idle would solve this issue because the firmware seems to be stable when the test code is included, even if it's not triggered. I think it's some sort of low-level issue.

**Comment by Lauszus** [comment]
Can you try to play around with the interrupt priority here: https://github.com/UltimateHackingKeyboard/firmware/blob/d72ea4dde53af43b83d725dd4cc5f51404958837/right/src/init_peripherals.c#L72

**Comment by Lauszus** [comment]
@eltang the whole point of only sending the reports when the report changes is so it works properly with Windows. This is also how keyboard normally do it.

**Comment by eltang** [comment]
Please refer to the documentation about HID idle [here](https://www.keil.com/pack/doc/mw/USB/html/_h_i_d.html).

**Comment by mondalaci** [comment]
Thanks guys!

I was testing ef7589d which seems to be bug free.

In the meantime, I talked to @Lauszus and he said that this might be due to a GCC bug, and it's worth to play with the opimization flags. I switched to master, and flashed the debug build which shouldn't be optimized. So far so good. I'll be keeping you in the loop.

**Comment by laxu** [comment]
Can confirm this is still happening on 8.3.3. Hopefully a fix is found soon as I can deal with having to reconnect it from time to time over not having working sleep and media keys.

**Comment by mondalaci** [comment]
After testing the most recent firmware 8.4.0 for about 100 hours, I'm confident that this bug has gone.

Excellent work, team!
