### ISSUE TITLE
Volume speed is crazy!

### ISSUE THREAD

**Issue by sad2project** [UltimateHackingKeyboard/firmware#139]
When adjusting the volume with the keyboard, the change of volume on my windows machines are crazy fast. A quick tap can increase the volume an amount between 15% to 30%. That's an insane amount for a quick tap. A single tap should be no more than a 10% jump, but preferably closer to 5%.

**Comment by mondalaci** [comment]
Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/72. We'll release a new firmware after a fair amount of testing.
