### ISSUE TITLE
Keymap switching bug 

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#145]
Mapping:
- mouse layer as a secondary role of a key (let's say the 'mouse' key)
- keymap switch on another key (let's say 'A' key) in the mouse layer

Expected behaviour:
- <mouse + tap A> switches to another keymap

Actual behaviour:
- <mouse + tap A> lights up the mouse indicator, but does not switch the layer
- <mouse + double tap A> switches the keymap

**Comment by kareltucek** [comment]
I consider this a low-priority issue (as well as #146), however, the behaviour is confusing, especially when combined with #146, since then the keyboard seems to have hanged. (One use case where the two issues may collide is cycling through  keymaps via a single shortcut.)

**Comment by mondalaci** [comment]
This is a duplicate of #69, but instead of removing this, I rather remove #69 because this one is better written.
