### ISSUE TITLE
Unable to make a text selection with the mouse feature with shift and two clicks

### ISSUE THREAD

**Issue by richrd** [UltimateHackingKeyboard/firmware#151]
Text selection works fine when clicking and dragging, but not without dragging.
With a regular mouse I can click where I want to start a selection, then hold shift and click somewhere else. 
That results in the text between the clicks getting selected. I can't seem to do that with the UHK mouse feature. I'm not sure if it's a firmware bug but I thought I'd report it here just in case.

**Comment by kareltucek** [comment]
Shift is not bound to shift key in the mouse layer by default. Bind it via agent and it will work as expected.

**Comment by richrd** [comment]
I should have realized that, thanks! Works great after remapping them.

I think it might be worth having both shifts bound by default as they're not used for anything on the mouse layer.

**Comment by kareltucek** [comment]
Definitely.

**Comment by mondalaci** [comment]
What a fabulous oversight on our part! Thanks so much for reporting!

Just fixed this in https://github.com/UltimateHackingKeyboard/agent/commit/80e8c014ec493378bde851c2ebfe4f906fbe2487

(The firmware builder uses Agent to generate the binary configuration that gets transferred to the EEPROM, so the above commit fixes this issue.)
