### ISSUE TITLE
Keys being held down are resent when layer is activated

### ISSUE THREAD

**Issue by kbranch** [UltimateHackingKeyboard/firmware#157]
When activating a layer (Mod, Fn or Mouse), it seems that any keys that were already being held down will be released, then any mappings associated with those keys on the new layer will immediately be pressed.  

For example, with the stock QWERTY layout, holding L followed by briefly pressing Mod (without ever releasing L) yields this:
22:59.0097 L (0x4C, BIOS 0x26) DOWN
22:59.0910 L (0x4C, BIOS 0x26) UP -> 812ms
22:59.0913 Right (0x27, BIOS 0xE04D) DOWN
23:00.0581 Right (0x27, BIOS 0xE04D) UP -> 668ms

Note that the same is not true when returning to the base layer - Mod + L followed by the release of Mod releases Down without pressing L.

I'm not sure I can call this a bug, but it is at least behavior that I am not personally a fan of.  I have backspace mapped to Mod + Space, and I somewhat frequently end up with troublesome unintended key presses like arrow keys or page up/down.

Edit: I have noticed this behavior on at least 8.4.4 and 8.4.2.

**Comment by mondalaci** [comment]
I can reproduce this, I agree that is not an ideal behavior.

**Comment by kbranch** [comment]
Wow, thanks for the quick turnaround!
