### ISSUE TITLE
[mac] caps lock light not turn on 

### ISSUE THREAD

**Issue by kuil09** [UltimateHackingKeyboard/firmware#161]
hi, my keyboard's caps lock led not turn on when I using on MAC.
But on windows, it works perfectly.

my firmware version is 8.4.5

**Comment by mondalaci** [comment]
It's probably not your UHK, but your Mac is misconfigured or running some application that affects caps lock. You can check caps lock state with another USB keyboard. Please confirm that it's not a keyboard issue, and once you got the solution, please let me know.

**Comment by mondalaci** [comment]
I assume that not the UHK is the culprit, so I'm closing this issue. Feel free to comment and I'll follow up / reopen the issue.

**Comment by mondalaci** [comment]
@kuil09 I think you have Karabiner Elements running and the "Manipulate LEDs" option is configured as such that caps lock is not shown on USB keyboards. Please confirm.

**Comment by kuil09** [comment]
I'm not using Karabiner but I refigure out whats going on here.

**Comment by mondalaci** [comment]
@kuil09 This must be a Mac specific issue.

Please let me know what causes it when you figured it out.

**Comment by kuil09** [comment]
Thansk to your fast response. Have a good day.

**Comment by kuil09** [comment]
@mondalaci 
Oh, It was just my mistake. 
It effected from layout for "Windows" and layout for "Mac".
Interest thing is capslock work perfectly just LED not working on different layout.

**Comment by mondalaci** [comment]
@kuil09 Can you please explain in detail which OS setting was wrong?

**Comment by kuil09** [comment]
My Mac version is High Sierra 10.13.6.
Problem happend when I changed Keymap for "QWERTY for PC"
In this situation capslock function works well but LED not turn on.

**Comment by mondalaci** [comment]
Thanks for explaining!
