### ISSUE TITLE
Buggy deactivation of layers

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#162]
Hi, me again :-). 

Long story short, toggled layer gets deactivated on keypress if there exists a keymap which has the corresponding layer switch mapped to the pressed key. 

Import the attached config and follow these steps:

- check that abbrev reads 'EMP'
- Doubletap left case button. This toggles mouse layer on.
- Press the hardware 'i' key. Mouse layer gets deactivated (even though i has no mapping in 'EMP keymap).

The same works with left mod key (which activates mod layer) and 'k' key.

firmware 8.4.5 

[UserConfiguration_isolated.txt](https://github.com/UltimateHackingKeyboard/firmware/files/2321030/UserConfiguration_isolated.txt)

**Comment by mondalaci** [comment]
Quite amusing! I can confirm this issue, and assigning it to @eltang.

@kareltucek Great find! When it comes to finding elaborate bugs, you have no match! :)
