### ISSUE TITLE
[MAC] caps lock led not turn on

### ISSUE THREAD

**Issue by kuil09** [UltimateHackingKeyboard/firmware#164]
I have a problem about capslock LED on MAC.
When I use caps lock, the LED not turn on.(But windows works properly.)
Is it firmware issue, right?

I'm using latest firmware 8.4.5.

**Comment by mondalaci** [comment]
Why did you open this issue? You already opened #161, I asked you a question, you didn't answer, and you then opened this issue. I'm closing this. Please follow up in the original issue.

**Comment by kuil09** [comment]
Sorry I missed I opened issue
