### ISSUE TITLE
Modify shortcut key modifier stick behavior

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#169]
The modifiers of a shortcut key should stick only as long as the current layer switcher key is being held. On the base layer, no layer switcher key is held, so the modifiers of shortcuts should not stick.

See https://github.com/UltimateHackingKeyboard/firmware/pull/168#issuecomment-418000863

**Comment by eltang** [comment]
How should they behave when a layer is toggled on?

**Comment by mondalaci** [comment]
It shouldn't stick if the layer is toggled on. Only when it's held.

**Comment by luteijn** [comment]
Since both ways of handeling this will be implemented anyway, please consider making it an option to configure the behavior for those of us that don't want modifiers to stick, or also want them to stick when the layer is toggled on. To avoid impact on the configuration format, perhaps consider some sort of non-serialized configuration section that just has key-value pairs parsed by the firmware (ignoring unknown keys for compatibility), to keep these kind of settings in until the next configuration version update where they can be folded into the main configuration.

**Comment by mondalaci** [comment]
We won't introduce key-value pairs because it doesn't fit well into the existing configuration format. Making modifers not stick is possible by implementing the relevant shortcuts as macros. Admittedly, this is a workaround. We might provide a better way of handling this eventually.

**Comment by dkilmer-mfj** [comment]
I don't understand the argument for having sticking be the default behavior when holding a layer-switching key (let alone a behavior that requires a workaround to avoid). The argument against it is that it assumes a use-case for layers that isn't universal, acts in a context-dependent way, and has side-effects that aren't obvious to the person setting up a keyboard mapping. All of those arguments are obviated by an option to disable sticking.

My use case is that the Mod layer is for text editing/manipulation. So I have arrows, backspace and so forth mapped there, as well as things like Cmd-C, Cmd-V, Cmd-A, etc. Any time I use a key that has Cmd as a modifier, it carries over to my next press of an arrow key, taking me to the top or bottom of a document. To avoid this behavior I have to map 11 different keys on the Mod layer to macros on the Mac.

I think the option to disable sticking should be a prerequisite to implementing the feature, not something to maybe do later.

**Comment by mondalaci** [comment]
@dkilmer-mfj I don't think sticking affects your use case given that modifiers get unstick as soon as another key gets pressed.

**Comment by kareltucek** [comment]
@dkilmer-mfj are you on the newest firmware? (8.4.5) This functionality used to be buggy...

**Comment by dkilmer-mfj** [comment]
I have never been so happy to have misunderstood something :). The latest version of the agent (1.2.8) is bundled with 8.2.5, which is what I'm using.

**Comment by dkilmer-mfj** [comment]
Still happens with 8.4.5. Seems to be Mac only (similar use case on Linux - Ctl-C and Home both mapped to keys on mod layer, pressing those in sequence with mod held down does not go to top of the document). I can create an issue for it.

**Comment by mondalaci** [comment]
#170 has been opened by @dkilmer-mfj in the meantime containing a detailed description. Let's not talk about it in this issue and handle it separately from now on.

**Comment by owlstead** [comment]
Sorry, but that one is now closed and this one is still open, so what is the status of this bug?

**Comment by mondalaci** [comment]
This issue is still present in the latest 8.5.3 firmware. I've just bound Alt+Tab to the ` key of the base layer. Pressing the key made Alt stick which is not considered to be the correct behavior according to the above.
