### ISSUE TITLE
Restructure keymap

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#17]
Currently, the default keymap is a 2 dimensional array of key actions. Robi implemented it a while ago which was a step forward but our modular architecture and configuration structure calls for a different hierarchy.

A keymap should be composed of 4 layers. A layer should be composed of a set of modules. A module should be composed of an array of key actions.

The array should be declared as

uhk_key_t currentKeymap[[LAYER_COUNT](https://github.com/UltimateHackingKeyboard/firmware/blob/1f8fc560e450b7e2d5a4ef84789c3a52d6375b36/right/src/layer.h#L11)][[SLOT_COUNT](https://github.com/UltimateHackingKeyboard/firmware/blob/1f8fc560e450b7e2d5a4ef84789c3a52d6375b36/right/src/slot.h#L28)][[MAX_KEY_COUNT_PER_MODULE](https://github.com/UltimateHackingKeyboard/firmware/blob/1f8fc560e450b7e2d5a4ef84789c3a52d6375b36/right/src/module.h#L33)]

and it shouldn't be `const` because it will be changed runtime.

@algernon It would be awesome if you could refactor the current code according to the above because the more we wait, the more refactoring we'll have to do later down the road.

**Comment by algernon** [comment]
Sure thing. This sounds like an easy thing :)
