### ISSUE TITLE
multimedia key next and previous do not seem to work on macos high siera 

### ISSUE THREAD

**Issue by RMHogervorst** [UltimateHackingKeyboard/firmware#171]
I'm not sure on which repo this should be but
see 
https://github.com/UltimateHackingKeyboard/agent/issues/775

The next track / prev track buttons don't seem to work on macos. I can't seem to find a way to display the codes send

**Comment by mondalaci** [comment]
This is rather an Agent issue. I'm closing this, and will address the other issue.
