### ISSUE TITLE
mouse scroll speed deceleration doesn't work

### ISSUE THREAD

**Issue by mgulick** [UltimateHackingKeyboard/firmware#178]
Hi,

Hitting the deceleration button while scrolling with the mouse doesn't have an effect.  These are my settings:
Initial speed: 20
Base speed: 20
Acceleration: 20
Decelerated speed: 10
Accelerated speed: 50

The acceleration button works as expected.

I have observed that if I change the "accleration" field to 10, then hitting the decelerate button will now slow down the scrolling to 10.  So it appears almost like the "acceleration" and "decelerated speed" fields are reversed.

Agent version 1.2.9, Firmware 8.4.5.

Thanks!

**Comment by mondalaci** [comment]
Thanks for reporting! This turned out to be an Agent issue. Fix included into [Agent 1.2.10](https://github.com/UltimateHackingKeyboard/agent/releases/tag/v1.2.10).

**Comment by mgulick** [comment]
Thanks for fixing!
