### ISSUE TITLE
Some keys have key repeating issues

### ISSUE THREAD

**Issue by old9** [UltimateHackingKeyboard/firmware#179]
Kailh Red switch, Windows 10, firmware 8.4.5

Some of my keys have **repeaating** issues, it's like more then one keydown/keyup pair events are triggered **wiwth** a single stroke.

Since the problem persists even when I downgraded the firmware to the bundled version 8.2.5, I'd say it might be a hardware problem? like the kailh **switchc** thing? 

(You can tell the problem in my spellings, notice the extra 'w', 'a', and 'c's.)

at least these keys are affected on my keyboard:
1, 4, q, w, a, s, c, v, h

Any **suggesstions**?

**Comment by mondalaci** [comment]
This is probably a hardware issue. Please shoot us an email to support@ultimatehackingkeyboard.com including your order id, and we'll help you.
