### ISSUE TITLE
's' char typed with delay during macro playback

### ISSUE THREAD

**Issue by p4elkin** [UltimateHackingKeyboard/firmware#181]
I've been trying to create a macro action that would open spotify via spotlight search and stumbled upon a weird issue: the spotlight is opened just fine via key press/release macro instructions, but the 'type text' command yields 'potifys' instead of 'spotify'. Oddly enough - it looks like the issue is only with 's' character. I do not have any additional magic attached to the 's' key if it matters.

here's the macro config (i intentionally added a 2s delay before typing to eliminate possible timing issues):
<img width="1316" alt="default" src="https://user-images.githubusercontent.com/1240136/46475454-3d562600-c7ee-11e8-86d1-fb6bea66744f.png">

 here's what spotlight shows after all:
<img width="717" alt="default" src="https://user-images.githubusercontent.com/1240136/46475499-58c13100-c7ee-11e8-8363-48ed40df1291.png">

p.s.: despite of this small issue, I am largely enjoying my UHK, thanks for the awesome work!

**Comment by mondalaci** [comment]
Thanks for your report and the nice words! @eltang will look into it.

**Comment by eltang** [comment]
I cannot reproduce this issue on macOS 10.14.

@p4elkin By the way, a tap action consists of a press and a release, so the release action in your macro is redundant and can be removed.

**Comment by mondalaci** [comment]
Not only the release action is redundant, but the proper shortcut should be Cmd+Option+Space, not Ctrl+Option+Space. Works perfectly on my end. Closing this issue.

**Comment by mondalaci** [comment]
By the way, I tested with the most recent 8.5.1 firmware.

**Comment by p4elkin** [comment]
> but the proper shortcut should be Cmd+Option+Space

@mondalaci the spotlight shortcut is modifiable in macos and it opens just fine with my macro, with the only issue that 's' chars are messed up. E.g. 'foosbar' is also typed as 'foobars' in my case.

@eltang thanks for heads up (though I was just playing around with tap/press/release variants to see if it helps).

I am ok with closing this if you can't reproduce it - maybe the issue is with my particular keyboard. 
BTW, another observation - if I assign the secondary role to 's', it primary role starts to be faulty ('s' keystroke misses and such). if I assign the same secondary role to e.g. 'a' - the experience with typing 'a' is still normal.

I'll try the latest firmware asap.

**Comment by mondalaci** [comment]
@p4elkin I stand corrected regarding the Spotlight shortcut. Please retry. I'll reopen this issue if needed.

**Comment by p4elkin** [comment]
@mondalaci I installed the latest firmware and everything's looking in order now! Thanks for fast answers and cooperation.
