### ISSUE TITLE
Alphabetic keys do not play well with secondary roles

### ISSUE THREAD

**Issue by p4elkin** [UltimateHackingKeyboard/firmware#187]
I have tried to replicate the 'vim mode' workflow that was really convenient with Karabiner back in days: while holding 's' the hjkl turn into arrows. In UHK terms - I assigned 'switch to MOD layer' as secondary role to 's' key. 

However, now when typing words fast, often the secondary role kicks in for 's'. From the event monitor I see that secondary role activates when some other key is pressed and it looks like **if I type 'st' (even if really quickly) - it is treated as if I pressed 't' while holding 's' (and => MOD).** 

I tried to find an existing issue for this - looks like there're some quirks in a similar spirit, but not exactly the same.

This issue of course can be observed not only for the alphabetic keys, but I think they are the most prominent example. 

Do you think this might be mitigated by maybe fiddling with debounce algorithm or some other settings?

firmware version: 8.5.2 
agent version: 1.2.11
os: macos sierra

**Comment by luteijn** [comment]
Using Space with shift as secondary function and will occasionally get something run togeter likeThis when typing quickly. Perhaps it would be better if there was some sort of setting to delay going to 2nd role for x ms. Of course, ideal settings would differ for different people.

**Comment by p4elkin** [comment]
Another aspect of this is the following: in my IDE I use alt + Enter shortcut extensively. On my UHK alt is facilitated via secondary-role, at the same time Enter key has a secondary role assigned (mouse layer). **So, when I hold ALT, tapping ENTER triggers its secondary role. (Should this be extracted into a separate issue?).**

@luteijn I agree that the simplest solution to this (in ideal world) would be a threshold delay before the secondary role kicks in.

Maybe the maintainers could give some initial pointer at the code base part to look at for investigation and experiments?

**Comment by mondalaci** [comment]
I rather wouldn't introduce a (configurable) delay. Accidental activation is the nature of this feature. A workaround I'd consider is to use a least frequently used key.

https://github.com/UltimateHackingKeyboard/agent/issues/792 may help you a bit in the future.

As for the firmware codebase, feel free to search for "secondaryRole", perferably in a case insensitive fashion. Please note that we can't provide help with custom implementations. We must focus on pressing issues.

**Comment by p4elkin** [comment]
> A workaround I'd consider is to use a least frequently used key.

FWIW - it is just so much nicer to be able to trigger MOD and MOUSE layers without having to leave the home row compared to e.g. having to hold the Mouse key with the pinky all the time (mine gets quite sore). And it somehow did work quite non intrusively in Karabiner (not the Elements version ofc). 

> feel free to search for "secondaryRole", perferably in a case insensitive fashion. 

thanks, I've done some git log grepping and checked out this awesome blogpost of yours (https://www.toptal.com/embedded/from-the-ground-up-how-i-built-the-developers-dream-keybooard) and things are much clearer now.

**Comment by kareltucek** [comment]
I am also interested in this. I find the idea of using home row keys as modifiers quite interesting since it solves multiple ergonomy problems I've been struggling with. However, I am skeptical about predictability of behaviour of such delay mechanism too...

Regarding the PR (it seems I cannot comment on the PR itself)... Could you publish a firmware release package for testing please? (Run /firmware/scripts/make-release.js package via node, then upload the uhk-firmware...tar.bz2 from the same directory.)

**Comment by p4elkin** [comment]
I've created a pre-release of the modified algorithm in my fork - feel free to try it out (more details in description there):

https://github.com/p4elkin/firmware/releases/tag/8.5.3.187-1

**Comment by kareltucek** [comment]
Works pretty well now:

- I have not noticed any chatter 
- Secondary roles don't kick in while writing (that's fine).
- Key supression does not work - if I release standard layer switcher while holding a key, the base layer of the key gets activated. (That's not fine - a key should act according to its activation action/role until released even if modifiers/layer switchers change in the meantime.)
- The algorithm seems to interfere with modifiers (e.g., shift) - writting "Star" often results in "star" when s key has some secondary role. Some logs here 
[log_star.txt](https://github.com/UltimateHackingKeyboard/firmware/files/2542036/log_star.txt) 
[log_star_regular_firmware.txt](https://github.com/UltimateHackingKeyboard/firmware/files/2542037/log_star_regular_firmware.txt)
- I suffer some minor problems with correct recognition of some secondary roles (I use them even on "regular" layer switcher keys), but investigation shows that these strokes are totally similar to my standard writing. If I focus more on releasing keys properly, it works fine. 
[log_secondary.txt](https://github.com/UltimateHackingKeyboard/firmware/files/2542179/log_secondary.txtl) 
- (ofc, layer toggling and keymap switching is in a pretty bad shape atm.)

I've measured some values while writting a piece of text (I was curious about the intervals, and though that it might probably be of some use to you too):
- interval between keydown and keyup of one key varies between 90ms and 150ms most of the time (avg: 110ms)
- interval between keydowns of two consecutive keystrokes varies between 90ms and 250ms (avg: 150ms)
- overlaps on keys while writing are sometimes as high as 100ms (
[log.txt](https://github.com/UltimateHackingKeyboard/firmware/files/2542060/log.txt) mesured with standard firmware )

**Comment by p4elkin** [comment]
thanks for the elaborate report! Most of the points do ring the bell and I was planning to investigate them as next steps. With these logs that should be easier to test/reproduce/debug

**Comment by kareltucek** [comment]
- writing two characters which both have some secondary role produces twice the second letter. E.g., with secondaries on "s" and "d" keys, writing "speeds" results in "speess"

**Comment by p4elkin** [comment]
> writing two characters which both have some secondary role produces twice the second letter. 

yeah, I mentioned that as a known issue - need to see how to mitigate that. Might be a tad tricky, but should be doable.

**Comment by p4elkin** [comment]
Just released yet another iteration which contains a rather refactored version of the previous release plus a couple of fixes for annoying issues. 

If nothing major pops-up, the next thing would be to come up with some good strategy for key suppression.

https://github.com/p4elkin/firmware/releases/tag/8.5.3.187-2

**Comment by kareltucek** [comment]
Seems good. Actually you seem to have solved some problems I've had with the firmware since last release (probably lowered some hard coded timeouts?).

One new (?) problem I've noticed - writing "user" results in "usre" when wrote fast, while having secondary on "s". While the action key is being postponed for a brief moment, the "r" is not.

**Comment by p4elkin** [comment]
> One new (?) problem I've noticed - writing "user" results in "usre" when wrote fast

yeah, indeed can confirm - there is some quirky logic related to enforcing the order of the sent keys (so that the deferred are sent first) and I kinda cut one corner in there yesterday thinking that it will not affect the other functionality. Will look into it asap.

> Actually you seem to have solved some problems I've had with the firmware since last release (probably lowered some hard coded timeouts?)

Nope, those weren't changed - just did some refactoring and tried to take care of the state mgmt a bit more carefully (though obviously there's still stuff to do).

**Comment by p4elkin** [comment]
uploaded a new artifact that has a tentative fix for the ordering issue. I will take a closer look when I've more time tho.

https://github.com/p4elkin/firmware/releases/edit/8.5.3.187-3

**Comment by kareltucek** [comment]
Just to let you know - I've implemented a new modifier on my macro fork which allows postponing activation of keys, which can be used to mimic some of the discussed behaviour. Pretty imperfect, but can be configured on per-key basis, which makes it a bit more versatile than a global implementation on firmware side.

At the moment, I am experimenting with the following setup:

    $suppressKeys delayUntilReleaseMax 200
    $suppressKeys ifNotPlaytime 199 goTo 4
    $holdLayer mouse
    $break
    $suppressKeys write s
