### ISSUE TITLE
Debounce timestamps stored as uint8_t instead of uint32_t 

### ISSUE THREAD

**Issue by p4elkin** [UltimateHackingKeyboard/firmware#192]
While fiddling with the firmware I've noticed that the ```CurrentTime``` is stored as uint32_t, which seems to be a correct type for milliseconds. However, the ```key_state_t#timestamp``` is declared as uint8_t which is just one byte and won't be able to accomodate anything larger than 255. 

Or am I missing smth here?

**Comment by mondalaci** [comment]
According to my memory, our code is actually fine in this respect, but don't remember why.

@eltang Would you explain why?

**Comment by p4elkin** [comment]
If I understand it correctly subtracting such a timestamp from the CurrentTime and casting back to uint8 will produce quite random results, making the debounce algorithm also quite random.

**Comment by p4elkin** [comment]
UPD: looking further into it - as long as the debounce timeout stays within 0..255, the timeout tracking should be indeed calculated correctly.
