### ISSUE TITLE
Impossible to switch off Fn mode after switching key maps

### ISSUE THREAD

**Issue by owlstead** [UltimateHackingKeyboard/firmware#194]
Reproduce:

 - create a button that *toggles* the Fn layer;
 - use this mode to switch to a map that only allows you to *activate* Fn layer;
 - now you can click Fn buttons all you want, but Fn mode won't switch off, making it impossible to ever get out of the Fn layer.

Simple resolution: allow Fn toggle to switch off if Fn active button is pressed. Furthermore, switch to the base layer once the map is changed.

Better resolution: have one *current* layer which is the base layer by default. This current layer can be changed by *toggling* a another layer. Toggling or deactivating the current layer will of course get you back to the base layer. The activate buttons temporarily switch away from this current layer. This allows you to switch to one layer to another and temporarily use functions from e.g. the Fn layer (volume up / down from the mouse layer).

**Comment by owlstead** [comment]
Reproduce:

 - create a button that *toggles* the Fn layer;
 - use this mode to switch to a map that only allows you to *activate* Fn layer;
 - now you can click Fn buttons all you want, but Fn mode won't switch off, making it impossible to ever get out of the Fn layer.

Simple resolution: allow Fn toggle to switch off if Fn active button is pressed. Furthermore, switch to the base layer once the map is changed.

Better resolution: have one *current* layer which is the base layer by default. This current layer can be changed by *toggling* a layer. The activate buttons temporarily switch away from this current layer. This allows you to switch to one layer to another and temporarily use functions from e.g. the Fn layer (volume up / down from the mouse layer).

**Comment by mondalaci** [comment]
Thank you for reporting this issue! I understand that your suggested "better resolution" is more general, but I much prefer your "simple resolution" because it's simpler from a user standpoint, and sufficiently flexible for most, so we'll implement it.

**Comment by owlstead** [comment]
This can be closed in favor of [issue #199](https://github.com/UltimateHackingKeyboard/firmware/issues/199) I suppose which adds way more detail and is more generalized to boot.

**Comment by kareltucek** [comment]
Oh, sorry for the duplicate, I missed the toggle/activate difference when reading this issue ;-)

**Comment by owlstead** [comment]
Meh, I'm all in favor of more generalized fixes and sometimes dupes are hard to find. I'm closing this issue with extreme prejudice and I'll thumb up #199.
