### ISSUE TITLE
Toggle mouse takes precedence over Mod + Mouse, making this combination impossible for CAPS LOCK if toggle is used

### ISSUE THREAD

**Issue by owlstead** [UltimateHackingKeyboard/firmware#195]
I've tried to use Mod + Mouse to switch on CAPS lock. However, after changing Mouse to Toggle mouse this becomes impossible as the toggle seems to take precedence over the Mod + Mouse combination. Possibly combinations could take precedence over any toggle behavior. I'm filing this separate from other ideas with regards to CAPS lock as I think this could be seen as a bug rather than a feature request.

**Comment by owlstead** [comment]
I've tried to use Mod + Mouse to switch on CAPS lock. However, after changing Mouse to Toggle mouse this becomes impossible as the toggle seems to take precedence over the Mod + Mouse combination. Possibly combinations could take precedence over any toggle behavior.

**Comment by mondalaci** [comment]
Thank you for reporting this bug! A toggle layer action shouldn't take priority over an already active layer, indeed. We'll fix this.
