### ISSUE TITLE
Caps Lock as primary role not working when secondary role is set to a layer

### ISSUE THREAD

**Issue by bhaeussermann** [UltimateHackingKeyboard/firmware#202]
When I set a key's scancode to "Caps Lock" and the secondary role to "Mouse", the mouse layer activates when I hold the key down, but tapping the key does not toggle caps lock.

![screenshot 2018-12-19 at 22 27 02](https://user-images.githubusercontent.com/7482216/50246421-f4ba0c00-03dd-11e9-85e5-0918a9a65605.png)

Agent: 1.2.12
Firmware: 8.5.3

**Comment by bhaeussermann** [comment]
An observation: when the key is set to "Caps Lock" with no secondary role, it toggles caps lock, but only when I press the key down long enough. Tapping it quickly yields no effect. Perhaps the delay required to toggle caps lock overlaps with the delay where the secondary role takes over.

I can't tell why caps lock should have this minimum delay to activate. Perhaps that is the actual bug.

**Comment by mondalaci** [comment]
This feature works flawlessly on my side. Are you using the latest 8.5.3 firmware? If not, please update your UHK via Agent.

**Comment by bhaeussermann** [comment]
I have the latest firmware (8.5.3) installed. It seems this does work as intended on Windows; the issue reported occurs on Mac OS.

**Comment by mondalaci** [comment]
Are you using Karabiner Elements on your Mac, or anything else that might interfere with keyboard input?

**Comment by bhaeussermann** [comment]
No :\

**Comment by mondalaci** [comment]
Then I don't have an idea, but this should be an installation-specific issue on your side.

**Comment by eltang** [comment]
As a way of filtering out accidental keypresses, macOS only activates Caps Lock if the length of the keypress is above a certain threshold. The firmware currently sends the shortest possible keypress, so a delay must be added to fix the problem.

**Comment by mondalaci** [comment]
@eltang Haven't ever heard about this (mis)feature of OSX. Does it only pertain to Caps Lock?

**Comment by jfieber** [comment]
It is a "feature".  Some info https://apple.stackexchange.com/questions/81234/how-to-remove-caps-lock-delay-on-apple-macbook-pro-aluminum-keyboard-when-booted

**Comment by mondalaci** [comment]
Ok, this was eye-opening. Thanks for the sharp insight, @eltang, and the further reference, @jfieber. I'm closing this, given that this is an OSX-specific behavior that I don't believe should be addressed on the firmware level. This can be worked around with a UHK macro.

**Comment by mondalaci** [comment]
Slight correction: This cannot be worked around for dual-role keys, and this feature should be disabled in OSX.

**Comment by bhaeussermann** [comment]
Thanks! I found a way to disable the feature in Mac OS: [Karabiner Elements issues: "any reliable way to remove capslock delay on macos?"](https://github.com/tekezo/Karabiner-Elements/issues/1423). It's not ideal, but I couldn't find any other way to do it.

Now I have Karabiner handling the Caps Lock, but the Caps Lock LED is not lighting up, even though the "Manipulate LED" option in Karabiner is checked. However, this LED function does not work with my Microsoft Comfort Curve Keyboard either, so I guess I will give the UHK the benefit of the doubt on that one and not log it as an issue. At least my Caps Lock key is working now :).

**Comment by mondalaci** [comment]
@bhaeussermann Thanks for elaborating about this! The information you shared should be useful for others, too.
