### ISSUE TITLE
"Type Text" Macro output is OS input layout dependent

### ISSUE THREAD

**Issue by vvolkgang** [UltimateHackingKeyboard/firmware#204]
"Type text" macro output will vary depending on which input layout is currently selected in the OS.

Tested the default "Go to UHK site in browser" macro with pt-PT layout instead of en-UK,

Expected: `https://ultimatehackingkeyboard.com`
Got: `httpsç--ultimatehackingkeyboard.com`

Notice the `ç--` part, they use the same keystrokes as `://` 

Changing the layout to en-UK fixes it. 

For reference, a pt-PT layout keyboard: 
![pt-PT](http://www.ncb.pt/catalog/images/products/hardware/peas-para-portateis/teclados-p-portateis/MP-09G36P0-6981W.jpg)

Firmware: 8.5.3
OS: Windows 10
Agent: 1.2.12

**Comment by mondalaci** [comment]
It's layout dependent, and it will always be given the reasons mentioned in https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk
