### ISSUE TITLE
Macro interprets incorrect

### ISSUE THREAD

**Issue by Peter-Odd** [UltimateHackingKeyboard/firmware#208]
I just created a macro named aruba containing the text
life-is-easier-on-aruba
but when i execute the macro the text
life+is+easier+on+aruba
is displayed, i.e. plus sign is being used instead of dash sign.

Agent version: 1.2.12
Firmware 8.5.4 is running on the left keyboard half.
Firmware 8.5.4 is running on the right keyboard half.

**Comment by mondalaci** [comment]
Are you using a non-US OS keymap? If so, set your OS keymap to the US keymap, and retry.

Please also read https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk

**Comment by Peter-Odd** [comment]
I do, that might be it. My bad, thank you for clarification. I'll take a look at the link.
