### ISSUE TITLE
Secured keymap activation

### ISSUE THREAD

**Issue by piratk** [UltimateHackingKeyboard/firmware#211]
I would like to have a possibility to have a keymap with sensitive macros, such as passwords, but this is not possible because:

* It is too easy to read the current configuration of the keyboard, and any secrets would be revealed. 
* There is no way to protect a keymap activation, other then obscuring the activation path. 

If some keymaps would require a sequence of keys to be pressed before they are truly activated, then this would be possible.

**Comment by mondalaci** [comment]
It is fundamentally insecure to store highly sensitive information on your UHK given that its EEPROM contains all your configuration unsecured. It'd take a vast effort to secure the EEPROM, and we don't plan to do it.

We'll provide a per-macro option to mark select macros as secure. This will make our yet to be implemented cloud sync service not expose them. We don't plan to add any related security features.
