### ISSUE TITLE
Merge leftKeyStates and rightKeyStates into keyStates

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#22]
And then we could iterate slots at the top level.

**Comment by mondalaci** [comment]
@algernon Would you be interested in doing this one? Apparently, the code is getting progressively harder to maintain around this spot. I plan to refactor the firmware in the near future, so I can do it too if you want me to, although I'll have plenty of stuff to refactor besides this one.

**Comment by algernon** [comment]
I'd leave it to you, if you don't mind. I'd like to inch towards config parsing slowly.

**Comment by mondalaci** [comment]
Ok, good thinking!

**Comment by mondalaci** [comment]
Done.
