### ISSUE TITLE
repeating macros

### ISSUE THREAD

**Issue by bistabil** [UltimateHackingKeyboard/firmware#227]
I don't know if this feature already exists and it does than it's hard to find.
Is it possible to create macros that will repeat:
1. indefinitely
2. until some key is pressed
3. set amount time without having to copy macro actions multiple times (counter)

In the page featuring the keyboard I've found following text:
"A macro action is composed of a sequence of key actions, mouse actions and delays. **It will also have a loop flag which will loop the macro until the associated key is pressed.**"

**Comment by mondalaci** [comment]
This is not implemented yet, and I doubt its usefulness. What's your use case?

**Comment by richrd** [comment]
I guess point 2. might be useful for some special cases like gaming? I don't have a personal usecase right now though.

**Comment by bistabil** [comment]
@richrd I have multiple usecases and yes, they are for automating gaming tasks.

I've thought about this a bit more and now I see potential issue if macro would repeat while at the same there is no way of manually stopping it.
Let's say in middle of macro I am interrupted and have to switch focus to different program.
Repeating (or any long) macro could create a lot of mess.

@mondalaci is it currently possible to forcefully cancel running macro?

As for loops I can use unofficial firmware.

**Comment by mondalaci** [comment]
It's not possible to forcefully cancel a running macro. We were talking about implementing a macro cancellation action eventually.

Case 2 might be implemented in the future. The other cases seem rather specific. Chances are good that [Karel's UHK firmware](https://github.com/kareltucek/firmware) supports these cases.

**Comment by mondalaci** [comment]
I'm sorry, but it's too much of a niche feature, and I rather wouldn't get it included into the main firmware. Feel free to implement it @kareltucek in your fork if you see fit.

**Comment by kareltucek** [comment]
All cases are already more-or-less supported. The last release also contains a command to stop running macros, which I have totally forgotten about and didnt mention in the changelog :-).
