### ISSUE TITLE
Need firmware update LINIVISION HDMI KVM04

### ISSUE THREAD

**Issue by shanechak** [UltimateHackingKeyboard/firmware#233]
Hello,

I am New user of UHK and i need firmware update for LINIVISION HDMI KVM04 to support it.
Specs Page:
https://www.amazon.com/LINOVISION-monitor-Keyboard-control-Players/dp/B07NZZ6RQW/ref=sr_1_1?keywords=linovision+hdmi+kvm04&qid=1562073062&s=gateway&sr=8-1

Thanks

**Comment by mondalaci** [comment]
Hi there!

I firmware update may address this issue, but not the firmware update of your UHK. The firmware of your KVM should be updated. Unfortunately, many KVM switches don't handle the sophisticated USB interface of the UHK. Please see our KVM switch compatibility page at https://ultimatehackingkeyboard.com/kvm-switch-compatibility for more information.

**Comment by shanechak** [comment]
Are they new kvm models they support from the companies mentioned in your
website?

Best regards
Kumar S S

**Comment by mondalaci** [comment]
I don't know for sure. The new KVM models should be tested.

**Comment by mondalaci** [comment]
I'm closing this issue, but any more questions, feel free to follow up.
