### ISSUE TITLE
Slightly different timing between macro and key

### ISSUE THREAD

**Issue by wofwofwof** [UltimateHackingKeyboard/firmware#234]
Hello,

Firmware 8.5.4

I use cyclefokus [https://github.com/blueyed/awesome-cyclefocus] on awesome window manager and register a small difference between macros and keys.

I use the shortcut <Alt><Tab> to switch between windows. If I use a the keypress configuration for <Alt><Tab>, everything works fine. If I use a macro that just contains the entry:
Tap key: Tab LAlt
it wont work any more, the graphic is not shown. Sendkeys shows, that the keycodes are the same. Cyclefocus is pretty fickling for the timing. I'm pretty sure, that there is a timing difference between the macro and the keypress configuration.

It can be fixed in this case in cyclefocus, but still be aware, that there are differences here.

cheers

wof

**Comment by mondalaci** [comment]
A small number of applications are sensitive regarding the order of modifiers sent by the UHK. awesome-cyclefocus seems to be one of them. Please modify your macro to first hold Alt, then delay a bit, then tap LAlt.

I'm closing this issue, but any further problems, feel free to let me know.
