### ISSUE TITLE
Make some keys sticky

### ISSUE THREAD

**Issue by Cretezy** [UltimateHackingKeyboard/firmware#279]
I use Ctrl + Tab to switch between files in my IDE, and I would like to make that sticky.

I see that only Tab/arrows + alt/super is allowed to be sticky, but it would be nice to be able to modify the stickiness though the agent as well (should I move this ticket there?).

For now, I have downgraded to 8.7.0, since I can't get the MCU IDE to run on my Linux configuration.

**Comment by mondalaci** [comment]
Which IDE treats Ctrl+Tab the way OSes treat Alt+Tab?

**Comment by Cretezy** [comment]
![image](https://user-images.githubusercontent.com/2672503/75182385-47900180-570e-11ea-9969-d7be83d64376.png)

IntelliJ has a switcher using Ctrl + Tab (or at least that's what mine is set as) to switch between files. If it's not sticky, it would only switch to the last opened file

**Comment by mondalaci** [comment]
Gotcha, thanks!

Please this make this shortcut sticky, too, @kareltucek.

**Comment by kareltucek** [comment]
Sure.

**Comment by Cretezy** [comment]
Wouldn't it be better to be able to configure which are sticky? I can imagine others using different binds for different programs

Thank you though!

**Comment by mondalaci** [comment]
@Cretezy I'd much rather make sticky keys hardcoded and make things work without configuring anything.
