### ISSUE TITLE
Sticky layer modifications should cancelled on keymap change

### ISSUE THREAD

**Issue by piratk** [UltimateHackingKeyboard/firmware#292]
When keymap is changed, sticky layer modifications needs to be cancelled.  

This can be an issue if  a keymap is activated that doesn't have the layer in question populated, and thus there will be no exit available from that layer activation.

**Comment by mondalaci** [comment]
This is quite an edge case, and it boils down to an opinionated behavior.

I think the right behavior is the least surprising one, and the way I see it, a layer that was manually toggled should be manually untoggled.

This is not the only way users can corner themselves. One can create a keymap from which it's not possible to switch back to other keymaps. I'd leave it users to make any configuration and deal with the consequences. The opportunity is there for them to make corrections.
