### ISSUE TITLE
Remove SECONDARY_AS_REGULAR_HOLD

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#295]
Please don't branch based on `SECONDARY_AS_REGULAR_HOLD`, but rather keep the currently active code, and delete the inactive code along with this macro because the code is already very complex, and I'd like to keep it as simple as possible.

**Comment by kareltucek** [comment]
Yep. Intended to remove it after receiving more feedback (or not receiving any negative), but it can as well be removed at once.
