### ISSUE TITLE
Per-keymap mouse speed

### ISSUE THREAD

**Issue by m42e** [UltimateHackingKeyboard/firmware#300]
I have the keyboard sometimes connected to my mac, sometimes to my windows device.
I saw a huge difference in how the mouse speed is interpreted in both. 
Would it be possible to save or overwrite the mouse speed in the current active keymap? This would really help me a lot.

Thanks.

**Comment by mondalaci** [comment]
@m42e How about adjusting the mouse speed on Windows / Mac instead?

**Comment by m42e** [comment]
@mondalaci This would affect all other mouse-devices, too. and then either all are very slow or very fast. I mean it is not that much of a deal, but it would be anice feature.

**Comment by mondalaci** [comment]
Gotcha. I think it's a valid use case which was requested by others too, so we'll make it possible to override global mouse speed settings on a per keymap basis. This will require substantial development regarding Agent too, and will take a while to implement.

**Comment by m42e** [comment]
I may be able to provide a PR for the change of the firmware as a proposal. But I am not too much into the agents stuff.

**Comment by mondalaci** [comment]
Thanks, but the firmware side is much dependent on Agent, and the on the updated configuration structure in specific. We'll handle this.

**Comment by steamraven** [comment]
I like the idea of moving a lot of the configuration into the keymap settings. This allows you to easy switch between preset settings.

**Comment by mondalaci** [comment]
This is a relatively niche feature, but it'll be possible via [smart macros](https://github.com/UltimateHackingKeyboard/firmware/issues/351).

**Comment by mondalaci** [comment]
Implemented via smart macros, will be included in the next firmware release.
