### ISSUE TITLE
Question: Is it possible to map Programmer Dvorak on UHK?

### ISSUE THREAD

**Issue by trueneu** [UltimateHackingKeyboard/firmware#303]
Hi!
I'm using a Programmer Dvorak layout which remaps the numeric row into this: `$&[{}(=*)+]!#`, and this with Shift pressed: `~%7531902468 <tilde>`. Is there any possibility I can map this without using OS keyboard layouts? For example, pressing `1` emits scancode for `Shift+7` and pressing `Shift+1` emits `Shift+5`?

**Comment by mondalaci** [comment]
Hi there! This will be possible as soon as https://github.com/UltimateHackingKeyboard/agent/issues/617 gets implemented. In the meantime, I think it's possible with [Karel's UHK firmware fork](https://github.com/kareltucek/firmware).
