### ISSUE TITLE
Key runaway/debounce

### ISSUE THREAD

**Issue by rom-burner** [UltimateHackingKeyboard/firmware#312]
Several times a week I get a key runaway, where I finish typing and the last key pressed is rapidly repeated, usually a space key but sometimes enter or other characters.  The repeated character can be stopped with any other keyboard input.

It doesn't happen with other USB keyboards.

Agent = 1.5.4, firmware = 8.10.1, linux 5.8.14, xorg 1.20.9

Not sure when it started, but the problem has been noticeable for at least the last half dozen or so firmware updates. Any ideas?

**Comment by mondalaci** [comment]
Please check out https://ultimatehackingkeyboard.com/knowledgebase?q=repeat and let me know if this problem persists.

I'm closing this issue, but feel free to follow up.
