### ISSUE TITLE
USB resets on Ryzen via USB 2.0 happen frequently on Linux with firmware 8.10.1

### ISSUE THREAD

**Issue by lo48576** [UltimateHackingKeyboard/firmware#314]
## Environment
* Gentoo Linux, kernel 5.9.2
    + Also with 5.8.14, 5.8.17 and 5.9.0, same problem happens.
* UHK is connected to USB 2.0 port, and XHCI driver is used (xhci_pci, xhci_hcd)
* UHK firmware 8.10.1

## Expected result
UHK works normally.

## Actual result
With linux kernel built with `CONFIG_HIGH_RES_TIMERS=y` **OR** `CONFIG_NO_HZ_IDLE=y` (or both), UHK is frequently disconnected (i.e. key inputs are ignored intermittently) and `dmesg` reports errors:

> [  286.223211] usb 1-10.3: reset full-speed USB device number 7 using xhci_hcd

![screenshot-2020-10-27-214313+0900](https://user-images.githubusercontent.com/1246590/97801137-f31a2a00-1c7d-11eb-8513-3a90d1004f0e.png)

### Workaround
If you are suffering from this, build the linux kernel with `CONFIG_HIGH_RES_TIMERS=n`, `CONFIG_NO_HZ_IDLE=n`, **AND** `CONFIG_HZ_PERIODIC=y`.

### Cause
~~I'm almost sure the patch for #269 caused this problem.~~
(I tried to confirm that, but I couldn't. The USB reset happened during firmware flashing, and left half of the keyboard seems to be bricked :rofl:)

**EDIT**: With firmware 8.10.0 (only with right half of the keyboard), this error still happens. Now I don't know why this error started to happen recently...
**EDIT2**: The error still happens with frimware 8.10.2 (most recent release).

**Comment by lo48576** [comment]
I plugged the keyboard to another Gentoo Linux machine (laptop), and then the error does not seem to happen, even with `CONFIG_HIGH_RES_TIMERS=y` and `CONFIG_NO_HZ_IDLE=y` and `xhci_hcd`...
I don't know what to check more.

**Comment by mondalaci** [comment]
What happens if you connect your UHK via a USB 3 port or a powered USB hub?

**Comment by lo48576** [comment]
Powered USB 2 hub (which is connected to USB 2 port of M/B): problem still happens.
USB 3 port: The problem doesn't seem to happen.

Unplugging from USB 3 port, this warning is reported by `dmesg`, but I don't know this is related.

> [74359.445614] xhci_hcd 0000:02:00.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.

![screenshot-2020-11-03-153321+0900](https://user-images.githubusercontent.com/1246590/97955717-30032f80-1dea-11eb-9538-411fa48429ae.png)

**Comment by mondalaci** [comment]
Are you using a Ryzen PC?

**Comment by lo48576** [comment]
Yes, using Ryzen 7 3800X.

**Comment by mondalaci** [comment]
@xxxajk Shouldn't #301 fix USB 2 issues like this, too? Is there any way to fix this?

**Comment by Jopie01** [comment]
Just to let you all know, I came across this: https://www.reddit.com/r/Amd/comments/lnmet0/an_update_on_usb_connectivity_with_500_series/. So it seems this issue is a problem from AMD and not UHK or Linux.

**Comment by xxxajk** [comment]
Update your bios, which should have the microcode fixes. Solved a lot of the problems for the USB and other bugs.

**Comment by lo48576** [comment]
I know this is hardware (CPU or M/B side) problem.
I googled about that AFTER the left half of the UHK was broken, and I noticed this sometimes (infrequently) happens on other USB devices.

However, the disconnection of UHK became quite frequent (a few times in a minute!) at some point, so I think this could possibly be mitigated by the Linux kernel or UHK firmware side.
(I'm sorry I don't know when and why the disconnection became frequent on my machine.)

I alreday tried UEFI updates, but they haven't solved the problem.
I'll keep trying newer UEFI firmwares from now on...

Thank you for your information!

**Comment by xxxajk** [comment]
One other thing to consider is a newer kernel version. Currently I'm running 
Linux devil 5.10.12-051012-generic #202101301330 SMP Sat Jan 30 14:07:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
which fixes a ton of stuff too. My UPS would drop USB constantly, now it is much better with new BIOS and kernel.

**Comment by mondalaci** [comment]
A lot of improvements have been made to the USB handling of the firmware recently, so chances are this issue has been fixed, assuming that it was a firmware issue and not a BIOS-related one.

I'm closing this issue but if anyone thinks that it still persists, feel free to comment and I'll reopen it if needed.
