### ISSUE TITLE
Expose layer toggling via USB

### ISSUE THREAD

**Issue by hamoid** [UltimateHackingKeyboard/firmware#324]
Hi! I was wondering if it would be possible to use a MIDI foot-controller to activate and deactivate layers in the UHK.

I can write the C++ application that listens to MIDI myself, but I don't know if one can send commands to the UHK in real time and do so fast enough.

Might this be possible?

**Comment by mondalaci** [comment]
Only keymaps can be set via the USB protocol at this point, but we'll extend the protocol, so it'll be possible to activate layers, too.
