### ISSUE TITLE
Accidental layer toggling

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#327]
If I double tap a layer switcher key, which has the "lock layer when double tapping this key" option enabled, and I hold it for a while, then release it, it doesn't get toggled, which is correct behavior.

However, If I double tap such a layer switcher key, hold it for a while, but at the same time press some other keys, and then release it, it gets toggled, which is not desired, and from time to time, I toggle layers accidentally this way.

**Comment by kareltucek** [comment]
This applies to simple layer "toggle" too. 

Is the behaviour considered correct for toggle, or should it be changed too?

**Comment by mondalaci** [comment]
I'd expect single-tap toggle actions to toggle layers under all circumstances.
