### ISSUE TITLE
Tab backlight

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#332]
This does not look entirelly right...
![Tab](https://user-images.githubusercontent.com/3447497/109999832-ee8c7d80-7d12-11eb-91b0-ea56b01ed5b1.jpg)

**Comment by mondalaci** [comment]
I knew about this bug, and I've just partially fixed it with b1f858c28692f41a7ada7d5dc969be3530129107, but for some reason, the Tab and Backspace LEDs are still affected on the Mouse and Fn layers.

**Comment by kareltucek** [comment]
I think I see the problem, will confirm later and hopefully also post a PR.

Edit: allright, have no idea atm but intend to do some more experiments and testing before giving up "officially".

**Comment by steamraven** [comment]
LedMap: line 79

        { .red=0, .green=16, .blue=29 }, // Tab

I think this should be

        { .red=0, .green=16, .blue=32 }, // Tab

since 29 is also used with G green.

Also, 

       { .red=152, .green=168, .blue=0 }, // Backspace

Based on the pattern it looks like it should be 

        { .red=152, .green=168, .blue=40 }, // Backspace

**Comment by kareltucek** [comment]
Indeed! Works with both custom backlight as well as with the functional backlight, and does not mess up led display text!

Will you create a PR so that the contribution rightly remains logged as yours? :-)

**Comment by steamraven** [comment]
Can we confirm if backspace is also incorrect?

**Comment by kareltucek** [comment]
Yes, and your proposed fix works as well.

**Comment by kareltucek** [comment]
> but for some reason, the Tab and Backspace LEDs are still affected on the Mouse and Fn layers.

Just for record - if layer array goes out of range (in `LedDisplay_SetLayer`), then the written address is (probably) 0 (since index is taken from uninitialized memory) - i.e., that Tab's red gets written by a value originally intended for layer led indicators.

**Comment by mondalaci** [comment]
@kareltucek Can you look into this? Feel free to open another issue and a PR.

**Comment by kareltucek** [comment]
This is not a problem at the moment I believe - I meant it just as a memento in case we run into it in the future.

It is relevant to the 12-layer PR, where it is already solved - https://github.com/kareltucek/firmware/pull/66/commits/173833506319933450487239d7e88976785fb371.
