### ISSUE TITLE
Navigation mode bugs

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#354]
@kareltucek

- When scrolling with the mini trackball of the key cluster, it scrolls quite a large distance at a time. It feels like it emits double or triple scroll actions on every pulse.
- Vertical direction is reversed for the touchpad and for the mini trackball of the key cluster in caret mode.

**Comment by mondalaci** [comment]
@kareltucek I plan to release a new firmware version as soon as this gets fixed. Please let me know if you're interested in fixing it. I guess I can fix the reverse direction bugs very easily, and the mini trackball issue might be harder.

**Comment by kareltucek** [comment]
Will look into it.
