### ISSUE TITLE
Feature request: Configurable axis directions

### ISSUE THREAD

**Issue by steamraven** [UltimateHackingKeyboard/firmware#360]
For scrolling with the trackball on the left module, it is much easier moving side to side than up and down.  And I usually scroll more up-down then side-side.  It would be nice to rotate the axis, so a Side-side movement translated to a up-down scroll.

**Comment by mondalaci** [comment]
This would definitely be useful, and I've been thinking about the same feature. Let's expose this feature as the `module.keycluster.invertAxis` [smart macro](https://github.com/UltimateHackingKeyboard/firmware/issues/351) variable.

**Comment by barnc** [comment]
Came to create this exact issue and was happy to find it already here - A big plus 1 on this for me.

**Comment by mondalaci** [comment]
This is already implemented via the swapAxes smart macro variable and will be included in the next release.
