### ISSUE TITLE
Key cluster has wrong colors when attached

### ISSUE THREAD

**Issue by Nicd** [UltimateHackingKeyboard/firmware#366]
1. Set up keymap for key cluster so that it has different colors
2. Detach your key cluster module
3. Reattach your key cluster module
4. Observe that key cluster has default (?) colors, not the same colors before detach
5. Switch layer, observe that colors are correct now

**Comment by mondalaci** [comment]
Fixed by 5d4645179bca5edb5e1c605c37293d541abfa46a
