### ISSUE TITLE
Trackpoint module momentarily unresponsive when used in strokes

### ISSUE THREAD

**Issue by ghost** [UltimateHackingKeyboard/firmware#385]
When using the trackpoint module in a stroke-like fashion (rather than maintaining constant contact with the point, contact is reapplied with direction) resulting in some strokes not producing movement ( usually not the first stroke )

**Comment by mondalaci** [comment]
Does the trackpoint module momentarily disappear in Agent when this issue happens?

**Comment by ghost** [comment]
nope it stays connected

**Comment by mondalaci** [comment]
Can you reproduce a similar issue when only using the mouse keys of the mouse layer, and the trackpoint is connected but not used?

**Comment by ghost** [comment]
mouse layer doesn't seem to be doing this either. this only happens when the pressure to the trackpoint is applied in strokes and it seems inconsistent when it happens

**Comment by mondalaci** [comment]
Can you make a screencast that shows this issue?

**Comment by ghost** [comment]
https://drive.google.com/file/d/1PeOBUR9TqI9eKQzkHAgXtGAO9gfeccPA/view?usp=drivesdk

**Comment by ghost** [comment]
each stroke is happening at the same interval, but you should see pauses in the cursor intermittently. That's when the cursor is unresponsive to the movement when placing the finger back on the nub

**Comment by mondalaci** [comment]
Thanks for sharing. I can notice the issue. Please give a shot to [this guide](https://ultimatehackingkeyboard.com/repair/fastening-module-steel-guide-screws), and let me know whether it fixes the issue.

**Comment by ghost** [comment]
just tried it. didn't seem to change anything. Module also doesn't feel loose

**Comment by mondalaci** [comment]
Then we shall replace your module. Please shoot an email to support@ultimatehackingkeyboard.com and we'll arrange it.

Thank you for your patience and understanding!
