### ISSUE TITLE
Touchpad two-finger scrolling and zooming

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#387]

**Comment by linduxed** [comment]
Would this issue overlap with the possibility of treating a two finger tap as right-click, or should this be considered to be a separate issue?

EDIT: Found a comment from @mondalaci related to my question: https://github.com/UltimateHackingKeyboard/agent/issues/1586#issuecomment-916408625

**Comment by kareltucek** [comment]
Both are covered in the above PR.

**Comment by mondalaci** [comment]
Implemented by master, will be included in the next release.
