### ISSUE TITLE
Keycluster module keys occasionally stop working

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#389]
Strange behaviour, not sure how to best test / report this. It has happened twice in the past week, so I am beginning to think it's not just a one-off fluke.

Right keyboard half firmware: 8.10.10
Left keyboard half firmware: 8.10.10
Key cluster firmware: 8.10.10
Touchpad is detected, and its firmware is implemented by the right keyboard half.

Agent version: 1.5.15

UHK60 v1 with touchpad and keycluster modules. When I used my UHK this morning, I noticed the keys on the keycluster are not working. They don't do anything. The scroll wheel (ball) still works. The keys on the regular keyboard halves work fine. All layers work. But they keycluster keys don't do anything. No mouse clicks, no key presses.

If I unplug the keycluster and plug it back in, no change.
If I unplug the complete left half and plug it back in, no change.
If I unplug the touchpad and plug it back in, no change.

The first time this happened, I unplugged the complete UHK from the USB port and re-connected it, then the key cluster worked again.
The second time this incident happened, I opened Agent, and re-saved the keyboard configuration into the keyboard, now the key cluster works again.

Any suggestions what else I should try / do if it happens again?

**Comment by mondalaci** [comment]
Please give [this guide](https://ultimatehackingkeyboard.com/repair/fastening-module-steel-guide-screws) a shot, and let me know whether it works.

**Comment by mhantsch** [comment]
> Please give [this guide](https://ultimatehackingkeyboard.com/repair/fastening-module-steel-guide-screws) a shot

I am happy to try this, but I am confused.

Why should those screws change anything? The issue was not solved by unplugging/replugging the key cluster, so it cannot be a contact problem. Re-saving the configuration from Agent solved it; so that sounds more like a software issue?

Also, why would the scroll ball still work, and only the keys fail to do anything?

**Comment by mondalaci** [comment]
The connection of your modules may be unreliable due to a loose mechanical connection which may mess up the I2C stack that can result in all kinds of issues. That's my theory for the time being, and I'll dig deeper if the issue persists.

**Comment by mhantsch** [comment]
OK, understood. I'll reseat the connection and observe whether the issue reoccurs.

**Comment by mondalaci** [comment]
Closing this issue due to the lack of replies. Feel free to follow up, and I'll reopen it if needed.

**Comment by mhantsch** [comment]
OK, I had that reappear, and I have figured out the sequence that triggers the behaviour:

- Unplug the UHK from USB.
- Unplug all modules from the UHK.
- Plug the UHK into USB. Check that it's working.
- Plug the key cluster module into the left half.
- Check that the scroll ball is working.
- Now check the mouse buttons of the key cluster module. For me, they are not working.
- Unplugging and replugging the keycluster module does not help.
- To get the keys working again, you have to either save a new configuration to the UHK from Agent, or you have to unplug-replug the UHK from USB (basically, reboot the UHK through power cycling).

I think this issue needs to be reopened, but it's now clear that it doesn't accidentially / sporadically stop working, but it's a specific sequence of events that triggers this behaviour.

**Comment by mhantsch** [comment]
Oh BTW, I ran into this because I have two UHKs (one at work, one at home), and only 1 set of modules. So I keep carrying the modules between the two locations. I often start my Laptop with the UHK attached (but without any modules), and then later realise I forgot to plug in the modules. I then pull them out of my bag and attach them, only to notice subsequently that the key cluster keys aren't working (mouse buttons, mostly).

**Comment by mhantsch** [comment]
Perhaps #348 would solve this?

**Comment by kareltucek** [comment]
Sounds like it. One way to test: when this happens, try to change keymap forth and back...

**Comment by mhantsch** [comment]
> Sounds like it. One way to test: when this happens, try to change keymap forth and back...

@kareltucek You mean directly on the UHK, correct? (without Agent)

**Comment by kareltucek** [comment]
Yes.

**Comment by mhantsch** [comment]
Will try!

**Comment by mhantsch** [comment]
@kareltucek I just tested it, and you are correct. Switching keymaps back and forth makes the keycluster keys work again.

@mondalaci I guess it is up to you if you want to reopen this issue or add a note on #348 to test this exact scenario.

**Comment by mondalaci** [comment]
@mhantsch Please subscribe to #348 and reopen this issue if it persists after testing the fix of #348.
