### ISSUE TITLE
[NOT AN ISSUE] Just want to mention some explanation videos about USB

### ISSUE THREAD

**Issue by Jopie01** [UltimateHackingKeyboard/firmware#394]
A year ago I came across the fantastic Youtube channel of Ben Eater who builds 8-bit computers on a breadboard and explains what he is doing. Some time ago he also made some videos about the USB interface, how it works etc. It will give everybody some insight in the USB protocol, how it works and that it in the end is a complex protocol.

https://www.youtube.com/watch?v=wdgULBpRoXk
https://www.youtube.com/watch?v=N0O5Uwc3C0o
https://www.youtube.com/watch?v=2lPzTU-3ONI

Have fun watching!

Maybe nice to have the videos in the Readme ......

**Comment by mondalaci** [comment]
Thanks for the videos!

I won't include them in the readme because they're not directly related to the UHK, but they're worth watching for anyone interesting in the USB.
