### ISSUE TITLE
Touchpad drag and drop

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#398]
Most touchpads support drag and drop via double-tapping and holding their surface. I'll try to implement the same for the touchpad module, but according to my memory, the touchpad controller IC doesn't drag and drop the standard way, and its drag and drop implementation is rather clumsy. Also, it's questionable how useful drag and drop would be for the touchpad module since its surface area is rather small.

**Comment by linduxed** [comment]
> Also, it's questionable how useful drag and drop would be for the touchpad module since its surface area is rather small.

While I agree that long distance dragging will likely be rather difficult with the touchpad, I would argue that there's one reason for supporting it: highlighting a couple of words in text.

I can only speak for myself, but with most other touchpads supporting the double-tap-then-hold feature, *muscle memory* gets disrupted when one can't double-tap then hold to highlight a region of text.

I don't mean to influence your project priorities with this comment, just wanted to give a reason for why I think it would be worth implementing.

**Comment by nilehmann** [comment]
I'm trying the touchpad module now for the first time, and I'm really missing double-tap-then-hold feature for the exact same reason @linduxed mentioned: highlighting text.

**Comment by matthewgrossman** [comment]
I've also seen in some amount of mice a "hold setting" thats lets you 
- hold mod+shift, or some keyboard combo
- moving the mouse will begin dragging whatever is under the cursor 
- you stay in "dragging mode" until you release the keyboard combo

This fixes the problem around the mousepad being too small, as you can re-center your thumb and continue dragging elsewhere

**Comment by mondalaci** [comment]
@matthewgrossman It's already possible to hold Mouse+F according to the default keymap to achieve similar behavior.

**Comment by matthewgrossman** [comment]
ah excellent, thanks! This is preferable to me than the double-tap fwiw, sorry for the noise

**Comment by mondalaci** [comment]
Done in master and will be included in the next firmware release.
