### ISSUE TITLE
Wrong detection of ISO vs ANSI

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#406]
@kareltucek Just committed aebe2080b135c38a198adb00fbf579dd7fa91be9, but always ISO gets detected, even after running `agent/packages/usb/write-hardware-config.ts uhk60v2 ansi` and power-cycling the UHK. Any ideas what's wrong?

**Comment by kareltucek** [comment]
If you are after a quick answer, then no.
