### ISSUE TITLE
Audible noise

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#412]
The LED drivers of the UHK 60 v2 emit audible noise. We tried to minimize this noise in the design phase, but a customer asked about reducing it, so it can still be distracting to some.

The noise is largely proportional to the brightness of the LEDs, so reducing LED brightness in Agent should reduce the noise, too.

The LED driver has a PWM Frequency Setting option which may help reduce the noise. I've made the following builds to be tested:

[uhk-firmware-8.10.11-1.05khz.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/7351859/uhk-firmware-8.10.11-1.05khz.tar.gz)
[uhk-firmware-8.10.11-2.1khz.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/7351860/uhk-firmware-8.10.11-2.1khz.tar.gz)
[uhk-firmware-8.10.11-4.2khz.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/7351861/uhk-firmware-8.10.11-4.2khz.tar.gz)
[uhk-firmware-8.10.11-8.4khz.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/7351862/uhk-firmware-8.10.11-8.4khz.tar.gz)
[uhk-firmware-8.10.11-26.7khz.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/7351863/uhk-firmware-8.10.11-26.7khz.tar.gz)

**Comment by mondalaci** [comment]
Closing issue due to the lack of feedback. 7a8c6bfe1cf729354e8d11a325d0a7a11388fddd should have minimized audible noise and it's included in firmware 8.10.12

**Comment by maxheld83** [comment]
I just tried all of the above variants, as well as 8.10.12, and 8.10.11 (without above fixes), and I can't hear much of a difference.
The pitch seems to change with the above versions, but maybe that's me *expecting* a change in pitch.

For context (should anyone else read this):
The noise is quite minor and it took me a couple of weeks of using to even notice it.
It goes away completely by turning off the led backlighting in agent.

**Comment by mondalaci** [comment]
I talked to Lumissil (formerly ISSI), the manufacturer of the LED driver ICs that are responsible for the audible noise. They told me that the frequency setting has a limited effect on audible noise.

We tried hard to minimize audible noise when designing the UHK, and we did our best. Nobody has complained about it so far, but I know it can be slightly disturbing in very silent environments and when the brightness is high. I'll be researching alternative LED drivers to be used in future UHK versions to minimize, preferably eliminate audible noise.

**Comment by lexa** [comment]
Is it possible to somehow reduce the noise mechanically? for example by dropping a drop of silicone/glue on the LED driver?

**Comment by mondalaci** [comment]
I wish it were possible, but it's not. The noise is generated by the capacitors and conducted by the PCB. I don't know of any way to reduce the noise. If anyone finds a way, please share!

**Comment by mhantsch** [comment]
> The noise is generated by the capacitors

Would different capacitors (manufacturers) make a difference?

**Comment by mondalaci** [comment]
Practically, no. Low-noise capacitors are incredibly expensive and considerably larger, and as a result, they usually don't have enough space. The solution is to use LED drivers that operate outside of the audible range of humans. There are some candidates that we intend to use in future products.
