### ISSUE TITLE
Nonstandard buttons for stenotype; opinion?

### ISSUE THREAD

**Issue by bgeron** [UltimateHackingKeyboard/firmware#413]
Hi Laszlo! 

I'm considering spending some time to make UHK nicer for typing in stenotype. But before I do that, I was wondering what you think of the idea, and if you'd be inclined to merge the PRs. 

## Motivation

Stenotype is a way to type faster (up to 240 wpm) and more ergonomically. People do this on (essentially) a modified 23-key NKRO keyboard where every finger is essentially assigned 2 keys, and pressing a combinations of those keys at the same time forms a syllable, word, or even a small group of words. 

A pretty decent way to achieve this is UHK with special keycaps and software called [Plover](https://www.openstenoproject.org/plover/). Plover captures keystrokes from the OS, reinterprets them, and sends words on to an application.

Here is an example of Plover in action: https://youtu.be/UtQzTUEuPWo?t=15

I have two shortcomings with this method. Primarily, the method of capturing keystrokes isn't so robust - on Linux, it depends a bit on the application. In Firefox, I can't type in steno because Firefox captures keyboard directly too, it seems. Second, I feel sometimes Plover is sometimes missing some keystrokes because it only sends up to 6 to the USB host. But I'm not 100% sure of this.

## Proposal

So I was thinking of adding ~30 nonstandard key codes to firmware + agent, which would be sent as vendor-defined USB HID keys, such as HID Button Page (0x09). It's so few that we could send them as a fixed width bit vector, so that keys would never be missed. Because the keys are nonstandard HID buttons, Plover could presumably capture them more reliably, without the OS layer in between. On Linux for instance, I imagine Plover could use the builtin USB HID driver.

What do you think about this sort of thing? Does it sound like the kind of thing you'd be happy to merge?

If clutter in Agent is a concern, I was thinking we could hide those new keys from Agent unless some checkbox was ticked to enable these new keys from the hey drop down.

Looking forward to hearing your thoughts.

Cheers, Bram

P.S. QMK comes with builtin support for stenotype, but it uses serial over USB — yech! :)

**Comment by kareltucek** [comment]
So... basically you are asking for arbitrary scancode feature and N-key rollover feature?

Both are already implemented (https://github.com/UltimateHackingKeyboard/agent/issues/857, https://github.com/UltimateHackingKeyboard/firmware/pull/367) (n-key rollover needs a slight refactor) and wait jut to be merged and released.

(Do those two PR's fit your needs, or is there something special you need on top?)

**Comment by mondalaci** [comment]
Hi Bram!

Thanks for elaborating on the details. I'm vaguely familiar with stenotype and Plover, so this was a useful refresh.

I'm sorry to say that this application is too niche, and I don't plan to merge such a PR, but it may not need any custom code.

Karel correctly referenced the two relevant issues. NKRO is implemented in a PR, and it's possible to specify arbitrary scancodes via Agent when compiling it from source. The next Agent release will contain the latter feature. These two features may implement everything you need.

I'm closing this issue, but feel free to follow up.

**Comment by bgeron** [comment]
Wow, it seems the combination of those would pretty much solve my use case! In particular the arbitrary scancodes. Currently, Agent can only set about 12 scancodes that don't have existing meanings (F13-F24), which is not enough, but I'll try to use _Reserved_ scancode ranges if firmware+agent will support that. The Reserved ranges are probably not supposed to be used at all (until USB Implementers' Forum defines them) but this could also be the first step to standardization ;)

Great forward planning, thanks!
