### ISSUE TITLE
`com.apple.AppleUserHIDDrivers` using ~10% CPU on macOS Monterey

### ISSUE THREAD

**Issue by noefroidevaux** [UltimateHackingKeyboard/firmware#414]
Since the upgrade to macOS Monterey, I have an Apple process `com.apple.AppleUserHIDDrivers` which takes in permanence ~10% of the CPU when the UHK keyboard is plugged.

Under macOS Big Sur, I didn't have this behaviour.

Tested on the following 2 Macs with the same behaviour:

* MacBook Pro (Intel) i9
* Mac mini M1

**Comment by mondalaci** [comment]
Please let us know which firmware versions are affected, and try some of the latest firmware versions.

**Comment by noefroidevaux** [comment]
I was using:

```
Right keyboard half firmware: 8.10.10
Left keyboard half firmware: 8.10.10
Key cluster firmware: 8.10.10
Trackball firmware: 8.10.10
```

I have tried the latest firmware found on https://github.com/UltimateHackingKeyboard/firmware/releases , but the problem is always here:

```
 Right keyboard half firmware: 8.10.11
 Left keyboard half firmware: 8.10.11
 Key cluster firmware: 8.10.11
 Trackball firmware: 8.10.11
```

Tell me if I can test another firmware.

**Comment by mondalaci** [comment]
@ert78gb Can you reproduce the issue?

**Comment by ert78gb** [comment]
I haven't installed Monterey yet. I will do it on the weekend.

I tested v1 and v2 keyboard with Big Sur and my experience the same with 8.10.10 and 8.10.11 firmware BUT I don't experience relevant CPU usage with 8.10.9 firmware version.

**Comment by mondalaci** [comment]
@noefroidevaux Does firmware 8.10.9 exhibit the issue?

**Comment by noefroidevaux** [comment]
@mondalaci I have tried the new `8.10.12`... but it's the same. BUT with the version `8.10.9`, it works well 🎉 So it seems something was introduced between `8.10.9` and `8.10.10`. I'll stay on the `8.10.9` version 😊
Thank you @ert78gb for the workaround!

**Comment by mondalaci** [comment]
@noefroidevaux So glad to hear! :) Please test [these commits](https://github.com/UltimateHackingKeyboard/firmware/issues/390#issuecomment-891739822) and let me know which one introduces the issue. It'd greatly help us narrow down the cause and fix the bug for future firmware releases.

**Comment by noefroidevaux** [comment]
@mondalaci It starts with **uhk-firmware-8.10.9-08-6fc356e.tar.gz** (uhk-firmware-8.10.9-07-191e915.tar.gz was fine).

**Comment by mondalaci** [comment]
@noefroidevaux Given the identical commit, the root cause of this issue must be the same as for #390. Closing this duplicate issue, and please subscribe to the #390.

**Comment by noefroidevaux** [comment]
@mondalaci Yes, maybe. I'm subscribed to #390 :)
