### ISSUE TITLE
Per-keymap mouse speed and LED brightness

### ISSUE THREAD

**Issue by marshallflax** [UltimateHackingKeyboard/firmware#415]
I'd like to propose that Mouse Speed and LED brightness be configured for each keymap rather than globally.

A typical use-case would for switching between ChromeOS and MacOS, since they work best with different mouse speeds.  (And I *already* switch between keymaps when I switch computers.). 

This would also allow users to control their LED brightness without introducing any new concepts.

**Comment by mondalaci** [comment]
Closing this issue as a duplicate of #300.

What's the rationale of the per-keymap LED brightness setting?
