### ISSUE TITLE
Minor Enhancement Idea: TrackPoint could make it easier to use other keys for Click

### ISSUE THREAD

**Issue by vorburger** [UltimateHackingKeyboard/firmware#417]
(Caveat: I've got my UHK v2 *yesterday* and am at the very beginning of exploring this **ultimate gadget** - Thank You for having created this!)

I have the TrackPoint module, and as a new user am initially trying to recreate an experience similar to how I've used my Think Pad keyboard (on Lenovo ThinkPad laptops, or with [ThinkPad USB keyboard](https://www.google.com/search?q=thinkpad+usb+keyboard) on a desktop), hoping to gradually ease into a more "UHK native" experience.

With a ThinkPad TrackPoint, I got used to moving and then leave my right thumb on the TrackPoint, and then left click with my left thumb. To re-create this experience with the UHK, instead of using the (for me too) clickly little button under the TrackPoint, I've mapped what in the default QUERTY for PC keymap is the lower left Mod key on the right half of the UHK to Click Left. (I hope this explanation makes sense, let me know if a screenshot or video is needed to clarify.)

This works pretty great (for me, YMMV; that's the beauty of the UHK), except for 1 minor point I wanted to provide you feedback on here:  When clicking on something which can be dragged, such as the keys in the Agent (or anything else that's draggable), then it often drags instead of clicking. This is because I'm clicking quickly, and the pointer is probably just "finishing to move", if you know what I mean. With the ThinkPad TrackPoint I never had this problem; I'm not sure if it's somehow "smartly compensating" and "stops sending mouse movements" (?) as soon as you click, or... if this is only just because my ThinkPad USB keyboard's TrackPoint is just moving much slower than the UHK's? But I'm seeing this "dragging" problem even at Linux GNOME Mouse & Touchpad's slowest Mouse Speed setting (which feels just about right, to me; everything else is too fast, for me); I could try if this persists if I could make it a slower, see #416.

It's not a huge deal, of course, but I thought I'd let you know, in case this gives you some useful ideas. (My workaround is just to have to remember to slightly lift the right thumb from the TrackPoint before clicking with the left thumb.)

**Comment by mondalaci** [comment]
@vorburger Thanks for your feedback! Let's wait until #351 gets implemented, which has the potential to solve this issue. I'll reopen this issue later if needed.
