### ISSUE TITLE
fade leds after some time of inactivity

### ISSUE THREAD

**Issue by jalberto** [UltimateHackingKeyboard/firmware#426]
I would like to see a way to configure a save-energy mode where the leds fade out after some minutes of inactivity.

**Comment by Drizzt321** [comment]
Ohh, I'll second this request. When I go to bed, it's nice if the backlights were to go off, eventually, after a short timeout to have less light floating through my apartment.

**Comment by mhantsch** [comment]
Fade to complete darkness, or fade to a very low light level?

**Comment by mondalaci** [comment]
I think "fade to complete darkness" is what the vast majority wants, so I wouldn't introduce further options now.

**Comment by kareltucek** [comment]
So this is about both the backlight and segment display, right?

**Comment by mondalaci** [comment]
Right.

**Comment by Drizzt321** [comment]
> I think "fade to complete darkness" is what the vast majority wants, so I wouldn't introduce further options now.

I'd like fade to complete darkness. If it's just as easy to put in an option for fade to a specified point that'd be neat, but as @mondalaci said, complete darkness is what I'd like/prefer.

**Comment by mhantsch** [comment]
> So this is about both the backlight and segment display, right?

Ah yes, so this would work on UHKv1 too, and fade the LED segments (and icon indicators). I like!

**Comment by mondalaci** [comment]
Closing this issue as a duplicate of #437.
