### ISSUE TITLE
MD5 checksum-based firmware updates

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#440]
For new firmware versions, Agent updates the firmware images of both halves and all modules, even though usually only the firmware image of the right half changes, which is problematic for two reasons:

1. The update process is unnecessarily long, especially due to BusPal, the USB to I2C proxy, which requires re-enumeration over USB.
2. Rarely, some customers brick their module or left keyboard half, which gets returned to us for hardware-flashing. Theoretically, the bootloader should always recover when flashing is incomplete, but practically, for some unknown reason, sometimes it doesn't.

We'll add MD5 checksums to every firmware image, including both halves and all modules. Agent will only flash firmware images whose MD5 checksums differ unless explicitly asked to flash them.

The checksums of all modules will be included in the master (right half) firmware, too, for Agent to display the current master firmware image to them whenever possible. See the [Agent-side specification of this feature](https://github.com/UltimateHackingKeyboard/agent/issues/1663) for details.

Given that the checksums are contained in the firmware images, they affect the checksums of the firmware images, so `make-release.js` will implement a two-step build process. In the first step, the 128-bit MD5 checksums will contain all zeros. In the second step, the MD5 checksums of firmware images of the first step will be used as the MD5 values contained in the final firmware images to be released.

We'll have to extend the device and module protocols to transfer the checksums and expose them to Agent.

**Comment by Drizzt321** [comment]
As an aside, for hardware flashing, is this over serial with the pins exposed on the board if we were to take apart the cases? Probably a number of us have FTDI USB->Serial available and can use them, so maybe posting instructions somewhere would be useful to a (probably very small) sub-set of users who do accidentally end up bricking one or both halves.

**Comment by mondalaci** [comment]
@Drizzt321 One needs a compatible SWD adapter, not an FTDI USB adapter. Related instructions are at https://github.com/UltimateHackingKeyboard/bootloader

This issue is not related to hardware flashing.

**Comment by AkechiShiro** [comment]
Thanks a lot @mondalaci !
Sorry for polluting this issue, but I would like to know, when this will be released in a new release ?

Also, is there any lacquer for the wood palm that is recommended to be very durable, mine is alll gone, now I'm sad, but don't want to go for a cheap spray for cars, lacque, what would be the most durable/best without taking into account the price ?

**Comment by mondalaci** [comment]
@AkechiShiro You're welcome! This feature will be included in the next firmware release and will be supported by the next Agent version.

My colleagues may be able to recommend a lacquer type. Please contact them at https://ultimatehackingkeyboard.com/contact-us
