### ISSUE TITLE
Allow simultaneous key presses at the same time (Chords)

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/firmware#441]
## Support chords / advanced auto correction

Chords are a revolutionary way to type, where instead of tying by letter (one at a time), the user can type by word (pressing all letters of word at same time). 

1. Is it feasible to add this functionality to the UHK? 
2. Would this have to be done in firmware? Or could it be done in software? 

Here is [an example](https://www.kickstarter.com/projects/adan-arriaga/charachorder-lite-type-at-the-speed-of-thought) of a keyboard that has implemented chords

**Comment by mondalaci** [comment]
I have doubts about the usability of this input method. :) Maybe it works for a small niche, but we don't want to pursue it.

In any case, this should be implemented on the OS level, possibly with special drivers.
