### ISSUE TITLE
Trackpoint to respect Mouse Layer commands

### ISSUE THREAD

**Issue by iukej** [UltimateHackingKeyboard/firmware#458]
Hi, thank you for a great product! Love using the keyboard.

With a multi-monitor setup, it doesn’t seem possible to find a single mouse speed that will work for all points. It’s so awesome that there are decelerate/accelerate keys in the mouse layer. However when using these keys, they don’t seem to alter the trackpoint behavior. Might there be some way to do this?

**Comment by kareltucek** [comment]
I intended to allow that for quite some time now... 

Here is simple version that halves/doubles the speed: [uhk-firmware-9.0.0.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/8246392/uhk-firmware-9.0.0.tar.gz).

**Comment by iukej** [comment]
Would this change show up by pressing 'Check for update' in UHK Agent/Agent/Settings? Or is that for larger releases?

Was worried about downloading the linked firmware https://github.com/UltimateHackingKeyboard/firmware/issues/458#issuecomment-1066979597 in the case it overwrote existing settings.

**Comment by kareltucek** [comment]
No. The posted firmware is just a quick local build for your convenience and testing. It is not available within the official line of releases. The "check for update" checks for new version of *Agent*, not firmware, anyways. 

You can flash it without worries - it will not overwrite the User Configuration, and you will be able to flash older firmware again. (Of course, be sure to make a backup of your user config just in case...)

**Comment by kareltucek** [comment]
(Also, the posted firmware is de-facto a pre-release since origin/master already contains bumped versions. Once official 9.0.0 is released, be sure to upgrade to that.)

**Comment by iukej** [comment]
Much appreciated!

You mentioned this wouldn't show in the official line of releases? I believe @mondalaci has merged it in. firmware/readme shows the following 
<img width="911" alt="image" src="https://user-images.githubusercontent.com/40323012/162598622-a6fbe1d0-8bd7-404b-897b-bdf924cd68c4.png">

That would mean this firmware would be part of the next release, no?

Thank you guys again!

**Comment by mondalaci** [comment]
Karel's halving/doubling speed feature implemented above will be part of the next official firmware release, which I plan to release in a month or two.
