### ISSUE TITLE
PS2 Support

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [UltimateHackingKeyboard/firmware#462]
It seems like there has been some interest in PS2 compatibility as seen from the [knowledge base query](https://ultimatehackingkeyboard.com/knowledgebase?q=ps2).

It seems like it would be possible for the firmware to support a PS2 configuration that is compatible with a [passive usb to ps2 adapter](https://web.archive.org/web/20220330133251/https://www.ebay.com/itm/371606569199?hash=item56857a40ef%3Ag%3AyWcAAOSwxMle8lR0).

**Comment by mondalaci** [comment]
We'll try to simplify the USB interfaces of the UHK, which might improve the situation, but PS/2 is a deprecated protocol, and it's getting increasingly marginalized, so we can't justify spending major resources on it.
