### ISSUE TITLE
Modifier (Alt) key keeps being enabled after using alt+arrow key defined in mod layer

### ISSUE THREAD

**Issue by Rhahi** [UltimateHackingKeyboard/firmware#466]
**Precondition**

1. Have a trackpoint module installed
2. Have mod+S bound to [alt]+[left arrow] for backwards history navigation.
3. Have a web browser up with some navigation history towards the past.

**Steps to reproduce**

1. Press and hold mod layer key
2. Press and release S to navigate backwards -> web browser goes backward
3. (Now, ALT key should be enabled stuck.)
4. Try to navigate up, down, left, right using the trackpoint.

**Expected behaviour**

Because ALT key is not pressed and Mod layer is enabled, trackpoint should scroll in the browser

**Actual behaviour**

Bug: ALT modifier is still pressed, web browser navigates in history instead.

**Comment by mondalaci** [comment]
Alt + Left arrow is a [sticky shortcut](https://github.com/UltimateHackingKeyboard/firmware/blob/182d4e7579e7ea7679c645eac7b0839401e3fba7/right/src/usb_report_updater.c#L125-L146), hence the observed behavior. We'll make it possible to disable sticky shortcuts in the next firmware release, which is already implemented but not yet released.
