### ISSUE TITLE
Feature request - Timed layer change

### ISSUE THREAD

**Issue by leandergangso** [UltimateHackingKeyboard/firmware#471]
# Add extra layer mode

I would love to have even more flexibility to activate/toggle between layers.

My suggestion is a checkbox option for **toggling** as well. (same as img bellow: "Lock layer ...", but for toggling)
This new checkbox could say: "Toggle back if pressed for more than 0.5sec." (0.5sec could be custom)

Toggle scenarios with this checkbox checked:
- Button clicked, toggle between layers. (like normal)
- Button pressed for more than 0.5sec, go back to base layer on release. (new feature)

This could enable me to have the best of both worlds for toggling and holding/activate.

![image](https://user-images.githubusercontent.com/60340480/166125975-17593950-0e28-4c4e-a271-d48b7c3870b3.png)

**Comment by mondalaci** [comment]
This is a very specific feature, which we don't plan to expose via the UI, but [Karel's UHK firmware fork](https://github.com/kareltucek/firmware) may make it possible via macro commands, much of which we'll merge into the stock UHK firmware.
