### ISSUE TITLE
Module cursor movement does not trigger secondary role.

### ISSUE THREAD

**Issue by Felixoid** [UltimateHackingKeyboard/firmware#476]
1. Install the latest Agent:
   https://github.com/UltimateHackingKeyboard/agent/releases/latest
2. Use Agent to update to the latest firmware:
   https://github.com/kareltucek/firmware/releases/tag/v8.10.12.kt.2

I've done everything from the template.

Here's my issue. When I use a key with Esc as primary and MOD as secondary role, modules (trackball, trackpad, and key cluster) behave as I expected in the mod layer, but then after releasing the Esc signal is sent. The problem is that the keyboard behaves halfway, it doesn't switch to a second role completely.

Previously (not sure until when) it didn't work at all, and keys w/ secondary role didn't affect modules' behavior at all. IMHO, it's worse now, because it's inconsistent.

**Comment by kareltucek** [comment]
Can this still be the power issue?

**Comment by Felixoid** [comment]
The mentioned behavior is reproduced on v1 with stock cables after upgrading to kt.2. MOD layer is not switched unless a key is pressed. For "mouse movements" it's not triggering MOD layer, so after key is released the ESC is sent.

BTW, v1 was with release 8.10.12 firmware, there the behavior as described below

> Previously (not sure until when) it didn't work at all, and keys w/ secondary role didn't affect modules' behavior at all. IMHO, it's worse now, because it's inconsistent.

**Comment by kareltucek** [comment]
Oh, I see.

**Comment by mondalaci** [comment]
@Felixoid Can you reproduce the issue without the modules attached?

**Comment by kareltucek** [comment]
@mondalaci inherently no. The problem is the way seconday roles interact with cursor movement (when the movement is initiated by modules).

I know what the problem is, just dealing with it is a bit of a problem.

(Yes, this should probably be solved before the release.)

**Comment by Felixoid** [comment]
I feel the issue is not 100% clear. It's about the behavior of the secondary role as layer MOD *and* modules mouse function.

If I press any _key_, it works and did work as expected.

**Comment by mondalaci** [comment]
Sorry, but I have a hard time understanding the exact issue. Please describe how to reproduce the issue step by step as simply as possible.

**Comment by kareltucek** [comment]
1. press secondary role key.
2. use module to move cursor, but do not tap any key. 
  - expected outcome: it behaves according to the navigation mode given by the secondary role.
  - actual outcome: correct.
3. release secondary role key. 
  - expected outcome: nothing, since the key in 1) was used as secondary role.
  - actual outcome: primary action is issued.

**Comment by mondalaci** [comment]
By "actual outcome: correct", I assume you mean: "actual outcome: works as expected".

This is kind of an edge case. Do you think that the primary role should be triggered when a pointer action has been invoked since the activation of a secondary role action? I think it shouldn't be triggered.

**Comment by kareltucek** [comment]
> By "actual outcome: correct", I assume you mean: "actual outcome: works as expected".

Yes.

> Do you think that the primary role should be triggered when a pointer action has been invoked since the activation of a secondary role action? I think it shouldn't be triggered.

Yes, I think it should not be triggered. 

Furthermore, I guess that modifier secondary roles should apply. E.g., for caret mode, for which they do not apply at the moment. (This part is the real trouble, since it is required that the secondary role takes place before activation of the module-mapped behaviour.)

**Comment by mondalaci** [comment]
Agreed, but the last point is even more of an edge case, so no need to rush.

**Comment by Felixoid** [comment]
Hello, it's solved on the following combination of agent and firmware:

Agent version: 2.0.2  
 Right keyboard half firmware: UltimateHackingKeyboard/firmware:9.1.4  
 Left keyboard half firmware: UltimateHackingKeyboard/firmware:9.1.4  
 Key cluster firmware: UltimateHackingKeyboard/firmware:9.1.4  
 Trackball firmware: UltimateHackingKeyboard/firmware:9.1.4

**Comment by Felixoid** [comment]
Ah, no, I am wrong. The primary action is still triggered
