### ISSUE TITLE
Feature request: show num lock status using background illumination

### ISSUE THREAD

**Issue by surban** [UltimateHackingKeyboard/firmware#489]
For some applications I require the use of the numeric pad keys. I've applied an appropriate mapping to my UHKv2, which includes `Fn+~` being mapped to `Num Lock`.

I would now like the background illumination of the `~` key to show the status of `Num Lock` while `Fn` is being held, for example red for on and blue for off.

Ideally this should also be possible for `Caps Lock` and `Scroll Lock`.

**Comment by mondalaci** [comment]
The status of the caps lock is shown on the LED display. Scroll lock is so rarely used that nobody has requested such a feature yet.

As for num lock, I can't see a clean way of implementing this feature.

@kareltucek Does [your fork](https://github.com/kareltucek/firmware/) support this use case, or do you have a workaround in mind? I'm closing this issue, but we'll follow up.

**Comment by surban** [comment]
As an alternative I would be happy to remap the triangle in the LED display to show Num Lock status, if this is easier to implement.

**Comment by mondalaci** [comment]
@surban This is much more feasible, and I'm fine with having a `set useAdaptiveIconAsNumLock` smart macro setting.

@kareltucek Any objections?

**Comment by kareltucek** [comment]
> @kareltucek Does [your fork](https://github.com/kareltucek/firmware/) support this use case, or do you have a workaround in mind? I'm closing this issue, but we'll follow up.

No and no. (Except for via #322.)

> @kareltucek Any objections?

It sounds far too random. I don't think we should try to support every single feature request just because smart macros make it easier than it was in the pre-smart-macro era.

Why exactly not to support the original suggestion? If the answer is computational overhead, why exactly is that a problem?

Alternatively, it might be possible to introduce building blocks which would allow userspace implementation of such feature. That is, `$onLayerChange` macro event and `ifStateKey { capsLock | numLock | scrollLock }`, `set backlight.key.KEYID.rgb ...` commands.

**Comment by mondalaci** [comment]
@kareltucek Just to make my stance clear, although overloading the adaptive icon with scroll lock seems reasonable, it's clearly a niche request, and I don't feel strongly about it. We should not add additional commands just for the sake of this request.

I should also mention that the display of future UHK versions will be able to display the state of scroll lock.

**Comment by surban** [comment]
I would say this is not very niche, given that [Windows allows direct entry of ASCII characters using the numpad](https://support.microsoft.com/en-us/office/insert-ascii-or-unicode-latin-based-symbols-and-characters-d13f58d3-7bcb-44a7-a4d5-972ee12e50e0). This is quite useful when you need symbols such as ° that are not on the keyboard.

> Inserting ASCII characters
>
>To insert an ASCII character, press and hold down ALT while typing the character code. For example, to insert the degree (º) symbol, press and hold down ALT while typing 0176 on the numeric keypad.
>
>You must use the numeric keypad to type the numbers, and not the keyboard. Make sure that the NUM LOCK key is on if your keyboard requires it to type numbers on the numeric keypad.
>

**Comment by mondalaci** [comment]
Fair enough. I plan to add a dedicated icon for num lock on the display of upcoming UHKs. But I don't plan to repurpose the icons of existing UHKs.
