### ISSUE TITLE
RFE: Allow disabling scrolling with trackpoint module on Mod layer

### ISSUE THREAD

**Issue by ansasaki** [UltimateHackingKeyboard/firmware#494]
I would like to request a way to disable scrolling with the trackpoint on Mod layer.

Sometimes I'm performing actions on Mod layer and I would like to keep the trackpoint as mouse movement control instead of scrolling.

**Comment by kareltucek** [comment]
This is already implemented as part of Smart Macros and will be available in next firmware release. 

(In the meantime, feel free to give a try to https://github.com/kareltucek/firmware - it is the same code which is heading to stock release. Search for "navigation mode". Namely `$set module.trackpoint.navigationMode.mod cursor` in a macro named `$onInit` should do the trick.)

Closing, but feel free to follow up.
