### ISSUE TITLE
Manually installed LEDs on UHKv1 stopped working with recent firmware update

### ISSUE THREAD

**Issue by jceb** [UltimateHackingKeyboard/firmware#495]
Hi, I manually installed LEDs in my UHKv1 switches some years ago and they worked great. I wasn't able to control the brightness so they were on all the time. With the installation of the recent firmwares (sorry, I can't pin-point the exact firmware, currently running v8.10.12) the LEDs were suddenly turned off and I couldn't get them to light up ever since. My impression is that this change of behavior has to do with the introduction of UHKv2 that has built-in back lighting.

**Comment by mondalaci** [comment]
Hi there! Please try to pinpoint the exact firmware version that introduced this issue. If you cannot pinpoint it, please let me know why and I'll do my best to help.

**Comment by jceb** [comment]
I ran a bunch of tests and realized that this issue is related to @kareltucek 's firmware and not to the standard UHK firmware. I'll close this issue.

**Comment by kareltucek** [comment]
Chances are that it affects both. I guess I will have to solder on some leds and bisect the code to figure out what is wrong.

**Comment by kareltucek** [comment]
@jceb should be good in https://github.com/kareltucek/firmware/releases/tag/v8.10.12.kt.4

**Comment by jceb** [comment]
I'll check it tomorrow and let you know.

**Comment by jceb** [comment]
@kareltucek works great thank you very much!
