### ISSUE TITLE
Expose long git sha

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#523]
As it turns out, Agent needs the long SHA to resolve informal documentation resources via GitHub raw URLs, such as https://raw.githubusercontent.com/UltimateHackingKeyboard/firmware/885a92a0d6b730fcb74ac7fd7c256d10ab215750/doc/dist/agent-onInit.png

Please make `tag` only expose the git tag if present, and make the new `sha` field always expose the long SHA. If I'm correct, this change affects the module protocol, the device protocol, and packages.json

This feature is a prerequisite for Agent 2.0.0

**Comment by kareltucek** [comment]
Does it? Short version https://raw.githubusercontent.com/UltimateHackingKeyboard/firmware/885a92a0/doc/dist/agent-onInit.png seems to work fine.

Do we actually want it as a new field as opposed to setting the tag to long sha?

**Comment by ert78gb** [comment]
We web ui resolve the short sha, but the API does not.

https://api.github.com/repos/UltimateHackingKeyboard/firmware/git/commits/885a92a => does not work
https://api.github.com/repos/UltimateHackingKeyboard/firmware/git/commits/885a92a0d6b730fcb74ac7fd7c256d10ab215750 => works

**Comment by kareltucek** [comment]
I see. And it does not universally accept tags either.

So be it new sha field then, indeed.

**Comment by kareltucek** [comment]
@ert78gb, one more try: can you not simply resolve it using https://docs.github.com/en/rest/commits/commits#get-a-commit ?

_(Edit: I mean, use that API to translate ref to sha once, and then proceed as originally intended.)_

It seems to work fine, and if you specify media type, it gives sha only. (Docs explicitly mention it, so it probably is the intended usecase.)

```
$ curl -H "Accept: application/vnd.github.sha" https://api.github.com/repos/UltimateHackingKeyboard/firmware/commits/v9.0.0
3a7d4aeeb042aa48ceb1397c3915b084a924915a
$ curl -H "Accept: application/vnd.github.sha" https://api.github.com/repos/UltimateHackingKeyboard/firmware/commits/885a92a0
885a92a0d6b730fcb74ac7fd7c256d10ab215750
```

**Comment by mondalaci** [comment]
We've tried it. The API is heavily rate-limited, and only allows 50 requests per hour per IP, so we'd use the raw URLs.

**Comment by kareltucek** [comment]
I see.

**Comment by ert78gb** [comment]
I will check Karel's recommendation on the evening. My URL and his url are same . I use the `git/commits` path his url uses only the `commits`

**Comment by kareltucek** [comment]
(I will wait then.)

**Comment by ert78gb** [comment]
@kareltucek thanks for the hint. I found the method in the [octokit](https://github.com/octokit/rest.js) lib too.

**Comment by mondalaci** [comment]
@kareltucek We still need the new `sha` field because tags may be deleted or changed.

**Comment by kareltucek** [comment]
Well, I can build and publish a tar and not push the code into github...

Why would we delete or change tags? Does such risk justify the added complexity and consumed right-half memory?

**Comment by mondalaci** [comment]
Fair enough. Given your findings, a tag is not needed after all.

Thanks for your help!
