### ISSUE TITLE
Upgrading from 8.10.12 to 9.0.1 breaks Layer activation

### ISSUE THREAD

**Issue by gnutix** [UltimateHackingKeyboard/firmware#529]
Hello there,

I have the following setup : 

1. My Base Layer has a "Mod" key (let's call it "a") that activates the "Mod" layer (only when holding the key)
2. My Base Layer has a "Mouse" key (let's call it "b") that toggles the "Mouse" layer
3. My Mouse Layer has the "a" key (see 1.) with the "Accererate mouse" feature

When using firmware version 8.10.12, I can activate the Mouse layer by pressing "b" once, then press "a" to accelerate the mouse (when holding).
With 9.0.1, I can activate the Mouse layer by pressing "b" once, but when I press "a" it triggers the Mod layer.

Any idea why that is ? I've reverted to 8.10.12 in the meantime.

**Comment by kareltucek** [comment]
Oops. Looks like a bug. Thanks for reporting!
