### ISSUE TITLE
Hold mouse button and Release mouse macros do not have correct behavior

### ISSUE THREAD

**Issue by da11an** [UltimateHackingKeyboard/firmware#537]
`Hold mouse button: Left` (see image) and `Release mouse button: Left` macros should allow you to drag and drop by first pressing (and not holding) the hold key then later releasing by pressing the release key. The actual behavior seems to just be a full down/up left click on the hold, making it useless to support drag-and-drop. The desired behavior can be seen when using "mouse keys" in Windows.

![image](https://user-images.githubusercontent.com/49221299/198735209-ea3c8c7e-2323-4c76-a3e8-07206b83d32a.png)

Agent version: 2.0.0
Firmware: 9.1.1

**Comment by mondalaci** [comment]
I can't reproduce the issue. The following macro drag & drops for me as expected:

![image](https://user-images.githubusercontent.com/300402/198818373-27a2e14e-3ad9-41bb-9c53-a67038411367.png)

Please paste your macro here for me to reproduce the issue.

**Comment by da11an** [comment]
Thank you for looking at it László. I was hoping to be able to hold in one macro and release in a second macro. I looked at the documentation last night and found that all keys are released at the end of a macro, so the behavior I'm observing is according to design. I was trying to duplicate the behavior of windows mouse keys `0` and `.` that allow you to sustain a click (`0`) without holding a key down then later release with another key press (`.`). I will close this issue since it was a misunderstanding on my part, but I still hope to figure out the Windows mouse-keys-like desired behavior within a single macro.

![image](https://user-images.githubusercontent.com/49221299/198843967-e2a97e8c-a580-4a0e-8fc7-68f69ab57d06.png)

**Comment by kareltucek** [comment]
Actually, mouse states can be controlled using `startMouse` and `stopMouse` and those *are* persistent.

I am wondering whether we should add a global macro state which would allow persistent key locking... Any thoughts @mondalaci?

**Comment by mondalaci** [comment]
@kareltucek I think this is a very niche use case, and I rather wouldn't introduce a global macro state until we can see that there's a substantial demand. `startMouse` and `stopMouse` should suffice.

**Comment by da11an** [comment]
> Actually, mouse states can be controlled using `startMouse` and `stopMouse` and those _are_ persistent.
> 
> I am wondering whether we should add a global macro state which would allow persistent key locking... Any thoughts @mondalaci?

@kareltucek, I'm not seeing how to use `startMouse` as you're suggesting. I tried the following.
![image](https://user-images.githubusercontent.com/49221299/199880315-96c4961d-b24a-48ca-9125-84a307f11af6.png)
Also tried with just `startMouse mouseBtnLeft`. Both just set the LCD status to `ERR` without actually holding the left button. Am I doing something obviously wrong?

**Comment by kareltucek** [comment]
Oops. Indeed buttons are not part of the syntax at the moment. Will fix that eventually.
