### ISSUE TITLE
System crashed during firmware update

### ISSUE THREAD

**Issue by bistabil** [UltimateHackingKeyboard/firmware#538]
Today I noticed that after the agent was updated to a new major version, I had to update firmware too in order to save a configuration.
During the update, I lost power and now the keyboard is not recognizable anymore.
Is there anything I can do to recover from this?
I am now using my UHK v1 so it's not the end of the world but v2 is broken now.

**Comment by mondalaci** [comment]
Please give a try to https://ultimatehackingkeyboard.com/knowledgebase?q=unbrick and if the issue persists, email us to support@ultimatehackingkeyboard.com
