### ISSUE TITLE
Smart Commands in Macros: different trackball speed in different layers

### ISSUE THREAD

**Issue by SirVer** [UltimateHackingKeyboard/firmware#562]
I really love smart macros and what they let me do in the latest version of Agent. I have the trackball now moving on the main layer, and scrolling on all others. And I really like that, however scrolling is a tad too fast and I do not want acceleration when scrolling.

I did not find a way to disable this. I was expecting this to work:

```
# Speed for trackball
set module.trackball.baseSpeed.fn 0.5
set module.trackball.speed.fn 0.5

# Slower scrolling on fn layer
set module.trackball.navigationMode.fn scroll
set module.trackball.baseSpeed.fn 0.1
set module.trackball.speed.fn 0.1
set module.trackball.xceleration.fn 0
```

But it seems that the layer is ignored for `baseSpeed`, `speed` and `xceleration`. It is taken into account for naviagationMode (as also layed out in the documentation)

**Comment by kareltucek** [comment]
You want `set module.trackball.scrollSpeedDivisor 16.0`. (If still too fast, then increase the divisor until satisfied.)

(Closing, feel free to follow up.)
