### ISSUE TITLE
Backlight macros don't work on UHK 60 v1

### ISSUE THREAD

**Issue by IzK666** [UltimateHackingKeyboard/firmware#569]
Using "set backlight.strategy constantRgb; set backlight.constantRgb.rgb 255 0 0" shows ERR on the lcd screen.
I've an UHK v1 with a cluster module and my intention was to change the cluster lightning depending on the keymap used.

**Comment by kareltucek** [comment]
If you mean literally with a `;`, then that's the problem. Should be:

```
set backlight.strategy constantRgb
set backlight.constantRgb.rgb 255 0 0
```

**Comment by kareltucek** [comment]
But RGB light is not supported with UHKv1 as far as I know.

**Comment by IzK666** [comment]
I tested both ways: with semicolon and without. I don't remember if one of them threw the err code or both.

That's what I suspected, that the cause might be the lack of lights of the v1.
Can you enable them? The cluster module leds can be controlled with the general "key backlight brightness" slider, so it might not be very difficult to enable it and imho can be useful.

**Comment by kareltucek** [comment]
@mondalaci ?

**Comment by mondalaci** [comment]
For me, ERR didn't appear; another command has likely caused it on @IzK666's side. But I can confirm that these commands have no effect on the UHK 60 v1.

Even though the UHK 60 v1 doesn't support RGB backlighting, the key cluster module does, so the above commands should work regardless. 

@kareltucek Would you please fix this issue?

**Comment by kareltucek** [comment]
@mondalaci, what does that mean implementation-wise?

**Comment by mondalaci** [comment]
I haven't looked into the code, but I think we branch with ifdefs for the UHK 60 v1 vs v2. The above macros should work with the v1, too.

**Comment by kareltucek** [comment]
I mean:

1) what is the actual specification for backlight of the right and left half of v1?

2) I suspect there may be some hardware differences between v1 and v2 right and *maybe* left half (?). I am not sure what these differences mean for implementation.

(Answer to 1 is required, any pointers regarding 2 are welcome, but I guess I should be able to figure them myself.)

**Comment by mondalaci** [comment]
1. I'm unsure whether monochrome functional backlighting makes sense for the v1. Not lighting none actions up would probably be useful, but for the time being, I'd just light up every LED.

2. Different LED driver ICs are used for the v1 vs the v2, but we should only care about the relevant LED value arrays on the high level.

**Comment by mhantsch** [comment]
This issue is almost the same as #655 (or at least closely related).

**Comment by kareltucek** [comment]
I don't think that is true. Monochrome handling of UHK v1 and RGB handling of key cluster seem to me as two quite significantly different issues.

**Comment by mhantsch** [comment]
@kareltucek I should have phrased my statement as a question: "Isn't this issue almost the same....?", and you already provided a good answer as to why you want to handle them are two separate issues; thanks.
