### ISSUE TITLE
OR/AND gates for ifKeyActive command

### ISSUE THREAD

**Issue by rftw** [UltimateHackingKeyboard/firmware#570]
This is a feature request.

I wish to pass more than one keyId to the ifKeyActive command and check if one of them is active (OR condition) or all of them are active (AND condition)

Currently as a workaround for OR condition, I use each keyId on a separate line:
```
ifKeyActive 10 final ...
ifKeyActive 11 final ...
...
```
However I couldn't find a way to check if two keys are active at the same time.

**Comment by kareltucek** [comment]
> However I couldn't find a way to check if two keys are active at the same time.

`ifKeyActive 10 ifKeyActive 11 final ...`

**Comment by rftw** [comment]
Thank you! 
I initially attempted to pass multiple keyids `ifKeyActive 10 11 ...` assuming the same syntax as `ifShortcut` command.
