### ISSUE TITLE
Allow any key in ifShortcut

### ISSUE THREAD

**Issue by likern** [UltimateHackingKeyboard/firmware#575]
It would be awesome to support range of keys or `any` keyword in `ifShortcut`.

My command is the following
```
ifShortcut timeoutIn 200 29 exec toMouseLayer
// Here I want not only 16 key, but all keys in layer fn4
ifShortcut noConsume timeoutIn 1000 16 final holdLayer fn4 
autoRepeat tapKey space 
```

This (`ifShortcut noConsume timeoutIn 1000 16 final holdLayer fn4 `) is the only what works the way I like and reliably.
So, when I press `space + <some key>` I get key from layer `fn4`, while just space (hitting fast multiple times) and autorepeat space still works.

**Note:** Looking at source code I've found that `%0` is similar to what I wanted
```
ifShortcut noConsume timeoutIn 1000 %0 final holdLayer fn4
```
it produces desired key (at `fn4` layer), while later giving me error
```
spACeaNDTOmOuSe; 0; 1; nOT enough pending keys1 note tHAT this is zero-indexed1
```

**Comment by kareltucek** [comment]
I believe you are actually after a secondary role, maybe with some non-trivial resolution strategy. Is that correct?

**Comment by kareltucek** [comment]
Also, why not `holdKey space` instead of that `autoRepeat`?

**Comment by likern** [comment]
> 

Kind of. Multiple secondary roles. So space + space would result in switch to mouse layer, space + key would toggle to fn4.

**Comment by likern** [comment]
> 

Thank you, that works. But looks like with `holdKey space` I've found bug here.

**Comment by likern** [comment]
With that macro
```
ifShortcut timeoutIn 200 29 exec toMouseLayer
ifShortcut noConsume timeoutIn 1000 16 final holdLayer fn4
holdKey space
```
sometimes I get `9` instead of `(` on `fn4` layer.
![Снимок экрана от 2022-12-02 22-30-30](https://user-images.githubusercontent.com/842306/205371538-20ab5b6f-4b5a-4d96-968b-7acf39c04630.png)
![Снимок экрана от 2022-12-02 22-33-11](https://user-images.githubusercontent.com/842306/205371656-c40bf88a-d589-404f-bd5d-f21fa4c66332.png)
![Снимок экрана от 2022-12-02 22-34-15](https://user-images.githubusercontent.com/842306/205371824-affe27a1-d1f2-46fc-9e21-3f4b6380f19c.png)

**Comment by kareltucek** [comment]
> Note: Looking at source code I've found that %0 is similar to what I wanted

The `%0` notation is intended to query current state of the queue, not future state of the queue. Please, do not use it this way. 

> sometimes I get 9 instead of ( on fn4 layer.

This looks like your text editor cannot keep up with the fast input. Still, it should not be a problem when tapping a single key. Are you using any hardware or software in between UHK and the text editor? I mean like an RDP session or a KVM switch.

It should go away if you add `set keystrokeDelay 10` into your `$onInit` macro.

**Comment by likern** [comment]
No, keyboard directly attached to usb port of computer.   Native OS (Linux), gedit (simplest text editor), no virtual machine or anything.

I will test `autorepeat tapKey...` too.

**Comment by likern** [comment]
> No, keyboard directly attached to usb port of computer. Native OS (Linux), gedit (simplest text editor), no virtual machine or anything.
> 
> I will test `autorepeat tapKey...` too.

I've tested with `autorepeat ...` and also could caught this bug. I don't think this is somehow related to text editor beeing slow.

I think that's because in UHK there is freeze/delay/gap between "_changing a layer_" and "_apply automatic shift for key_" - so `fn4` layer has already loaded (and at that moment key `9/(` is pressed), while `Shift` has not applied to this key. That should be a bug in UHK logic.

Might be being able to bind directly to `(` (without using `Shift + 9` could solve this problem.

**Comment by kareltucek** [comment]
> I think that's because in UHK there is freeze/delay/gap between "_changing a layer_" and "_apply automatic shift for key_" - so `fn4` layer has already loaded (and at that moment key `9/(` is pressed), while `Shift` has not applied to this key. 

But in your setup, shift is not part of the layer switch. It is direct part of the 9 action. We are deliberately sending two reports so that modifier / scancode order is unambiguous.

Have you tried the keystrokeDelay?

If you share your UserConfig.json, I can give it a test, but I don't think UHK is sending them in wrong order.

> Might be being able to bind directly to `(` (without using `Shift + 9` could solve this problem.

You can't bind `(` directly without using (or editing) host-OS keymap which features scancode exclusively for `(`. Of course, feel free to edit your host-OS keymap...

**Comment by likern** [comment]
> This looks like your text editor cannot keep up with the fast input.

I've tested with terminal and I think you were right. With terminal can't reproduce this bug.

**Comment by mondalaci** [comment]
It seems to me that the issue has been (partially?) resolved. I'm closing this issue, but feel free to follow up.

**Comment by likern** [comment]
@mondalaci Can we reopen this (I can't)?
@kareltucek

I want this behaviour and think `ifSortcut` might help.

1. Press key `KEY`
2. Wait for some time gap (350ms), do nothing.
3. **After gap** if `KEY` is still pressing and no other keys were pressed during gap (no interruptions) - press `backspace` in sticky mode (autorepeat)
4. **During gap** if `KEY` was released and no other keys were pressed before release (no interruptions) - tap `backspace` once. This happens as soon as possible, so fast taps are supported.
5. **During gap** if `KEY` was interrupted by some key `OTHER_KEY` it works as `Ctrl`, tap `Ctrl + OTHER_KEY`. If `KEY` is still pressing continue pressing `Ctrl` - so `KEY + A + B` works as `Ctrl-A Ctrl-B`.

So this behaviour essentially fits into category Primary/Secondary roles. But now Primary/Secondary doesn't support this use case (at least I couldn't make it working), only cases where primary role holds modifiers which are invisible if released.

As far as I understand this should help:
```
ifShortcut noConsume timeoutIn 350 any_key final tapKeySeq C-any_key
holdKey backspace
```

**Comment by mondalaci** [comment]
@kareltucek Can you comment on this?

**Comment by kareltucek** [comment]
Using ifshortcut as primary/secondary role is an abuse of the command. 

But indeed implementation may be enough simple so that there might not be sufficient reason not to do it.

**Comment by likern** [comment]
> Using ifshortcut as primary/secondary role is an abuse of the command.
> 
> But indeed implementation may be enough simple so that there might not be sufficient reason not to do it.

I'm open to better and more robust solution. Updating `ifShortcut` is something came to my mind. I agree the desing is kind of ugly. If we can we need something better.

**Comment by kareltucek** [comment]
Since advanced secondary roles have been implemented, I would rather close this.
