### ISSUE TITLE
how to create macro with holding space + left mouse

### ISSUE THREAD

**Issue by msio** [UltimateHackingKeyboard/firmware#577]
I'm trying to create macro with holding space + left mouse. I want to achieve the same behaviour as you would hold left mouse and space. This kind of behaviour is mostly used in Graphics program when you want to move whole canvas.  
How can I achieve that by macros please

Thanks for any help
Cheers

**Comment by mondalaci** [comment]
@kareltucek Any ideas?

**Comment by kareltucek** [comment]
The trick is the `delayUntilRelease` macro command.

**Comment by kareltucek** [comment]
Also, you may need to enable the extended macro command mode, which can be done by creating a macro named `$onInit` that contains (at least) `set macroEngine.extendedCommands 1`.

**Comment by likern** [comment]
I think this should work
```
holdKey space
holdKey mouseBtnLeft
```
it doesn't (tested in Figma). Looks like a bug to me.

Note: in my mental model. It's not clear how all this machinery working - for example which commands are blocking. I expect this to be working.

**Comment by likern** [comment]
> 

```
pressKey space
pressKey mouseBtnLeft
delayUntilRelease
```

**Comment by kareltucek** [comment]
I believe this is solved? Feel free to protest!
