### ISSUE TITLE
Minus key doesn't work with ifShift

### ISSUE THREAD

**Issue by likern** [UltimateHackingKeyboard/firmware#582]
**Doesn't work**
```
ifShift suppressMods tapKey -
ifNotShift tapKey _
```
**Works**
```
ifShift suppressMods write -
ifNotShift write _
```
while other keys (0-9) are working with `tapKey`.

I'm using this feature to make keys reversible.

![Снимок экрана от 2023-01-09 11-25-46](https://user-images.githubusercontent.com/842306/211266492-a9d04b83-6b24-4eef-8956-afa7b52fff84.png)
![Снимок экрана от 2023-01-09 11-25-22](https://user-images.githubusercontent.com/842306/211266497-df998e2a-072c-4b56-a168-f114b4009bc1.png)
![Снимок экрана от 2023-01-09 11-24-52](https://user-images.githubusercontent.com/842306/211266499-9ae58108-1da6-4ad9-8a0d-3197bf6ba906.png)

**Comment by mondalaci** [comment]
@kareltucek Can you reproduce the issue?

**Comment by kareltucek** [comment]
Yes, will fix it soon...
