### ISSUE TITLE
[Macros] Expose the state of capslock, scroll lock, and numlock to use in macro conditions

### ISSUE THREAD

**Issue by rftw** [UltimateHackingKeyboard/firmware#585]
I noticed that on Windows OS, when I turned on/off the caps lock on a non-uhk keyboard, the caps lock led icon on the uhk is also turning on/off. Apparently Windows OS updates all the connected keyboards to be in the same state for modifiers like caps lock, regardless on which keyboard they are toggled. We can use this feature to allow non-uhk devices and uhk interact with each other. For example, I wish to toggle the scroll mode of UHK trackball when I turn on the numlock on my macropad. This is already possible in qmk firmware where they provide the led states of scroll lock / num lock / caps lock `host_keyboard_led_state().num_lock`. Can you provide the same so that we can use them in macro conditions. Also is it possible to change the navigation modes of modules using these conditions?

**Comment by mondalaci** [comment]
The firmware could expose $on{CapsLock|ScrollLock|NumLock}{On|Off} smart macro events to run user-specified macro commands, allowing for such features. Still, this feature feels quite niche, so I'm unsure whether it worths the effort. I keep this issue open, so we can see the demand and use cases.

**Comment by Totoro83** [comment]
While it's not something incredibly important for me, I would definitely like to write some macros to change the led text to show different things depending on caps, scroll and num lock statuses, and those events seem perfect for this. It's the only thing that at the moment I miss in my current setup.
