### ISSUE TITLE
$onLayerChange smart macro event

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#588]
At the moment, the display shows the active keymap, and layers are indicated with the "mod", "fn" and "mouse" LEDs.

Now that the firmware also has "fn2-fn5" (as well as "shift/alt/ctrl/super") layers, there are no indicators for there layers.

I would like to be able to show different text on the segment display when layers are switched. My use case: the secondary role of my Tab key switches to a layer with a num pad. I would like to display "NUM" when that layer is active.

**Comment by mondalaci** [comment]
Have you looked into smart macros? Maybe it's possible to implement your use case with them.

**Comment by kareltucek** [comment]
@mondalaci we don't have `$onLayerChange` event (at the moment anyway).

But yes, I find implementing `$onLayerChange` event to be a relatively reasonable request, which can be done quite easily.

**Comment by mondalaci** [comment]
@kareltucek Sounds good to me. How exactly would one implement @mhantsch's use case with the help of `$onLayerChange`?

**Comment by kareltucek** [comment]
Have one macro for each layer, e.g.:

`$onLayerChange fn`:
```
setLedTxt 0 fn
```

**Comment by mondalaci** [comment]
Makes perfect sense. Feel free to implement `$onLayerChange`.

**Comment by mondalaci** [comment]
Sorry, moving my comment to the PR.

**Comment by mhantsch** [comment]
What's the syntax for the onLayerChange and onKeymapLayerChange macro events? `$onKeymapLayerChange QWR mouse` ? `$onLayerChange fn2` ?

**Comment by kareltucek** [comment]
Yes. Namely:

```
    $onLayerChange {LAYERID|any}
    $onKeymapLayerChange KEYMAPID LAYERID
```

Docs are fixed now, thanks for pointing out!
