### ISSUE TITLE
Setting Macro to call other macros

### ISSUE THREAD

**Issue by adrianegraphene** [UltimateHackingKeyboard/firmware#595]
I have ~10 macros that I would like to run. I saw a comment that referred [to this](https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md).

I would like to create 1 Macro, that call 10 of my macros in sequential order.

So, I set the following command  `set macroEngine.extendedCommands 1` 

I can get a single macro to run by using the "Command" function.

However, I cannot get more than 1 macro to run at a time. I want something like the following.

```
exec App-FireFox-F4
exec App-voicemeeter
exec App-Slack-F2
exec App-PhoneLink
exec App-LogiTune
exec App-Notepad++-f9
```
but, only the 1st macro gets called

I've tried listing all my commands in the same command.... and creating different command blocks the same thing happens either way - just 1 macro runs.

Any suggestions for how I can trigger multiple macros from a single macro?

**Comment by IzK666** [comment]
Hi @adrianegraphene,

You should use CALL instead of EXEC.
The difference between them is that EXEC don't return, while CALL will run every macro one after another.
