### ISSUE TITLE
Steam Big Picture Mode thinks UHK is a Controller

### ISSUE THREAD

**Issue by NicholasJEllingson** [UltimateHackingKeyboard/firmware#596]
I realize that this is more of a "steam" problem than a "UHK" problem, but with the most recent Steam update, Steam thinks that the UHK is a controller. Because of this, if I launch a game through Steam, Steam automatically assigns the UHK as controller #1. This completely breaks the keyboard somehow (I'm assuming Steam is detecting inputs in the background and eating them?) making it so that I cannot type. Even if I close the game, the keyboard is still being locked by Steam and is unusable.

**Comment by mondalaci** [comment]
Are you using the latest 9.2.1 firmware version? If not, please update and retry.
