### ISSUE TITLE
multiple devices connected error

### ISSUE THREAD

**Issue by damky** [UltimateHackingKeyboard/firmware#597]
getting a "multiple devices connected error" when only one is connected using the cord the device came with. Seems to have happened after the recent macOS update. I noticed a new authorize notice come up asking to authorize uhk for input monitoring.

![Mar-30-2023 12-57-43](https://user-images.githubusercontent.com/18455931/228938117-07f0959d-fed1-4e7a-94f0-20c4e602cd8d.gif)

![Mar-30-2023 13-00-52](https://user-images.githubusercontent.com/18455931/228938153-fe8b47ed-24ba-4416-b8b4-7ee5fed96eb9.gif)

**Comment by mondalaci** [comment]
Duplicate of https://github.com/UltimateHackingKeyboard/agent/issues/1971
