### ISSUE TITLE
When changing LED brightness with higher value, it makes keyboard unreliable

### ISSUE THREAD

**Issue by kenhys** [UltimateHackingKeyboard/firmware#602]
Environment:

```
 Right keyboard half firmware: UltimateHackingKeyboard/firmware:9.2.2
 Left keyboard half firmware: UltimateHackingKeyboard/firmware:9.2.2
 Key cluster firmware: UltimateHackingKeyboard/firmware:9.2.2
 Trackpoint firmware: UltimateHackingKeyboard/firmware:9.2.2
```

May be related with https://github.com/UltimateHackingKeyboard/firmware/issues/484

* With stock bridge cable, changing LED brightness, it will work expectedlly

* When using more longer cable (~ max 2 meters because of spiral one), changing LED brightness higher (~ 200 ) cause unreliable behavior.
  * unreliable means that left keyboard, key cluster module, trackpoint module lost connectivity at random and agent shows these device seems lost.

Here is the movie to show the behavior:
https://user-images.githubusercontent.com/225841/229777327-b9fef544-d353-4b37-beae-1a5b9edf0927.mp4

With logging console, repeating that there are some object recognized/unrecognized status change.

Apparently, it is caused by my alternative bridge cable - the culprit, (not stock bridge cable).

Ref. https://ultimatehackingkeyboard.com/modding/can-i-have-a-longer-bridge-cable

> The cable should be as short as possible. The longer the cable, the higher the chance it'll make your UHK malfunction. 
> If you need a long cable, use a straight cable instead of a spiral cable to minimize overall cable length. Then you can go 
> as long as about 3 meters.

Yes, it should be shorter, but I want to know other person's experience (higher brightness) with working bridge cable length (spiral) even though it is longer than stocked bridge cable.

**Comment by mondalaci** [comment]
The long bridge cable is probably the major culprit.

Please read the relevant [troubleshooting instructions](https://ultimatehackingkeyboard.com/repair/fixing-misbehaving-keys).

This is not a firmware issue, so I'm closing it, but feel free to follow up, preferably via email at support at ultimatehackingkeyboard dot com.
