### ISSUE TITLE
Modifier layer pass through stopped working

### ISSUE THREAD

**Issue by tunney** [UltimateHackingKeyboard/firmware#603]
" If a key on the modifier layer is unmapped, the UHK will fall back to the base layer and compose its mapping with the modifier."

This used to work for the macOs modifier keys but since the latest firmware the "pass through" does not seem to work. For example, shift+a when the 'a' key is unmapped on the shift layer does nothing when it used to fault in 'A'

**Comment by mondalaci** [comment]
@kareltucek Can you look into this?

**Comment by mondalaci** [comment]
Fixed in https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v9.2.3
