### ISSUE TITLE
ifAnyMod only works on legacy keys

### ISSUE THREAD

**Issue by Festiu** [UltimateHackingKeyboard/firmware#612]
Hi,

I notice that ifAnyMod (and variants like ifCtrl, ifGui etc) only works when legacy keys are pressed. I mean, if for example I create a macro that simulates Super (holdKey leftGui) and then in another macro I want to evaluate if is pressed with ifGui or ifAnyMod, it doesn't work. Only works with the original Super (without using macros)

In my case I use a macro to press left Super key. I do it because I like press Ctrl with the palm of my hand, and sometimes I hit it together with the Super key by mistake. It works great on the Base layer, but not on the Mouse one where I have some rules with ifAnyMod and such

Any work around this?

**Comment by kareltucek** [comment]
Search https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md for "input modifiers". 

In practice, you want to use `holdKey iLG-` to trigger your Super key.

(Closing, feel free to follow up.)
