### ISSUE TITLE
Progressive mouse acceleration

### ISSUE THREAD

**Issue by Festiu** [UltimateHackingKeyboard/firmware#613]
Hi, I'm trying to make my own buttons to decelerate / accelerate mouse speed, having the same functionality as the default ones via menu - Decelerate / + Accelerate, but with a bypass key with ifAnyMod

```
ifAnyMod final holdKey d // Bypass key
set mouseKeys.move.initialAcceleration 6375
set mouseKeys.move.initialSpeed 500
set mouseKeys.move.baseSpeed 500
delayUntilRelease
set mouseKeys.move.initialSpeed 1800 // Restore speed
set mouseKeys.move.baseSpeed 1800 // Restore speed
```

They work ok, but I feel some kind of a progressive de/acceleration, that doesn't show up on the default buttons. It's like if I was missing some parameter on mouseKeys.move however none of the available ones seems to serve that purpose (initalSpeed, baseSpeed, initialAcceleration, deceleratedSpeed, acceleratedSpeed)

I like moving fast, in a very sensitive way, and I'd like to decelerate instantly in a raw way. Is it possible?

**Comment by kareltucek** [comment]
UHK adjusts towards target speed by initialAcceleration _per second_, therefore, your observation is correct. 

Following seems to give instant deceleration:
```
ifAnyMod final holdKey d // Bypass key
set mouseKeys.move.initialAcceleration 1000
set mouseKeys.move.initialSpeed 1
set mouseKeys.move.baseSpeed 1
startMouse decelerate
delayUntilRelease
stopMouse decelerate
set mouseKeys.move.initialSpeed 1800 // Restore speed
set mouseKeys.move.baseSpeed 1800 // Restore speed
```

(It will need some additional tweaking, but I am sure you can manage...)

**Comment by Festiu** [comment]
Yes, that's exactly what I needed. Thank you very much
