### ISSUE TITLE
Support of register values in setLedTxt

### ISSUE THREAD

**Issue by soloidx** [UltimateHackingKeyboard/firmware#614]
Hello, this is not an urgent matter but it would be nice:

I am currently creating a basic VIM engine inside the keyboard and I want to display a number from the registry inside the led text panel.

currently `setLedTxt 2000 #22` displays "22" in the led display

**Comment by kareltucek** [comment]
I have seen this request before...

I am fine with merging a PR along these lines. (E.g., a new command `setLedReg 2000 22`, or anything else reasonable.) Otherwise, noted but it is not a priority at the moment.

**Comment by kareltucek** [comment]
Also thinking about `setLedNum 2000 #22`, so that this can be used to output other numeric stuff...

@mondalaci any opinions?

**Comment by mondalaci** [comment]
@kareltucek How would `setLedReg` and `setLedNum` differ?

**Comment by kareltucek** [comment]
One takes register number/name as an argument, the other takes any number. The second one is more general because it can output any information that can be obtained as a number - e.g., postponed queue, keyids, in future probably configuration values, etc..

The question was meant more along the lines of whether we want to support either of them, or not, or something else than decision between the two (`setLedNum` is clear winner for me when it comes to deciding which of the two).

**Comment by mondalaci** [comment]
Both commands make sense to me, but is there a way to make commands polymorph instead of introducing per-type command names?

**Comment by kareltucek** [comment]
Yes, but the language will need to be refactored to support proper string tokens... ...which admittedly should be done anyways.

But I am not sure if going polymorph is actually a good thing. 🤔

**Comment by mondalaci** [comment]
My brain deals easier with a smaller API surface, even if polymorphism is introduced, but feel free to voice your concerns.

**Comment by mhantsch** [comment]
If you refactor the language anyway, perhaps that's a chance to think about the ifGesture/ifShortcut key ids vs. characters again. Number would be key id, and String would be a character to be converted into the matching key id. See also the discussion around https://forum.ultimatehackingkeyboard.com/t/key-id-symbols-wanted/226/35

**Comment by mondalaci** [comment]
@mhantsch We've already agreed on key id handling in https://github.com/UltimateHackingKeyboard/firmware/issues/630#issuecomment-1630574561

**Comment by mhantsch** [comment]
> @mhantsch We've already agreed on key id handling in [#630 (comment)](https://github.com/UltimateHackingKeyboard/firmware/issues/630#issuecomment-1630574561)

I had missed that one. Thanks.
