### ISSUE TITLE
FTY - Invalid Signature

### ISSUE THREAD

**Issue by TeamBrett** [UltimateHackingKeyboard/firmware#615]
My keyboard (v1) is stuck in FTY mode.  I've tried it on 3 different computers with plenty of USB power and I've tried disconnecting power and reconnecting and disconnecting, waiting a deal of time, then reconnecting.  No luck.  When I open the UHK client I get a red message saying "Please power cycle your keyboard (Invalid hardware configuration: Invalid Signature).

![image](https://github.com/UltimateHackingKeyboard/firmware/assets/1856015/0b8f3ab5-43d6-4d23-80fa-314161ddf527)

**Comment by ert78gb** [comment]
Please check the https://github.com/UltimateHackingKeyboard/agent/issues/2009#issuecomment-1536831370

**Comment by mondalaci** [comment]
Closing due to the lack of replies.
