### ISSUE TITLE
LED fade out too soon

### ISSUE THREAD

**Issue by Zot1881** [UltimateHackingKeyboard/firmware#632]
For some reason on latest agent\firmware no matter what LED fade timeout i configure leds fade out after ~10 seconds.

**Comment by mondalaci** [comment]
Do you have a smart macro that overrides Agent's LED fadeout settings?

**Comment by Zot1881** [comment]
Sorry, yes i forgot to remove it and previously it was 10 minutes :). Now works great. Thank you.
