### ISSUE TITLE
Macro on shift layer not working correct

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/firmware#641]
To my understanding the shift layer is just another layer option which will be activated with the shift key.
The following will output Qu correctly in any layer (e.g. Fn2), but not in the shift layer, where it wrongly outputs QU. Workarounds to split the command (Q and later pressing the u-key in the macro) make no difference.

![image](https://github.com/UltimateHackingKeyboard/firmware/assets/51239533/64030f68-cdd9-4e7a-9795-836e5dc128f2)
[UserConfiguration.zip](https://github.com/UltimateHackingKeyboard/firmware/files/12070165/UserConfiguration.zip)

**Comment by kareltucek** [comment]
I believe this is a duplicate of #608

**Comment by kareltucek** [comment]
Closing in favor of 608, please, join the discussion there.

**Comment by rpnfan** [comment]
Thanks, looking forward the release :-)
