### ISSUE TITLE
Detect caps lock state

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#65]
Currently, the Caps Lock LED of the UHK is always off because the USB API of KSDK doesn't expose the state of Caps Lock.

Please simply call `LedDisplay_SetIcon(LedDisplayIcon_CapsLock, capsLockStateVariable)` to set the LED.

According to my knowledge, keyboard LED state is sent in the set report request of endpoint 0, so I assumed that it resides in the report buffer of [this code block](https://github.com/UltimateHackingKeyboard/firmware/blob/569493cbfa431bd76e86ffa9bd7e6b69aeb948aa/right/src/ksdk_usb/usb_device_hid.c#L462-L476). I dumped the value of the buffers of both clauses but none contained keyboard LED state.

**Comment by NicoHood** [comment]
You can compare with the code here:
https://github.com/NicoHood/HID/blob/master/src/SingleReport/BootKeyboard.cpp#L165
https://github.com/PaulStoffregen/cores/blob/master/usb_hid/usb.c#L837
https://github.com/abcminiuser/lufa/blob/master/Demos/Device/LowLevel/Keyboard/Keyboard.c#L168

Those are 3 different implementations, you should be able to figure it out.
