### ISSUE TITLE
Support advancedStrategy for FN layers

### ISSUE THREAD

**Issue by likern** [UltimateHackingKeyboard/firmware#650]
I set up `fn3` as secondary role for  `advancedStrategy` for base layer.
Now I want to do the same for the same key but at different layer.

It will allow me to switch to digits-only layer (`fn2`) and being able to use `+ - * / , . $` at  `fn3`

GUI doesn't allow to switch layer as secondary role for `fn2`, no such option.
I tried to use macros `ifSecondary ...` but it seems also doesn't work.

**Note:** I have master agent and flashed agent firmware
**Note:** I have global `set secondaryRole.defaultStrategy advanced` on `$onInit`

![Screenshot from 2023-07-25 11-32-26](https://github.com/UltimateHackingKeyboard/firmware/assets/842306/f6105f5f-6b3c-4e5e-ac2a-0b6893a9108c)

![Screenshot from 2023-07-25 11-32-43](https://github.com/UltimateHackingKeyboard/firmware/assets/842306/f364707c-2740-4092-9a5d-56b04e24c762)

![Screenshot from 2023-07-25 11-33-20](https://github.com/UltimateHackingKeyboard/firmware/assets/842306/74806455-48be-4771-a4f1-88e5f0807161)

![Screenshot from 2023-07-25 11-33-49](https://github.com/UltimateHackingKeyboard/firmware/assets/842306/d723b6cd-e602-418b-8fe9-d8113b9acf19)

**Comment by mhantsch** [comment]
I believe within Agent, layer switching is only supported from the base layer. You'd have to use macros to achieve what you want (stacking layers).

**Comment by likern** [comment]
> I believe within Agent, layer switching is only supported from the base layer. You'd have to use macros to achieve what you want (stacking layers).

I think `switchLayer` just doesn't with advancedStrategy, it least I tried solve this using macroses.

**Comment by likern** [comment]
My `$onInit` setup
```
set keystrokeDelay 10

set secondaryRole.defaultStrategy advanced
set secondaryRole.advanced.timeout 350
set secondaryRole.advanced.timeoutAction secondary
set secondaryRole.advanced.safetyMargin 0
set secondaryRole.advanced.triggerByRelease 1
set secondaryRole.advanced.doubletapToPrimary 0

switchKeymap TST
exec configureTrackpoint
```

**Comment by kareltucek** [comment]
`ifSecondary` is broken in 10.0.0. Please wait for next release.

If you wish help with any of your macros, please post the macros that you have tried.
