### ISSUE TITLE
Support ctrl+shift using advancedStrategy

### ISSUE THREAD

**Issue by likern** [UltimateHackingKeyboard/firmware#651]
According to this comment https://github.com/UltimateHackingKeyboard/firmware/pull/639#issuecomment-1648627706 it should work on master branch with agent firmware.

But it **doesn't work** for me (`tapKey` also didn't work).

- [ ] Just single tap on key `s` doesn't produce key `s`

Overall it doesn't work and fill like `advancedStrategy` setup through UI (which works very well and smooth)

![Screenshot from 2023-07-25 12-05-21](https://github.com/UltimateHackingKeyboard/firmware/assets/842306/82051974-ead9-4009-82a2-71705609f91c)

**Comment by likern** [comment]
My `$onInit` setup
```
set keystrokeDelay 10

set secondaryRole.defaultStrategy advanced
set secondaryRole.advanced.timeout 350
set secondaryRole.advanced.timeoutAction secondary
set secondaryRole.advanced.safetyMargin 0
set secondaryRole.advanced.triggerByRelease 1
set secondaryRole.advanced.doubletapToPrimary 0

switchKeymap TST
exec configureTrackpoint
```

**Comment by kareltucek** [comment]
You need up-to-date firmware, not agent.

**Comment by likern** [comment]
> You need up-to-date firmware, not agent.

I thought if I build agent from source (as in documentation) it will use master firmware. Is it correct?

**Comment by kareltucek** [comment]
No.

It downloads the firmware from github according to version that is manually entered in package.json. This version is manually updated and committed to the repository on releases.

You really need to clone the firmware repository and build that.

**Comment by likern** [comment]
> No.
> 
> It downloads the firmware from github according to version that is manually entered in package.json. This version is manually updated and committed to the repository on releases.
> 
> You really need to clone the firmware repository and build that.

Get that, will close for now and test on new release
