### ISSUE TITLE
Unrecognized command: untoggleLayer

### ISSUE THREAD

**Issue by likern** [UltimateHackingKeyboard/firmware#656]
Error message by `printStatus`:
```
M_fn2: 0: 0: unrecognized command: untoggleLayer
```
**base layer:**
```
ifSecondary final holdLayer fn2
ifDoubletap final toggleLayer fn2
holdKey m
```

**fn2 layer:**
```
untoggleLayer
```

I think my macros is not fully correct, but it's not relevant to this error (before `toggleLayer` one `m` letter is printed)

**Note:** it's an advanced mode with the following config
```
set keystrokeDelay 10

set secondaryRole.defaultStrategy advanced
set secondaryRole.advanced.timeout 350
set secondaryRole.advanced.timeoutAction secondary
set secondaryRole.advanced.safetyMargin 0
set secondaryRole.advanced.triggerByRelease 1
set secondaryRole.advanced.doubletapToPrimary 0

switchKeymap TST
exec configureTrackpoint
```

![Screenshot from 2023-07-29 19-31-16](https://github.com/UltimateHackingKeyboard/firmware/assets/842306/8e1d96d8-e1e8-4280-8f03-27bb489b2e5d)
![Screenshot from 2023-07-29 19-31-31](https://github.com/UltimateHackingKeyboard/firmware/assets/842306/b2075559-c66c-414a-a1b0-09b06eda286a)

**Comment by kareltucek** [comment]
Should be `unToggleLayer`. (Yes, macro commands are case sensitive.)

**Comment by likern** [comment]
Sorry, my bad. I've verified before creating new issue, but it turns out that didn't turned on match case while searching.
