### ISSUE TITLE
Windows 7 & 8 enumeration issues

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#66]
The current UHK firmware doesn't seem to play nice with Windows for some reason.

Sometimes, it doesn't enumerate at all on Windows 7 Ultimate SP1 32-bit and Windows 8 Professional x64. (No other Windows versions have been tested yet.)

**Comment by NicoHood** [comment]
I cannot really help on this issue, sorry. I dont use windows, nor do I know your code. I suggest using LUFA, it is widely tested.

**Comment by mondalaci** [comment]
I used to use LUFA for our older AVR based firmware, but our firmware has been ported to ARM, so LUFA is not an option anymore. Thanks for the idea anyways!

**Comment by mondalaci** [comment]
I can confirm this #93 fixed this one, too.
