### ISSUE TITLE
Timeout for OneShot

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/firmware#701]
Add configurable timeout option for OneShot, to prevent "hanging" Shift function when this is used in combination with external mouse combos.

see: https://forum.ultimatehackingkeyboard.com/t/kill-macro-oneshot-after-a-specific-time/494

**Comment by kareltucek** [comment]
Thanks for creating the ticket!

Please suggest default value for the timeout.

**Comment by rpnfan** [comment]
>  I looked up what the default repeat delay for a keystroke in Windows is. That is 500ms, with options for 250ms, 750ms and 1000ms as well. 

So for that use case here I think 500 ms is also a good default. For "slow" typing ( about 24 wpm) long enough, but still not too long to have to wait forever, when one is doing another action. For myself I think I want to set it to 250 or 300 ms longest, as holding Shift to mark multiple items in a list will still work and then timing is not critical.
