### ISSUE TITLE
Logical operators && and || missing

### ISSUE THREAD

**Issue by tunney** [UltimateHackingKeyboard/firmware#706]
The release notes for 10.2.0 mention and && and || but I cannot see them in the syntax for 10.2.0 or 10.3.0
Their presence in a macro does not cause an issue but they don't seem to work. At least the && tends to operate as an "or".

<img width="909" alt="image" src="https://github.com/UltimateHackingKeyboard/firmware/assets/860018/69114460-f764-44a6-96d0-5c94aa8ac6f0">

<img width="501" alt="image" src="https://github.com/UltimateHackingKeyboard/firmware/assets/860018/167f4ee8-7052-4d01-90cf-a81761cf580c">

Will ands and ors in the if expressions be supported? Or are the release notes ambitious?

**Comment by kareltucek** [comment]
Ouch. Thanks for report!

**Comment by kareltucek** [comment]
Release notes are fine, it is the release itself that is not fine, as well as its documentation 😅.
