### ISSUE TITLE
Basic mouse interface BIOS fallback

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#71]
The current mouse interface is fairly advanced featuring horizontal + vertical scrolling. The problem is that it doesn't seem to be handled by BIOSes. Let's also expose a basic BIOS compatible mouse and fall back to it if needed the same way as for #70.

**Comment by Lauszus** [comment]
Adding a hidboot mouse interface should solve this issue.

**Comment by mondalaci** [comment]
I've just checked the UHK mouse in the UEFI BIOS of my PC, and it works. This doesn't mean that it works with all BIOSes, but I think adding an extra USB interface just for this niche use case is overkill. One should not spend a lot of time in old BIOSes, and they support keyboard input anyways.
