### ISSUE TITLE
Latest Firmware exception with `onInit` Macro

### ISSUE THREAD

**Issue by mohitt** [UltimateHackingKeyboard/firmware#711]
With the firware version `10.3.0` I started seeing following error in my `onInit`

```
Error at $onInit 1/3/22: Unrecognized command: ScrollSpeedDivisor
```

My `onInit` Commands are

```
set module.trackball.baseSpeed 1.1
set module.trackball.speed 2.3
set module.trackball.ScrollSpeedDivisor 16
```

Documentation says it is supported

**Comment by kareltucek** [comment]
> Documentation says it is supported

No, it does not!

The syntax is case sensitive. Should be:

```
set module.trackball.scrollSpeedDivisor 16
```

**Comment by mohitt** [comment]
![image](https://github.com/UltimateHackingKeyboard/firmware/assets/919686/7441998f-091c-438f-8396-eb962b52e90a)
This is what I see in documentation and surprisingly it was working in version 9

**Comment by kareltucek** [comment]
Ahh, this documentation. Will fix that.
