### ISSUE TITLE
Sticky modifiers not getting cleared due to navigation modes.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#722]
Scenario:

- Have a "switch tab right" (Ctrl+PgDown) bound in your mod layer. Also, have mod layer navigation mode set to scrolling. 
- Switch tab and scroll immediately afterwards, before releasing the "switch tab" key.
- Observe page getting zoomed.

Correct behavior: just as sticky mods get cleared by any other key action, I think they should be cleared by any navigation mode action.

**Comment by mondalaci** [comment]
I can't reproduce the mentioned issue.

Also, I don't understand what you mean by "navigation mode action".

**Comment by kareltucek** [comment]
> Also, I don't understand what you mean by "navigation mode action".

An action produced by a navigation mode. E.g., scrolling via right-hand module.

> I can't reproduce the mentioned issue.

Well, simpler setup then. 

- Map Ctrl+C on your base layer C key.
- Change your base layer navigation mode to scroll.

Now:

- Press and hold the c key.
- Move your trackpoint up.

Expected behavior:
- Ctrl+C gets emitted
- Ctrl gets released
- Page scrolls up

Actual behavior:
- Ctrl+C gets emitted
- Page zooms in

**Comment by mondalaci** [comment]
Still can't reproduce. The expected behavior happens on my side.

**Comment by kareltucek** [comment]
That's just not possible. Are you holding the c key while doing the scrolling via the right hand module?

**Comment by mondalaci** [comment]
Sorry for not being observant. I can reproduce the mentioned current behavior, and I agree with the proposed expected behavior.
