### ISSUE TITLE
MacOS Sonoma Keyboard shut-down on lock

### ISSUE THREAD

**Issue by emin-grbo** [UltimateHackingKeyboard/firmware#729]
Sometimes (1-3 times a day), after my computer was in locked state, I need to plug out/in the keyboard in order for it to work.
I have a V2 keyboard, bought less than 6 months ago I think.

System: macOS Sonoma (it actually started after the latest update)
Agent version: 3.2.1

**Comment by mondalaci** [comment]
Does the locked state put USB devices to sleep? I'm asking because if not, this detail is irrelevant, and your UHK would reproduce the issue regardless when not used for a while.

**Comment by mondalaci** [comment]
Closing because of the lack of replies.

Feel free to follow up regardless.

**Comment by emin-grbo** [comment]
Sorry for the delay, just saw the closure notification now 😅
I am not sure as the only plugged device is the keyboard. I have a bluetooth trackPad next to it and that's it.

However, not sure it happened after the latest OS update, so I will try to track occurrences with more details and see if its reproducible more consintently.
