### ISSUE TITLE
Firmware 10.4.0 regression: no longer parses `@0`

### ISSUE THREAD

**Issue by robbievogt** [UltimateHackingKeyboard/firmware#731]
I have several macros implementing "sticky" layer modifiers, that rely on the macro time machine and wait loops.

E.g. 
```
postponeKeys ifNotPending 1 ifNotPlaytime 2000 goTo @0  // wait up to 2 sec for a single pending key
```

These stopped working with firmware update to 10.4.0. The error console in UHK Agent (nice addition!!!) complains that it can't parse `@0`. 

There are workarounds for this (e.g. labels), but it left my keyboard in an unusable state after the firmware update due to the regression.

**Comment by kareltucek** [comment]
Yes, please replace it by `$currentAddress`. 

(Closing, but feel free to follow up!)

**Comment by robbievogt** [comment]
Thanks Karel, makes sense.

Not there are a couple of references to the `@` syntax in the docs still:

* user-guide.md, line 717
* reference-manual.md, line 255

**Comment by kareltucek** [comment]
Thanks! 

The first one is fixed.

The second one is in "removed" command section, therefore intentional ;-).
