### ISSUE TITLE
Right click menus on macOs can often disable the keyboard

### ISSUE THREAD

**Issue by tunney** [UltimateHackingKeyboard/firmware#736]
I have only started to notice this recently.
V2 connected directly to macbook pro. Latest versions of OS and the like.

Sometimes when I right click on items, happens in all manner of applications, I get the keyboard no longer responding at all and I have to unplug it and plug it back in.
Not every time I right click on something but very very frequent

**Comment by tunney** [comment]
Latest firmware as well

**Comment by tunney** [comment]
On closer inspection I fear that this is a hardware issue. Apologies for raising in error.

**Comment by mondalaci** [comment]
I also believe that this is a hardware issue. Feel free to reach out to [our support](https://ultimatehackingkeyboard.com/contact-us).
