### ISSUE TITLE
UHK still recognized as a game controller with firmware 11.0.2

### ISSUE THREAD

**Issue by matthjes** [UltimateHackingKeyboard/firmware#770]
Hi,

I've already talked with László Monda about this:

My UHK is still recognized as a game controller in Windows 10 with firmware 11.0.2:

![screenshot](https://github.com/UltimateHackingKeyboard/firmware/assets/1440866/07885497-d3bf-4ebc-afbc-055922629a14)

Steam also shows the UHK three times as a controller:

![screenshot1](https://github.com/UltimateHackingKeyboard/firmware/assets/1440866/8246e23b-2c60-422a-88b2-0c35e33d5189)

Here is a screenshot showing the currently flashed version:

![screenshot2](https://github.com/UltimateHackingKeyboard/firmware/assets/1440866/28066eba-61b7-4550-98ca-9b28491400e6)

I don't know what further information you require, please just ask, I'll provide it.

**Comment by mondalaci** [comment]
@benedekkupper How can this happen since https://github.com/UltimateHackingKeyboard/firmware/commit/45fd12a188548d0a55cfe5cd4ade59261f1f4dc0?

**Comment by benedekkupper** [comment]
I'm as clueless as you are.

@matthjes please follow these instructions to [install usbview](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/usbview). When you run this program, you can inspect the USB bus tree of your computer, and it allows you to inspect the descriptors of your USB devices. Please send us a screenshot of the UHK device's view.

**Comment by matthjes** [comment]
Hi,
Attached you'll find the output for the UHK 60 v1.
[USBViewAll.txt](https://github.com/UltimateHackingKeyboard/firmware/files/15053358/USBViewAll.txt)

**Comment by benedekkupper** [comment]
Well according to this the UHK isn't presenting a gamepad interface to your computer. Can you test it on another Windows machine, preferably with which you didn't use it before? I can imagine that a stray registry entry is the root cause of this.

**Comment by matthjes** [comment]
The registry tip was a good one. I've searched for "UHK" the registry and there were two entries with "Controller (UHK 60 v1)" in their title (like in the screenshots above). I've deleted the entries and now it no longer shows up in Windows or Steam.

Thanks!
