### ISSUE TITLE
UHK v1 - Single LED not working after flashing 11.0.0 firmware

### ISSUE THREAD

**Issue by brt-duda** [UltimateHackingKeyboard/firmware#773]
UHK v1 with backlight turns off the LED underneath 'H' key after firmware upgrade.

Downgrade to 10.5.0 resolved the issue. 

Problem can be replicated by upgrading the firmware 11.0.0 again.

**Comment by kareltucek** [comment]
Please flash 11.0.2 from https://github.com/UltimateHackingKeyboard/firmware/releases
