### ISSUE TITLE
User guide and reference not easy to find

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/firmware#779]
Please add a link in the firmware readme to

https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/user-guide.md

and

https://github.com/UltimateHackingKeyboard/firmware/blob/master/doc-dev/reference-manual.md

For avid github users it might be self explaining where to find those, not for Joe Average :)

**Comment by kareltucek** [comment]
Done by https://github.com/UltimateHackingKeyboard/firmware/commit/ba5cea2c2692ad38bd3230247e172566115bb4a2 . Thanks for head ups :-).

**Comment by rpnfan** [comment]
Great, thanks a lot! 👍  :-D
