### ISSUE TITLE
Mac mouse should be inverted

### ISSUE THREAD

**Issue by spuder** [UltimateHackingKeyboard/firmware#78]
OSX by default does inverted scrolling. (Since OSX Lion)

The `Y` and `H` scrolling feel wrong to me. I think if you have selected QWM, it should default to inverted scrolling on Mac.

Two ways to querry the OS setting for scroll

https://stackoverflow.com/questions/30767674/change-scroll-direction-on-mac-programatically-assign-to-key-combination-comman

https://stackoverflow.com/questions/12433018/how-to-check-scrolling-direction-of-osx-with-cocoa-apis

**Comment by spuder** [comment]
Never mind, I now realize that the Y and H key are just doing a 'page up' and 'page down'. The UHK should be consistent with those keys.

**Comment by mondalaci** [comment]
I assume you closed this due to https://github.com/UltimateHackingKeyboard/agent/issues/535

Looks like we're totally on the same page regarding the solution. Thanks for reporting!

**Comment by spuder** [comment]
Yes, it is a duplicate.
