### ISSUE TITLE
Fn light only stays lit for Fn layer

### ISSUE THREAD

**Issue by tunney** [UltimateHackingKeyboard/firmware#784]
If I activate FN2, or FN3 the FN light does not light up.
It only seems to light for FN layer.

I could have sworn it used to light up for all the FNx layers

**Comment by kareltucek** [comment]
My memory says you are wrong, but it is a fair feature request. @mondalaci, your take? Should fn2-fn5 light up fn led?

**Comment by mondalaci** [comment]
I don't feel too strongly about this one, but I think it's the Right thing to do, so feel free to make it happen.

**Comment by mhantsch** [comment]
I would not necessarily want _**`fn`**_ indicator to be lit for all my _fnX_ layers. Can you control the modifier lights from macros? That could be another awesome niche feature (like so many in the UHK... :smirk:)

**Comment by kareltucek** [comment]
No and we are not going to!

(Have you started your firmware fork yet? 😇)
