### ISSUE TITLE
ISO keys are lit in switch tester mode on the UHK 80

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#823]
When the layout is set to ANSI on the UHK 80, and the switch test mode is enabled, I press a key. Only this key should be lit but the ISO Shift and the extra ISO key are also lit.

**Comment by mondalaci** [comment]
@kareltucek Please make this a priority.

**Comment by kareltucek** [comment]
I am not sure how to reproduce this.

> I press a key

You press which key?

When hwconfig on my uhk80 is set to ansi layout and I press ansi shift, only ansi shift get's lit.

**Comment by mondalaci** [comment]
1. The layout is ANSI.
2. I enable the switch testing mode.
3. I press escape, and only it should be lit. I see this instead:
![IMG20241210180915](https://github.com/user-attachments/assets/98f99ed2-3971-42de-9af4-f88243956e60)

**Comment by kareltucek** [comment]
Is user config flashed?

**Comment by mondalaci** [comment]
At this point, it should be.

**Comment by mhantsch** [comment]
> only ansi shift get's lit.

@kareltucek Are you testing on an ISO or an ANSI UHK 80? I am asking because laci's photo is from an ISO-populated board, isn't it?

**Comment by kareltucek** [comment]
I am testing with ansi board, but can see the iso leds quite clearly.
