### ISSUE TITLE
Remove the 6KRO configuration option

### ISSUE THREAD

**Issue by benedekkupper** [UltimateHackingKeyboard/firmware#829]
According to [this feedback](https://github.com/UltimateHackingKeyboard/firmware/issues/536#issuecomment-1820187822), the KVM compatibility issue with NKRO configuration might be solved just by having the keyboard interface at interface index 0. If that proves to be true, and noone demands a 6KRO fallback option (this is not the same as BOOT protocol, it adds a second HID keyboard interface that uses 6KRO report protocol), we should remove the related code.

**Comment by mondalaci** [comment]
> might be solved just by

Agreed, but emphasis on *might*. If 6KRO fallback is already implemented in the current codebase, it should not be removed yet.

**Comment by benedekkupper** [comment]
I'm closing this for now as we are using this on Android where the MTU negotiation fails/isn't done and the NKRO report is too long to make it through.
