### ISSUE TITLE
Disable LED display during sleep

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#83]
To save power.

**Comment by borje** [comment]
I agree to this.

**Comment by Lauszus** [comment]
I had a quick look at the document "Hut1_12v2.pdf" which defines all the HID Usage Tables. See page 61 chapter 11. 

It looks like we can simply extend the LED usage page: https://github.com/UltimateHackingKeyboard/firmware/blob/fa8c9dc907ef80a21ddcc6002175f1a0c4c42351/right/src/usb_descriptors/usb_descriptor_basic_keyboard_report.c, so it includes "Power" (id 6) or "Stand-by" (id 27).

We have to make sure it still is hidboot compliant, but I believe at least "Power" should be.

**Comment by mondalaci** [comment]
Thanks for looking into it! This sounds like the way forward when we get there. Currently it's not a high priority issue.
