### ISSUE TITLE
Async SPI porting

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#837]
Use `spi_write_async()` instead of the current sync calls for the OLED and LED drivers.

(I only used sync calls for the sake of quick prototyping.)

**Comment by mondalaci** [comment]
@kareltucek Can you proceed with this?

**Comment by kareltucek** [comment]
Yes, I plan to get to it soon. Tonight or tomorrow. 

Does it block anything? Sounds like a low priority issue to me.

**Comment by mondalaci** [comment]
Yes, it blocks the proper implementation of the LED driver, providing functional and per-key backlighting. Better port SPI first.

**Comment by kareltucek** [comment]
Allright.

> it blocks the proper implementation of the LED driver, providing functional and per-key backlighting

Could you elaborate?

If those two are entangled, it would be better for me to understand that when writing the oled update...

**Comment by mondalaci** [comment]
The rationale is that I'd rather have the current, moderate amount of sync SPI code ported to async than much more code later.

**Comment by kareltucek** [comment]
Well, I assumed we want to write the display update so that next spi write is initiated from within an spi callback, but it seems that this is not possible (since semaphores are not allowed to wait in interrupts, and the spi implementation uses waiting semaphore locks).

Without writing spi from spi callback, the spi has to be fed from a dedicated thread that waits to be polled when the spi write finishes... which does not add any value compared to synchronous spi writes, or does it?

Or did you perhaps mean some other means if implementation?

**Comment by mondalaci** [comment]
It seems that `spi_write_async()` is deprecated in favor of `spi_write_signal()`, and the latter should be used. Then `k_poll(&my_event, 1, K_FOREVER)` should be used in an infinite loop inside of a thread, `my_event` containing the signal that gets triggered by `spi_write_signal()`.

Relevant resources:
- https://chatgpt.com/share/767d44ca-bd1d-4b0a-87f8-21764b120483
- https://docs.zephyrproject.org/latest/kernel/services/polling.html
- https://docs.zephyrproject.org/apidoc/latest/group__poll__apis.html

Does the above make sense? Feel free to ask me if you have more questions.

**Comment by kareltucek** [comment]
Well, I do see how it is meant to be used. I just don't see any benefit to using spi_write_signal() or spi_transceive_cb() over the synchronous spi_write(). 

I have just tested that spi_write() does *not* block other threads from running while the write is taking place.

One more question. I don't see CONFIG_PREEMPT_ENABLED in prj.conf. It means that we are using non-preemptive scheduling, and that we are doing it deliberately, right?

**Comment by mondalaci** [comment]
Since `spi_write()` is synchronous, it blocks its thread (but not other threads) upon writing every byte, resulting in frequent context switches and heavy overhead. This explains why the OLED display updates are so slow instead of seemingly instantaneous, which, I believe, is achievable. `spi_write_signal()` allows writing numerous bytes much more efficiently.

`CONFIG_PREEMPT_ENABLED` is [not directly user-assignable](https://docs.zephyrproject.org/2.7.5/reference/kconfig/CONFIG_PREEMPT_ENABLED.html), and it's indirectly enabled because in the `zephyr/include/generated/autoconf.h` of build directories, `#define CONFIG_PREEMPT_ENABLED 1` is present.

**Comment by kareltucek** [comment]
Well, but if we call spi_write_signal from inside an infinite loop (that waits for polling signal), then that thread is also effectively blocked, and in order for other threads to run, there have to be standard context switches. So where is the improvement?

**Comment by mondalaci** [comment]
The improvement is due to the number of context switches. With `spi_write()`, it happens on every byte. With `spi_write_signal()`, it should happen much less frequently. The application logic should be modified accordingly to write many bytes per call.

**Comment by kareltucek** [comment]
So you say that a synchronous blocking spi write naively implemented via spi_write_signal should usually not yield (context switch), while the library-provided spi_write implementation is likely to yield on each call. And that this should give better performance.

That is easilly testable, and no it does not give a better performance than simple spi_write.

**Comment by kareltucek** [comment]
For reference what I have been testing:

```
static const bool useSignals = true;

void writeSpi(uint8_t data)
{
    if (!useSignals) {
        buf[0] = data;
        spiBuf[0].buf = buf;
        spiBuf[0].len = 1;
        spi_write(spi0_dev, &spiConf, &spiBufSet);
    } else {
        buf[0] = data;
        spiBuf[0].buf = buf;
        spiBuf[0].len = 1;

        k_poll_signal_reset(&my_signal);

        spi_write_signal(spi0_dev, &spiConf, &spiBufSet, &my_signal);

        k_poll(&my_event, 1, K_FOREVER);
    }
}
```

**Comment by kareltucek** [comment]
Anyways, while chatGpt supports your hypothesis, it still makes no sense to me.

I don't see why a k_poll should not yield while waiting.

I would expect spi_write to be implemented either using busy-waiting (and thus not yield), or using internally an asynchronous implementation plus a wait for poll.

I definitely would not expect spi_write to be implemented any way that is for any reason heavier, or more likely to yield than an actual asynchronous spi_write_signal+poll-based implementation.

**Comment by mondalaci** [comment]
My point is that there's a huge difference between a context switch per 1 vs 1000 bytes.

**Comment by kareltucek** [comment]
I don't argue that. 

I argue that so far I don't see any evidence (or reason) for spi_write_signal to produce any less context switches per byte than spi_write.

As for buffered writes, I don't see why spi_write_signal is relevant, since a (possibly long) buffer can be given to spi_write just as easily as to spi_write_signal.

**Comment by mondalaci** [comment]
You're right. I didn't think this through and may have assumed that sync calls busy-wait. Given your findings, we should keep using the sync read call with large buffers to minimize context switches.

**Comment by kareltucek** [comment]
To be clear, it may be busy-waiting for all I know. (Since the scheduler is preemptive, I don't really know how to test that.)

The important part for the moment is that if we need to switch to the other api, it can be done within writeSpi without changes to its callers.
