### ISSUE TITLE
Eliminate deprecated/experimental symbol warnings

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#840]
@benedekkupper I'd love to get rid of the following build warnings:

```
warning: Deprecated symbol CPLUSPLUS is enabled.


warning: Deprecated symbol LIB_CPLUSPLUS is enabled.


warning: Experimental symbol UDC_DRIVER is enabled.
```

Any ideas how?

**Comment by benedekkupper** [comment]
For sure we have to keep the UDC_DRIVER, and it will stay experimental until zephyr finishes their refactoring of their whole USB stack. I can check how the deprecated symbols can be updated.

**Comment by mondalaci** [comment]
Alternatively, a patch would be welcome in the meantime in https://github.com/UltimateHackingKeyboard/firmware-uhk80/tree/master/device/patches

I want to clean up the build output as much as possible to be able to better focus on the actual errors/warnings.

**Comment by mondalaci** [comment]
@benedekkupper Is there a way to resolve the CPLUSPLUS and LIB_CPLUSPLUS warnings?
