### ISSUE TITLE
Configure clang-format rules, apply formatting on codebase

### ISSUE THREAD

**Issue by benedekkupper** [UltimateHackingKeyboard/firmware#842]
Let's use automatic code formatting, so accidental whitespace changes aren't introduced and the code style is consistent. I have already addded a .clang-format file, this currently only applies to C++ sources. I left the C style out on purpose so you can tailor as you see fit.

How to work with it:
* download and install clang-format
* install clang-format VSCode extension
* add these settings to VSCode settings.json
```
{
...
    "editor.formatOnSave": true,
    "[cpp]": {
        "editor.defaultFormatter": "xaver.clang-format"
    }
    "[c]": {
        "editor.defaultFormatter": "xaver.clang-format"
    }
}
```

**Comment by mondalaci** [comment]
@benedekkupper Would you add your settings (that do not conflict with our coding style)?

Looks like we already have a `.clang-format file in the project root`.  Should we replicate it in settings.json and keep the two in sync to both make the command line utility and vscode happy?

@kareltucek Do you use clang-format? We probably should. If so, will you use the command line utility or vscode?

**Comment by benedekkupper** [comment]
> Looks like we already have a .clang-format file in the project root.

Yes, funnily enough it's many years old and also only targets C++. My settings for C++ are in device/.clang-format, if you are ok with it, we can move that to the root, and add the C settings to it. I don't think you'd be happy with my style being applied on the project, at least the `if` branches having newline everywhere are usually considered too verbose.

>  Should we replicate it in settings.json and keep the two in sync to both make the command line utility and vscode happy?

There's a misunderstanding I believe, the VSCode extension and settings are only a shortcut, running the command line utility on each save in the IDE.

**Comment by mondalaci** [comment]
Please apply your C++ settings in the project root, but only for C++ files.

For C files, https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/master/CONTRIBUTING.md contains our coding standards. You're welcome to add the relevant rules because I'm short on time, but I can do it in the far future.

**Comment by benedekkupper** [comment]
I'm trying to configure clang-format to match the contributing guideline style, however there is one particular style requirement that is not supported, the [header file structure](https://github.com/UltimateHackingKeyboard/firmware/blob/master/CONTRIBUTING.md#header-file-structure)'s "base" indentation. If we want to use auto-formatting, we have to forget about it. In that case the header file structure would look like this:
```
#ifndef __LED_DRIVER_H__
#define __LED_DRIVER_H__

// Includes:

#include "fsl_gpio.h"
...

// Macros:

#define LED_DRIVER_SDB_PORT PORTA
...

// Typedefs:

typedef enum {
    KeystrokeType_Basic,
    KeystrokeType_Media,
    KeystrokeType_System,
} keystroke_type_t;

// Variables:

extern led_driver_state_t LedDriverState;
...

// Functions:

void LedDriver_WriteBuffer(uint8_t i2cAddress, uint8_t buffer[], uint8_t size);
...

#endif
```

**Comment by mondalaci** [comment]
This is an acceptable compromise.
