### ISSUE TITLE
MacOS and NKRO compatibility

### ISSUE THREAD

**Issue by benedekkupper** [UltimateHackingKeyboard/firmware#844]
There's a lot of sources saying that MacOS doesn't support NKRO. Unless we find a working example, we might need to
a) create two keyboard interfaces, one 6KRO and one NKRO
b) switch between 6KRO and NKRO mode the hard way (removing the unused keyboard interface)

Further reading: https://www.reddit.com/r/MechanicalKeyboards/wiki/appleosx_keyboards/

Turs out there's a rather hacky way to detect if the host is a Mac: https://devzone.nordicsemi.com/f/nordic-q-a/61706/usbd_hid_composite-not-working-on-mac

A rather useful thread about MacOS and Fn key that 
https://github.com/qmk/qmk_firmware/issues/2179

**Comment by mondalaci** [comment]
A working example of what? NKRO on Mac?

If NKRO on Mac is not possible, option a) seems like a more flexible option. Does it have any drawbacks?

**Comment by benedekkupper** [comment]
Does the UHK 60 work with the current NKRO firmware on Mac?

**Comment by benedekkupper** [comment]
This was a false premise, mac does work with the bitfield NKRO approach that we use. The problem with macOS is their HID report descriptor parser isn't fully to spec, and we ran into a bug when using an uncommon pattern. Fixed with UltimateHackingKeyboard/firmware-uhk80#33
