### ISSUE TITLE
Dongle connection

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#849]
A NUS connection must be created between the right half and the dongle, in which the dongle is the central and the right half is the peripheral. The relevant files are mostly `bt_{central,peripheral}_uart.[ch]`, which must be extended / replicated.

- The `uhk/addr/dongle` settings key must be used on the right half to store the dongle's address.
- The `uhk/addr/right` settings key must be on the dongle to store the right half's address.

To save battery, the right half should not use more than 2 BLE connections. Consequently, when it's connected to the left half via NUS (as a central) and to a host via BLE HID (as a peripheral), it should not advertise, making the dongle unable to connect to it. Only when the BLE HID connection is terminated, or if it's not created, to begin with, should the right half advertise and accept the dongle's connection. `connected()` and `disconnected()` in `bt_conn.c` should be modified accordingly.

After establishing the connection, the right half must send the reports to the dongle, which should output them via USB.

This issue is quite technical, and we may need to add new Kconfig options to .prj files. Feel free to ask me if you need help.

**Comment by kareltucek** [comment]
Do I understand correctly that this is meant for me?

**Comment by mondalaci** [comment]
Yes. I originally wanted to implement this, but you're pushing it so hard these days that I'd love to delegate it to you.

**Comment by mondalaci** [comment]
Done in recent commits.
