### ISSUE TITLE
Media/System/Consumer pages

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#851]
@benedekkupper do I understand correctly that the "controls_app" / "hid::page::consumer" scancodes correspond to the UHK60 media interface scancodes?

Does it mean that the UHK60 system interface scancodes are not supported?

If I understand incorrectly, how do I map UHK60 media/system scancodes to UHK80 usb subsystem?

**Comment by benedekkupper** [comment]
The controls_app has support for 3 HID page controls:
```
using system_code = hid::page::generic_desktop;
using consumer_code = hid::page::consumer;
using telephony_code = hid::page::telephony;
```
See the respective enumerations for details. Telephony page is added mainly to support microphone mute button.

**Comment by kareltucek** [comment]
Ah, I see, thanks!
