### ISSUE TITLE
BLE HID doesn't connect on Linux

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#854]
To be precise, it momentarily connects and then immediately disconnects.

@benedekkupper Can you connect to a Linux host? I use Linux Mint 21.3, based on Ubuntu Jammy.

**Comment by benedekkupper** [comment]
At the moment I'm not able to pair with my Ubuntu, as the advertisement is not detected. Please send me logs of what's happening on your side.

**Comment by benedekkupper** [comment]
I flashed the `hci_usb` sample on the nRF devkit, and used that as a USB BT dongle on Ubuntu. I get this log when trying to connect to the UHK:
```
Connected to unknown (c6:23:1d:0c:0f:27)
Disconnected from unknown (c6:23:1d:0c:0f:27), reason 5
Advertising successfully started
```
Is this the same what happens to you as well?

**Comment by mondalaci** [comment]
Please see my email on using the same BLE dongle to reproduce such issues.

**Comment by benedekkupper** [comment]
I tried today with the ASUS BLE dongle on Linux, I had no issue.

**Comment by mondalaci** [comment]
After deleting the Bluetooth settings keys and restarting Zephyr, it works with my ASUS USB-BT500 dongle, too.
