### ISSUE TITLE
Mouse and media keys don't work on Android via BLE HID

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#855]
I'm using Android 14.

@benedekkupper Can you reproduce?

**Comment by benedekkupper** [comment]
Yes, Android doesn't show any interest in starting these interfaces at all. My current ideas are either a wrong report descriptor, or Android not supporting multiple BLE HID interfaces.

**Comment by mondalaci** [comment]
How do you plan to resolve this? Experimenting with different descriptors?

**Comment by benedekkupper** [comment]
I now tried not enabling the keyboard, then also the mouse interfaces, and what I saw was that Android always starts only one HID interface. This means that I will need to combine these into a single interface on BLE, while keeping them separate for better USB bandwidth use. Also redesign the HID over GATT protocol handling so it handles parallel input report sending (with different report IDs).
