### ISSUE TITLE
Remaining dongle tasks

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#857]
Currently, the dongle connects to the right half, but only if powering it after the right half is powered. (I'll make the dongle always connect.)

The following must be implemented.
- Make the dongle emit the correct scancodes via USB. Currently, the left-half scancodes are emitted when pressing right-half keys.
- Make the right half send the key events received from the left half to the dongle.

**Comment by kareltucek** [comment]
Any comments on the protocol that should be used?

Who should run user logic? Right half or the dongle?

If master device is going to change, what are the requirements / logic for that?

**Comment by mondalaci** [comment]
The right half will keep running the user logic.

The report passing protocol message format has already been implemented, so the protocol shouldn't be extended for this purpose. However, I'll create an issue with the protocol extension for non-report purposes.

**Comment by kareltucek** [comment]
> The report passing protocol message format has already been implemented

Has it? Where can I find it then? So far I see only sending a bitfield of key states to the dongle.

**Comment by mondalaci** [comment]
Currently, the bit field is the "protocol format." I'd expect a bit field containing the keys of both halves to be sent to the dongle.

**Comment by kareltucek** [comment]
But then the user logic has to run on the dongle, and the devices have to negotiate who is the master.

**Comment by mondalaci** [comment]
You're right. We shouldn't send key states but reports to the dongle.

Please use the related `syncable_property_id_t` values as the first bytes of NUS messages and only resend them upon change to save bandwidth and battery.

See https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/master/device/src/link_protocol.h
