### ISSUE TITLE
UART support

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#860]
If the bridge cable is connected, UART must be used between the halves instead of NUS, which will provide the following benefits:
- Lower latency
- Increased reliability, as wired communication is generally more reliable than wireless.
- More wireless bandwidth for other devices.

See `keyboard/uart.[ch]`. The halves already ping each other in every second. If pinging is successful, NUS between the halves should not be used.

First things first, please study the [async UART API](https://docs.zephyrproject.org/apidoc/latest/group__uart__async.html).

Unlike NUS, UART is purely a byte stream, which doesn't have an abstraction for packets, so an encapsulation must be created for packages on top of the byte stream.

Unless you have a better idea, I suggest using dedicated control bytes, such as:
- 0xFE: End of packet
- 0xFD: Escape the next byte

**Comment by kareltucek** [comment]
Any reason to not just begin a packet by stating the length of the data to be transferred?

**Comment by kareltucek** [comment]
Furthermore, how do I know whether a ble device is connected and whether an usb cable is connected?

**Comment by mondalaci** [comment]
If we prefixed packets with their length, packets can go out of sync once there's a communication error. With dedicated signaling bytes, communication should recover.

How would you branch based on the presence/absence of BLE / USB connections regarding this issue?

**Comment by kareltucek** [comment]
> How would you branch based on the presence/absence of BLE / USB connections regarding this issue?

Well, eventually we will want to send the packets with some interface like
```
void sendPacket(...) {
    if (<uart connected>) {
        <send over uart>
        <if succeeded, return>
    }

    if (<ble connected>) {
        <send over bluetooth>
        <if succeeded, return>
    }

    <report problem>
}
```

**Comment by mondalaci** [comment]
The send calls are already available in `uart.c`, `nus_client.c`, and `nus_server.c`.

**Comment by kareltucek** [comment]
Yes, but how do I know whether the interface is connected? Or should I always try to send packets over *all* possible connections?

**Comment by mondalaci** [comment]
If the bridge cable is connected, `uart_callback()` in `keyboard/uart.c` gets called in every second. The halves already ping each other and dump the ping payload to the console.

**Comment by kareltucek** [comment]
I know. That's why I was asking just about nus and usb.

**Comment by mondalaci** [comment]
Why is USB relevant? The halves can be connected via UART or NUS, not USB.

**Comment by kareltucek** [comment]
Because similar routing logic needs to be applied to whether to send usb reports over NUS (to the dongle) or USB (directly to the computer). (Yes, the question is quite irrelevant to this specific ticket.)

**Comment by mondalaci** [comment]
Please open a separate issue about it and bring up the relevant questions.
