### ISSUE TITLE
Packet routing.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#862]
How do I know whether a nus client and usb are connected?

**Comment by mondalaci** [comment]
@kareltucek As for NUS, my best guess is `connected()` and `disconnected()` of `bt_conn.c`, but it's not quite what you're asking, as NUS connections are more specific than BLE connections. I can't see relevant APIs on the [NUS service](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/bluetooth_services/services/nus.html) and [NUS service client](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/bluetooth_services/services/nus_client.html) pages, so please ask the [Nordic DevZone](https://devzone.nordicsemi.com/).

@benedekkupper Regarding USB, could you help us detect when the UHK 80 is 1) powered via USB and 2) connected to a USB host? We need both callbacks for certain features.

**Comment by kareltucek** [comment]
@mondalaci is it not reasonable to assume that NUS connection has been successfully established if `void NusClient_Setup(struct bt_conn *conn)` encounters no errors?

**Comment by mondalaci** [comment]
It's reasonable, but I'm not entirely sure. Testing the suggested implementation would be prudent, but I don't know how. Feel free to implement it as suggested; if it doesn't work as expected, someone will catch it.

**Comment by benedekkupper** [comment]
I added the `feature/usb-power-state` branch, where print messages inform you of the different power events. You can extend that code snippet by adding your callbacks. Note that the calculated current values are per USB 2.0 spec, it doesn't consider what the USB-C cable negotiates via its CC pins.

**Comment by kareltucek** [comment]
@benedekkupper is there currently a way to detect whether usb is connected in the sense of HID interfaces being active?

**Comment by kareltucek** [comment]
Or more generally, how do I know whether right half should hand reports over to the HID subsystem, or send over NUS to the dongle?

**Comment by benedekkupper** [comment]
For that you can add your callbacks to keyboard_app::start and stop, and query it with keyboard_app::handle().has_transport()

**Comment by kareltucek** [comment]
Thanks!
