### ISSUE TITLE
Make the OLED display connection state between the halves

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#865]
For now, it could display one of the following:
- left:no
- left:uart
- left:nus

Ultimately, I'd like to display this information as a nice status bar icon.

**Comment by kareltucek** [comment]
Do we have some idea of how the main screen should look like? 

Like a sketch or something...

**Comment by mondalaci** [comment]
I have a rough idea of having various status icons at the top and the rest, such as the current keymap, layer, and target, below. But I'm not sure if my original vision will look good on the display.

I'm thinking about building a platform for experimentation for this purpose. A simple JavaScript snippet running on codepen.io and painting on a canvas could work really well. Let me come up with something soon.
