### ISSUE TITLE
Fix flash write error and status reporting

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#868]
User configuration writes error out on the UHK 80, even though they actually succeed:

```
laci@lian:~/projects/agent/packages/usb$ ./write-user-config.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 UserConfiguration.bin 
[UhkHidDevice] Transfer error:  TypeError: Cannot write to hid device
    at file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:126:24
    at new Promise (<anonymous>)
    at UhkHidDevice.write (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:118:16)
    at UhkOperations.sendConfigToKeyboard (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-operations.js:515:31)
    at UhkOperations.saveUserConfiguration (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-operations.js:223:24)
    at file:///home/laci/projects/agent/packages/usb/write-user-config.ts:18:26
    at file:///home/laci/projects/agent/packages/usb/write-user-config.ts:23:3
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
```

I believe it's because writing to the flash of the nRF52840 is much slower than writing to the EEPROM of the UHK 80, so `UsbCommand_LaunchStorageTransfer()` takes so long that by the next USB report, writing is not finished and the report may contain zeros.

`IsStorageBusy` should also be updated, so that USB get device state command would expose pending flash writes for the UHK 80.

**Comment by kareltucek** [comment]
> , so UsbCommand_LaunchStorageTransfer() takes so long

Yes, it takes 1817ms. 

Also, it is synchronous, isn't it? So "**Launch**StorageTransfer" is slightly misleading.

> the report may contain zeros.

UsbCommandId_LaunchStorageTransfer is last in the sequence when executed with write-user-config.ts, so while it may affect agent, it should not affect the quoted error.

> IsStorageBusy should also be updated, so that USB get device state command would expose pending flash writes for the UHK 80.

I am not sure I understand. When should IsBusy be set? 

Since UsbCommandId_WriteStagingUserConfig start until UsbCommandId_LaunchStorageTransfer end?

Or just during UsbCommandId_LaunchStorageTransfer?

In the latter case, isn't it pointless? I mean, I am not sure whether the usb callbacks are reentrant, but I would expect not, in which case I would expect a status command to fail while UsbCommandId_LaunchStorageTransfer is being executed.

------------------

Also, I don't really understand what I should do about this?

**Comment by mondalaci** [comment]
I've just used `--log=all` to understand the cause better:

`./write-user-config.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 --log=all UserConfiguration.bin`

Resulting in:

```
[DeviceOperation] USB[T]: Apply user configuration to keyboard
[UhkHidDevice] USB[W]: 07 
[UhkHidDevice] USB[R]: 00 5f 4a 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[DeviceOperation] USB[T]: Write user configuration to EEPROM
[DeviceOperation] USB[T]: Write Config to Eeprom
[UhkHidDevice] USB[W]: 08 01 02 
[UhkHidDevice] Transfer error:  TypeError: Cannot write to hid device
    at file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:126:24
    at new Promise (<anonymous>)
    at UhkHidDevice.write (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:118:16)
    at UhkOperations.writeConfigToEeprom (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-operations.js:255:27)
    at UhkOperations.saveUserConfiguration (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-operations.js:226:24)
    at async file:///home/laci/projects/agent/packages/usb/write-user-config.ts:18:9
[UhkHidDevice] Device communication closing.
[UhkHidDevice] Device communication closed.
```

I think `Flash_LaunchTransfer()` should return immediately. To make this happen, its processing should be executed in a thread.
