### ISSUE TITLE
OLED layout design

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#873]
I've created an OLED playground on CodePen:
https://codepen.io/mondalaci/pen/gOJmzPm/0fd84aaf27b90175d4779915ec6fa056

![image](https://github.com/UltimateHackingKeyboard/firmware/assets/300402/3da73c7f-8239-4a91-ae04-6dff83e9f5ca)

As we iterate, I'll keep uploading the actual screenshot here so we'll have a nice history.

When opening the page, CodePen doesn't display the icons first. For some reason, I have to edit the code, which can be as simple as adding a space to the JavaScript code. Can you also experience this issue?

I have some concrete ideas, but this should be a good starting point. I'll iterate further today.

**Comment by mondalaci** [comment]
I came up with a design that I think has good usability and aesthetics.

![oled_image (11)](https://github.com/UltimateHackingKeyboard/firmware-uhk80/assets/300402/51de329b-0a9c-45b2-80d8-d54a092a2b2f)

The status bar is a familiar UI element of mobile operating systems. It's an information-dense yet intuitive part of the screen.

The right side of the status part, just as for Android and iOS, contains the battery charge percentages. I've removed the battery icon as it's of no use.

The status bar icons from left to right:
- The wireless icon shows that the keyboard halves are connected via NUS. There will be a separate UART-connected and disconnected icon in place of this icon, depending on the connection state.
- The NKRO icon shows that the current connection to the host uses NKRO. We should use a more readable icon, and I thought of a circle with N inside it. We should default to 6KRO as NKRO incompatibility with KVM switches, BIOSes, and docking stations is a reoccurring user issue.
- The lock icon shows that Caps Lock is enabled.

Some more status icon ideas:
- We should use a "1" icon for num lock.
- I'm unsure whether showing Scroll Lock status is worth it. It's probably unused these days, so I wouldn't show it.
- We can show a gamepad icon if the gamepad interface is enabled.

The first line shows the current keymap and layer name. I wouldn't show the base layer when it's active.

The current target is shown in the second line. This time, the UHK is connected via its left USB port.

---

![image](https://github.com/UltimateHackingKeyboard/firmware-uhk80/assets/300402/4eb0160e-4632-4814-b8f1-32aafcbbe868)

The batteries are being charged on this screen, hence the `+` signs after battery percentages instead of `%`.

I hand-edited the layer name to be underlined here, which I believe has better aesthetics and better use of space than underscores on its ends. I wouldn't use a colon between the keymap and layer name as on the first screenshot of this thread because it doesn't look clean, and it'd only be used for non-base layers.

The current target is a dongle here with a matching icon and name.

---

![oled_image (1)](https://github.com/UltimateHackingKeyboard/firmware-uhk80/assets/300402/f21454f2-33e2-473a-9b00-0a1893029b5b)

Here, the target is an Android phone via BLE HID with the relevant Bluetooth icon. Target names will be editable except for USB targets.

Your feedback is welcome.

**Comment by kareltucek** [comment]
I find meaning of many of the icons unintuitive. I also find it rather cluttered. I would find it aesthetically more pleasing if things were centered.

Specific ideas (more of a brainstorm than well thought-through ideas):
- Make the status bar texts/icons smaller - like 8 or 10 font size, to make it look more like an actual phone status bar. 
- Center the remaining two lines somehow. (Just for aesthetics.)
- I am not sure that full keymap name is a good idea - multiple separate words make the display more cluttered and make it hard to distinguish keymap from layer, furthermore prevent us from centering the text as keymap name requires more than half of the display. So:
  - Maybe show just the abbreviation after all?
  - Separate layer from keymap somehow - maybe just center layer within the right half of the display and keymap within the left half?
- Show caps lock, num lock and scroll lock as a group, maybe separate from other indicators. Just gray out those that are inactive. Not sure where though. Maybe center it in the status bar, but I am not sure by that... (*very* not sure by this)
- I would experiment with making the target text smaller font size and centering it.
- As for aesthetics, I would replace L and R with a small character-wide vertical battery icon. (Making it fill depending on current charge shouldn't be very hard.)
- I would show even base layer.

**Comment by mondalaci** [comment]
We should have a way to transfer the generated images to the display to get a better feel for how they look on it. Would you implement a relevant USB command? Robert will write a command-line utility in the agent80 repo.

Then, we should experiment with your ideas and finalize the design.

**Comment by kareltucek** [comment]
I am not sure how?

Is the legacy USB code functional?

**Comment by kareltucek** [comment]
I am also wondering if experimenting with them directly on the UHK might be more efficient after all? 

If you create a custom widget, you can write custom drawing code in the draw function. Text drawing supports both vertical and horizontal allignment so you don't need to finetune text position by hand after every change. The only issue is missing icons, and that flashing takes long.

**Comment by mondalaci** [comment]
I've used the USB commands on the UHK 80 to transfer the configuration, so they're functional.

I'd rather use my web playground as it allows for quicker iteration, at least for me. And I still have to deal with much to release the UHK 80 besides firmware. But feel free to prototype in other ways.

**Comment by kareltucek** [comment]
Sure, will implement it tomorrow!

**Comment by kareltucek** [comment]
How do I exec a generic command against uhk 80? I tried following (similarly to writing user config), but it didn't trigger usb_protocol_handler at all.

```
/opt/agent/packages/usb/send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 21 0 0 8 0 255 0 255 0 255 255 255
```

@ert78gb this may be relevant to you?

**Comment by mondalaci** [comment]
The referenced command should work. The following commands worked for me when tried them:

```
# get device state
./send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 9

# get property config sizes
./send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 0 2

# read eeprom to ram
./send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 8 0 2
```

**Comment by ert78gb** [comment]
What is the output of your command @kareltucek ?

**Comment by kareltucek** [comment]
Interesting, nevermind then, it has to be a problem on my end.

> What is the output of your command @kareltucek ?

UsbStatusCode_InvalidCommand, which correlates with other evidence that suggest that I must have messed up flashing correct firmware 🤦.

(Laszlo's commands work fine for me, so this is clearly not Agent's fault.)

**Comment by kareltucek** [comment]
Actually, it was dongle usb that was responding to the commands :-).

Anyways, solved.

**Comment by kareltucek** [comment]
Some draft of mine. 

The idea is to arrange the icons according to groups of relevance: left half (and its connection to right half) on the left, keyboard state things in the middle, right half (and its connectio nto pc) on the right.

Irrelevant numLock / capsLock texts would be grayed out. 

Some icons would be filled in (either added, or replacing some texts), but I don't think that necessarily all should be - I find NmLk an CpLk more descriptive than icons...

![oled_image](https://github.com/UltimateHackingKeyboard/firmware-uhk80/assets/3447497/b4013d07-35c0-41d3-a0d3-8d40164c2aee)

**Comment by mondalaci** [comment]
The left USB port will also be usable for data connection, so the suggested spatial arrangement can be misleading.

I agree that text is more descriptive than icons, but text occupies too much space when many states are shown, and once one is familiar with icons, I think they're easier to recognize in the long term.

We have yet to see whether the center arrangement works. It should be tested on an assembled UHK, so that the display is in its final environment.

**Comment by kareltucek** [comment]
> The left USB port will also be usable for data connection

Please explain. Will it be used for anything but firmware updates and charging?

**Comment by mondalaci** [comment]
Yes. The hardware of the left USB port is just as capable as the right USB port, and we should eventually make it work like the right USB port, including sending USB reports and making Agent usable via it. However, this is not a priority.

When the target is the left USB port, properties should be synchronized/routed accordingly.

**Comment by kareltucek** [comment]
So right half will still be master (thus leading to poor latency for gamers that may want to use only the left half), or will we have to be able to switch left to be the master?

**Comment by mondalaci** [comment]
Ideally, it'd make sense to make the halves able to switch roles when justified and make the left the master eventually, but it'd cause high complexity, so I think it's very low priority.

Regarding the large scheme of things, it may be better to make the halves talk [via the dongle](https://www.slicemk.com/pages/split-dongle) to preserve battery life, but this is very low priority, and I'm not sure it's worth the effort as we have huge batteries, and the right battery is much larger than the left one.

**Comment by mondalaci** [comment]
Closing this issue, as the layout is already pretty good. Will iterate further from now on in individual issues.
