### ISSUE TITLE
NUS ready state.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#874]
Currently, if a message is sent over NUS right after the connection is established, the message is lost. It takes around 0.5s for the NUS connection to actually start working

Possible ways forward:
- Currently, we wait one second after connection is established with sending any messages. This is more of a temporary solution.
- Find a way to figure out whether nus connection is ready.
- Implement a handshake - when connection is established, send a ping every 50ms until both halfs confirm each other receiving the pings. Then start using the connection normally, with no more pings.

**Comment by mondalaci** [comment]
There should be a cleaner way to use a callback when the NUS connection is ready. Please ask the Nordic folks unless you have a better idea.

**Comment by kareltucek** [comment]
(Raised at https://devzone.nordicsemi.com/f/nordic-q-a/111767/when-is-nus-ready )
