### ISSUE TITLE
Update power source on boot

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#875]
The power source variable, which describes whether the UHK 80 is USB-powered or battery-powered, is only updated from a callback when it changes. Its default value is USB-powered, even when the UHK 80 is battery-powered. As a result, UltimateHackingKeyboard/firmware-uhk80#97 is partially implemented.

We should update this variable on firmware startup with the actual value.

**Comment by benedekkupper** [comment]
Unfortunately zephyr's USB udc.h API doesn't expose any call to find out the current power state of the USB peripheral, therefore we cannot do anything trivial on our side, we need nordic's help here.

From a quick read through the code first, I found out that the VBUS related events don't even originate from the USBD peripheral, but from the NRF POWER peripheral. So maybe there is an existing interface for polling the VBUS state through a power related API, but that needs further research.

What I did find is a register for reading this status directly from the silicon, in 5.3.7.5 chapter of the [reference manual](https://infocenter.nordicsemi.com/pdf/nRF52840_PS_v1.0.pdf). So a code like this should be able to tell you the initial status (include nrfx.h for the needed symbols):
```
if ((NRF_POWER->USBREGSTATUS & POWER_USBREGSTATUS_VBUSDETECT_Msk) == POWER_USBREGSTATUS_VBUSDETECT_VbusPresent) {
            printk("USB power available\n");
        }
```
Please check if this code gives you good result or not. If yes, then at least we can confirm that the HW is suited to do this detection.

This is not at all portable though, so we'll need to get a proper zephyr API for this on the long term.

**Comment by mondalaci** [comment]
@kareltucek Please implement Benedek's suggestion and make the OLED display show the left and right power sources. Regardless of whether the above API works, please ask Nordic about the proper Zephyr API and let's use it in the final code.

**Comment by mondalaci** [comment]
@kareltucek Please make this a priority as I'm worried that power source detection doesn't work reliably in which case we may have to modify the schematic. We must finalize the electronics as soon as possible.

**Comment by kareltucek** [comment]
> Please check if this code gives you good result or not.

So far this seems to give good results. 

I have incorporated it in our code so that it is updated with battery updates and when your power_event_delegate reports state changes. For most practical purposes this satisfies our needs, but on top of portability issues, if I am not mistaken, the power_event_delegate may not trigger if I connect UHK into a dumb DC power source, so in that case we don't get actively notified, so it would be nice to get called by zephyr core when the state changes instead of having to actively check it from our side.

On the other hand, the above code is just a simple memory read (isn't it?), so while it is not a clean solution, we could just update it from the key_scanner every millisecond or so.

@mondalaci what is your opinion on this?

**Comment by mondalaci** [comment]
How can I make the firmware ignore my configuration to use `DefaultCfg` for testing purposes?

**Comment by kareltucek** [comment]
Flip `bool factoryMode` in main.c to true.

**Comment by mondalaci** [comment]
The `DisplayBrightnessBatteryDefault` and `KeyBacklightBrightnessBatteryDefault` values are used, even though USB is connected to the haves.

right: CHARGER_EN: 1 | STAT: 0 Battery is present: 1, charging: 1, at 4180mV (100%)
left: CHARGER_EN: 1 | STAT: 0 Battery is present: 1, charging: 1, at 4260mV (100%)

When UART is connected between the halves, this is a non-issue. Can you reproduce?

**Comment by kareltucek** [comment]
Well, are both your halves powered according to the OLED display?

Current logic is such that if either half is not powered, then both halves are behaving as if running on battery, and the behavior is managed from the right half.

**Comment by mondalaci** [comment]
Then this must be due to UltimateHackingKeyboard/firmware#983.

**Comment by kareltucek** [comment]
I suspect so.

**Comment by benedekkupper** [comment]
There are two ways we can get the power status information, either via polling (reading this register bit periodically), or by interrupts. Now, for the latter, we could hijack the API from under the USB stack, it just needs to be initialized after the USB stack is done. These are the calls needed (from nrfx_power.h):
```
void nrfx_power_usbevt_init(nrfx_power_usbevt_config_t const * p_config); // init with the callback pointer
void nrfx_power_usbevt_enable(void); // enable interrupts that trigger callback
void nrfx_power_usbevt_disable(void);
void nrfx_power_usbevt_uninit(void);
```
So you can see if hijacking this callback gives you any more info than hooking into the USB power event callback. If not, then we are stuck with the polling approach.

I also found that there is a wrapper to the register reading, so prefer to use this, still not portable, but at least one level higher: `nrfx_power_usbstatus_get()`
