### ISSUE TITLE
Dongle pairing

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#877]
This issue contains both the firmware-side and Agent-side specifications for dongle pairing. Separating the two would make it more difficult to understand the process as a whole.

1. Agent is connected to a UHK 80 and reads its configuration.
2. Agent detects that a dongle gets connected and reads its `dongleAddress`, which is its own BLE address, and its `dongleKeyboardAddress`, which is the address of the keyboard paired to it. Expose these two addresses via the getDeviceProperty USB command.
3. Agent computes `isDonglePaired` = hostConnections contains a connection with dongleAddress and type==dongle and also check dongleKeyboardAddress == keyboardAddress.
4. If isDonglePaired is false, Agent displays a yellow notification bar at the top containing "A dongle is detected. [Pair it] with this keyboard." - Clicking on the "Pair it" link initiates the following pairing procedure.
5. Agent calls the to-be-implemented `pairDevice` USB command on the dongle and the keyboard. The command has a target argument, which is a uint8 enum, and an address argument containing the target's BLE address. The target enum can represent the right keyboard half, the left keyboard half (not used in this issue), or a dongle. Make the dongle keep using the `uhk/addr/right` settings key, but don't use the `uhk/addr/dongle` settings key on the keyboard anymore as a host connection item will be used.
6. The connection must be established and secured. Securing the connection is akin to using the `uhk btacc 1` shell command, and similar API calls should be used, but [in this case](https://devzone.nordicsemi.com/f/nordic-q-a/110895/factory-pairing-two-nrf52840), out-of-band pairing should be used for securely exchanging the 16-byte OOB key via USB. Unlike when pairing BLE hosts, the pairing OLED screen must not appear for dongles.
7. Use a dedicated `pairingIsInProgress` bit in the response of the getDeviceState USB command, which Agent will poll and display a progress indicator until the pairing completes.
8. Expose the result of the pairing as a new uint8 enum of the getDeviceState USB command. I guess the result can be success or failure.
9. If pairing succeeds, Agent saves the configuration with the new host connection added to the end of the existing host connections. The name of the new connection is "Dongle". Agent jumps to the connection page and hides the top notification.
10. If pairing fails, Agent updates the top notification: "Dongle pairing failed. [Retry pairing] with this keyboard."

**Comment by kareltucek** [comment]
> 3. Agent computes isDonglePaired = hostConnections contains a connection with dongleAddress and type==dongle and also check dongleKeyboardAddress == keyboardAddress.

Strictly, this doesn't tell that they are bonded. This only tells us that they know each other's addresses, but not whether oob keys were exchanged.

But I would wait with this until we have some basic Agent implementation and just then talk about what it means for us and what we should do about it.

> but don't use the uhk/addr/dongle settings key on the keyboard anymore as a host connection item will be used.

~~I would keep using it for simplicity. The filters will be fed from both `uhk/addr/dongle` and from the host connection array. `uhk/addr/dongle` will always contain the last paired device.~~

Edit: Maybe no. 

~~Given usecases below, lets ditch it on both right and on the dongle.~~

Edit2:

Well, lets keep to the above specification for the moment.

> 7. Use a dedicated pairingIsInProgress bit in the response of the getDeviceState USB command, which Agent will poll and display a progress indicator until the pairing complete

A bit, or a new (fulll byte) bool? If a bit, which one exactly?

> 8. Expose the result of the pairing as a new uint8 enum of the getDeviceState USB command. I guess the result can be success or failure.

Again, a whole new byte for it?

> 9. If pairing succeeds, Agent saves the configuration with the new host connection added to the end of the existing host connections. The name of the new connection is "Dongle". Agent jumps to the connection page and hides the top notification.

This is vague when it comes to sharing a config among multiple keyboards.

------------------

Assume I have 2 uhks - one at home, one at office, and I have a single dongle permanently inserted in the laptop, that share a single config.

In this case, I want one shared config that contains that one dongle.

I want the dongle to be paired to both the UHKs.

This means that 2 doesn't work at all, as the Agent will be trying to re-pair them every time I connect carry the laptop between home and office

------------------

Now assume that 2 uhks share a single config, but each is paired to a different dongle. 

In this case, I definitely want to save the config even when one of the dongles is not paired.

-----------------

The way I see it, the only way to know if they are bonded is to explicitly ask the dongle if it has a bond to the other device.

So unless you protest, I am going to implement a new command that does this. (I.e., takes an address and tells whether it has the bond.

**Comment by kareltucek** [comment]
Alright, the above proposal is broken, as we need a list of addresses for scanning to be available on the dongle :-/.

So I guess let's continue with a single bond dongle for the moment, although I will implement the command to check bonding.

**Comment by mhantsch** [comment]
What are the use cases for Dongles?

- single Dongle with 1 single UHK
- several Dongles (at different PCs: home, office, office 2...) with 1 single UHK (user carries the UHK around)
- single Dongle (plugged into a Laptop) with several UHKs (user owns several UHKs for home, office, office 2... but carries the Laptop around)
- several Dongles with several UHKs?

**Comment by kareltucek** [comment]
Some random thoughts:

- Given the above, it would be somewhat more convenient if right half was the central (nus client) for both the nus links. 

- On the other hand, the nus (at least at the moment) has good bandwidth properties only in the server -> client direction.

**Comment by rogermeletta** [comment]
> What are the use cases for Dongles?
> 
> * single Dongle with 1 single UHK
> * several Dongles (at different PCs: home, office, office 2...) with 1 single UHK (user carries the UHK around)
> * single Dongle (plugged into a Laptop) with several UHKs (user owns several UHKs for home, office, office 2... but carries the Laptop around)
> * several Dongles with several UHKs?

For me personally, it would be nice to have one Dongle connected to my laptop and a wired connection via USB to my Desktop PC (and maybe a Bluetooth connection to my phone), along with a way to switch back and forth via keypress (like in ZMK):

There you have for example multiple Bluetooth profiles: https://zmk.dev/docs/keymaps/behaviors/bluetooth
(and you can also switch between Bluetooth and USB)

**Comment by kareltucek** [comment]
That will definitely be possible, but will take some time to implement...

**Comment by mondalaci** [comment]
When there are multiple hosts without BLE transceivers but with USB ports to be connected, multiple dongles can be useful, providing a wireless KVM switch, so I consider this a worthy use case.

I made the dongle the central because scanning takes more power than advertising, so I think it's the right choice from a power optimization standpoint.

I'd certainly not consider the "single dongle to multiple UHKs" case at this point because it largely complicates this already complex issue. For now, let's make the dongle store one bond. Other related issues exist, like multiple UHKs competing for the same dongle in the same space. We must focus on the basic use case (which is not so basic, considering how few keyboards support multiple dongles); otherwise, implementing this issue will take forever.

7. Only a bit. It's important to minimize the payload of getDeviceState as it's regularly called. Eventually, HID packet will consist of multiple commands, making such optimizations useful.

8. Sorry, I meant getDeviceProperty here, and a uint8 as a result. I'm unsure whether there will be multiple error codes or just a success/failure.

**Comment by kareltucek** [comment]
> 7

But which one?

Should I restructure existing data, or allocate it in a new byte?

**Comment by mondalaci** [comment]
The latter. The MSB of https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/fd3e67f86f979a765e75f5eca24ffe9f74adc443/right/src/usb_commands/usb_command_get_device_state.c#L37 would make a good candidate.
