### ISSUE TITLE
Make pinging module bootloaders always work

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#88]
Right now, pinging module bootloaders only works sporadically, and the user often has to [retry a couple of times](https://github.com/UltimateHackingKeyboard/agent/commit/b6bdd1486c7619019e6f241b59bb6c9a960a8aca#diff-6441fe89f23ff287fa12dc35a8ef3746R12). I think chances are good that the bootloader or BusPal is quirky in some ways. We should make it more stable.

**Comment by Lauszus** [comment]
I have actually solved this as well. I have simply modified blhost, so it pings the device three times before giving up. I have some other fixes as well. I can push them to a separate repository if you want?

**Comment by mondalaci** [comment]
Please push your blhost fix to the [bootloader repo](https://github.com/UltimateHackingKeyboard/bootloader) where blhost lives.

**Comment by Lauszus** [comment]
Please see: https://github.com/UltimateHackingKeyboard/bootloader/pull/11.

**Comment by mondalaci** [comment]
This does not seem to be an issue anymore.
