### ISSUE TITLE
Small status bar font

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#882]
The battery `%` characters are especially hard to read, but the general issue is that the status bar font is too small. A larger font would be a better choice.

**Comment by kareltucek** [comment]
Well, I wanted to increase it to 10, but unfortunatelly, I had not generated 10 size, and they had reworked the lvgl converter, and the new exports don't work 😭.

**Comment by mondalaci** [comment]
If you don't have a better idea, please ask them how to recover the converter and whether they can provide a solution.

**Comment by kareltucek** [comment]
Well, I am changing the size to 12 for now, and will see if I can make the new format work...
