### ISSUE TITLE
Don't display "n/a" when a battery is not present

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#883]
The UHK 80 will be buyable without batteries. Showing "n/a" for such customers wouldn't be useful and would only increase the chance of OLED burn-in, so let's not display battery status for them.

**Comment by kareltucek** [comment]
Not sure if its worth the trouble now since the statusbar line will need almost complete remake... but given changes in UltimateHackingKeyboard/firmware-uhk80#124 , feel free to suggest new format to also show when halves are powered...
