### ISSUE TITLE
hid connection target?

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#884]
@benedekkupper I would like to know (i.e., get called) whenever the "HID target service" changes. 

(If I understand things correctly, keyboard_app::stop/start are called for any hid connection - usb and hogp alike. I would like to distinguish them.)

Purpose is to show who is receiving usb reports (e.g., "usb cable", "bluetooth hid device", "uhk dongle", "my android phone"...).

Can you give me some pointers please?

**Comment by mondalaci** [comment]
It'd be worth mentioning some related code, so that Benedek could help you more effectively.

**Comment by kareltucek** [comment]
Well, lets say that I want something like either of the following interfaces getting called when the hid packet routing changes.
```
enum { HidTarget_USB, HidTarget_Hogp, HidTarget_None };
void HidTargetChanged(hid_target_t t);
```
or
```
void HidConnectionStateChanged(connection_t* con, bool active);
```
or whatever is relevant with respect to the internal function of c2usb.

**Comment by benedekkupper** [comment]
Please check the feature/hid-transport branch.
