### ISSUE TITLE
When only one battery is present, show which one

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#888]
When a single battery is present, prefix its charge value with `L` or `R` on the OLED display. This should seldom be an issue in practice, but when it is, it makes debugging easier.

**Comment by kareltucek** [comment]
Thery are now shown in fixed position: left as `100%     ` , right as `     100%`.

In the light of the above, does your request stand? (Aesthetically I find it a step back, but as you wish.)

**Comment by mondalaci** [comment]
Yes, I still believe it'd be useful, as the edge of the display is not always clearly visible, and the length of the keymap name can vary wildly, so it can't be used well as a general reference point.

I think my suggestion doesn't hurt aesthetics, and the prefix letters would only be used when a single battery is present, which is rare.

When a single value is shown, please right-align it even if it's for the left battery.

**Comment by kareltucek** [comment]
Ah, I see, ok!

**Comment by mondalaci** [comment]
Lxx% is displayed, but Rxx% is not displayed when only the right battery is connected.
