### ISSUE TITLE
Right half battery detection problem

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#889]
If the right half battery shows 100% and I unplug its battery, it keeps showing 100%. Can you reproduce?

`CHARGER_EN: 1 | STAT: 1 Battery is present: 1, charging: 0, at 4162mV (100%)`

**Comment by kareltucek** [comment]
Well, your keyboard is still powered via JLinks, so the charger and stat oscillation doesn't kick in. Is this correct?

I thought this was a known "problem" that we don't care about since it is development-only.

**Comment by mondalaci** [comment]
The left half is powered by a charger, and the right half is powered by a USB hub, so it's a real-life use case.

**Comment by kareltucek** [comment]
Allright, what does the statlog say?

**Comment by mondalaci** [comment]
Regardless whether I disconnect the right battery, I get:

left: CHARGER_EN: 1 | STAT: 1 Battery is present: 1, charging: 0, at 4166mV (100%)
right: CHARGER_EN: 1 | STAT: 1 Battery is present: 1, charging: 0, at 4142mV (100%)

**Comment by mondalaci** [comment]
STAT doesn't oscillate.

**Comment by kareltucek** [comment]
Yes, I can reproduce it, but given that stat doesn't oscillate, I consider it a hardware issue.

If there is anything I can do about it, please let me know.

**Comment by mondalaci** [comment]
I can't seem to solve this issue, but it should be a corner case that only occurs during development. It only occurs if the right battery is fully charged, the right half is powered via USB or the bridge cable (in the bridge cable case, the left half is powered via USB), and the right battery gets disconnected. If the right battery is disconnected upon firmware startup, the issue doesn't surface.

I'm closing this issue.
