### ISSUE TITLE
The dongle doesn't work

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#891]
According to the Zephpyr console, the dongle and the right half connect, but the right half doesn't send reports to the dongle anymore. Looks like a regression.

**Comment by kareltucek** [comment]
I cant reproduce this?

**Comment by mondalaci** [comment]
Are you making a statement or asking?

**Comment by kareltucek** [comment]
I am making a statement, but also expressing an uncertainty about any special steps that may be needed to make this problem exhibit and that you may have forgotten to mention.

**Comment by mondalaci** [comment]
The right half is in disconnected state. It doesn't matter whether the halves are connected via NUS or UART. Then plug in the dongle, and the two are connected via BLE. "UHK Dongle" appears on the OLED as the target, but the reports are not sent.

Right half:
```
NUS and HID advertising continued
Scan module initialized
NUS Client module initialized
Scanning successfully started
Reading hardware config
Reading user config
Applying user config
User config applied
W: opcode 0x200a status 0x0d
Connected to dongle (d5:82:81:0d:e5:96)
Failed to set security for dongle (d5:82:81:0d:e5:96): -12
Stop LE scan failed (err 0)
MTU exchange done with dongle (d5:82:81:0d:e5:96)
Service discovery completed
```

Dongle:
```Start scan                                                
Filters matched: right (d0:af:1e:df:98:3b), connectable:1 
Scan connecting: right (d0:af:1e:df:98:3b)                
Filters matched: right (d0:af:1e:df:98:3b), connectable:0 
Connecting failed: right (d0:af:1e:df:98:3b)              
Connected to right (d0:af:1e:df:98:3b)                    
MTU exchange done with right (d0:af:1e:df:98:3b)          
E: pairing failed (peer reason 0x8)                       
Security failed: right (d0:af:1e:df:98:3b), level 1, err 9
Service discovery completed                               
```

**Comment by kareltucek** [comment]
Still seems to work fine.

**Comment by mondalaci** [comment]
`E: pairing failed (peer reason 0x8)`

Maybe this is the culprit. Any insights/ideas?

**Comment by kareltucek** [comment]
No, except https://chatgpt.com/share/2f59f96f-6af9-4850-b734-ebe607a2ef1a and of course asking nordic folks...

**Comment by mondalaci** [comment]
Reflashed the dongle, deleted all key-related settings values of all peers, and now it works.
