### ISSUE TITLE
Sending USB commands

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#895]
The following command previously worked for me, but now, it doesn't:

```
# get device state
./send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 9
```

Results in:

```
[UhkHidDevice] Transfer error:  TypeError: Cannot write to hid device
    at file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:126:24
    at new Promise (<anonymous>)
    at UhkHidDevice.write (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:118:16)
    at file:///home/laci/projects/agent/packages/usb/send-command.ts:15:35
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
TypeError: Cannot write to hid device
    at file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:126:24
    at new Promise (<anonymous>)
    at UhkHidDevice.write (file:///home/laci/projects/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:118:16)
    at file:///home/laci/projects/agent/packages/usb/send-command.ts:15:35
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```

@kareltucek Does it work for you?

**Comment by kareltucek** [comment]
Indeed no command seems to work.

**Comment by mondalaci** [comment]
Gotta be a regression. Please look into this and make it a priority. I need to test the enumerate as bootloader command.

**Comment by kareltucek** [comment]
Well, bisecting shows c1581c469d7c335ee1629d1268ba82ebeed43786 as the first bad commit. 

Since traces lead into the internals of c2usb, I would rather leave this to @benedekkupper .

It seems like the set_report of the command_app isn't called at all most of the time.

In other words, most up-to-date master commit that works is 3462b70d404c93396767fe6e5e73a71b34cbc106

**Comment by kareltucek** [comment]
(I.e., the merge of android-full-compat into master has introduced this in master.)

**Comment by mondalaci** [comment]
@benedekkupper Please make this a priority.

**Comment by benedekkupper** [comment]
I added a report ID, so the payload size shrunk by 1 byte to 63 now. Can you adjust that on your side?

**Comment by mondalaci** [comment]
@benedekkupper We had no other way to achieve compatibility across OSes, right?

@kareltucek Please update the codebase accordingly.

**Comment by kareltucek** [comment]
@benedekkupper , what exactly needs adjusting?

(Randomly decreasing 64s and 63s found in the codebase doesn't fix the problem.)

**Comment by benedekkupper** [comment]
Ah, the agent side scripts need to be all updated, to have the report ID on the first byte (and to limit the payload size to 63 from the previous 64). See report_ids.h for the command report IDs.

**Comment by mondalaci** [comment]
@ert78gb Please implement the suggested change in the agent80 repo.

**Comment by kareltucek** [comment]
@benedekkupper just adding the 4 as the first byte of the regular payload still doesn't solve the problem:

```
$ ./execUhk80.sh send-command.ts 4 9
executing /opt/agent/packages/usb/send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 4 9
Error: Communications error with UHK. Response code: undefined
    at file:///opt/agent/packages/uhk-usb/dist/src/uhk-hid-device.js:132:35
```

(The above script allows us to send a custom payload - 4 9 in this case, and writes out the result.)

(@mondalaci does benedek have access to this repo? Not sure if above tag reaches him...)

**Comment by mondalaci** [comment]
@kareltucek I just invited Benedek to the agent80 repo (via the UHK 80 team) and moved this issue back to the firmware-uhk80 repo.

**Comment by mondalaci** [comment]
@benedekkupper Please comment on how we should proceed. (I'm mentioning you because you might not have received Karel's message while this issue was in the agent80 repo.)

**Comment by kareltucek** [comment]
Well, you are adding an id to the response too, don't you? In that case I guess the agent script checks for a global success response code on the first byte instead of just writing out the response (as it should) and therefore breaks down. 🤦

@ert78gb can you please look into it?

The send-command script should write out response as it is without doing any validity checks.

Furthermore, it would be nice if agent **always** printed out the actual response bytes instead of "undefined" whenever it encounters something it doesn't expect. (This applies to in-app error codes too. We are often left with a user's screenshot that just shows a totally unhelpful "undefined".)

**Comment by ert78gb** [comment]
Honestly I don't know why this way implemented the communication, but this is how works with the old firmware.
The https://github.com/UltimateHackingKeyboard/agent/blob/d479153817a134878fdd3f2853f2d1e9f11190a4/packages/uhk-usb/src/uhk-hid-device.ts#L174 method responsible to send data to the firmware.

The [getTransferData](https://github.com/UltimateHackingKeyboard/agent/blob/d479153817a134878fdd3f2853f2d1e9f11190a4/packages/uhk-usb/src/util.ts#L50) function convert the 64 byte `buffer` data to USB 'datagram'. You can see it is append `0` to the beginning of the array. I think it is the report id of the data package. So we send 65 bytes.

The https://github.com/UltimateHackingKeyboard/agent/blob/d479153817a134878fdd3f2853f2d1e9f11190a4/packages/uhk-usb/src/uhk-hid-device.ts#L187 reads the USB response. It is the "raw" data that the keyboard sends.

In the https://github.com/UltimateHackingKeyboard/agent/blob/d479153817a134878fdd3f2853f2d1e9f11190a4/packages/uhk-usb/src/uhk-hid-device.ts#L191 I check the first byte of the response is `0` or not.
In the past if it was not `0` then it was an error.  

The referenced error message `Communications error with UHK. Response code: undefined` contains the first byte of the response. In this case the first byte is `undefined` this is the reason of the undefined after the `Response code: `

Agent uses synchronous write and read Line 187 waits 1 second to the response. My assumption is the response did not arrived in 1 sec.
The earlier version of the `node-hid` library supported only sync operation. It had `data` event but it did not worked very well. So this read operation was enough stable. 
`node-hid` 3 introduced the async operations but it was bogus. The 3.1.0 that has been released 2 weeks ago maybe fixed all async issues.

Honestly I don't catch what should I change. I guess I have to use non `0` value in the https://github.com/UltimateHackingKeyboard/agent/blob/d479153817a134878fdd3f2853f2d1e9f11190a4/packages/uhk-usb/src/util.ts#L50
am I right?
If yes could you define when what value should set. I mean the old framework/keyboard will use always 0 and the new framework/keyboard will use the non 4 value.
Currently I don't really know how could differentiate the different cases.

**Comment by kareltucek** [comment]
Allright, thanks @ert78gb! I did some more investigation:
- I have increased the agent timeout to 10 seconds, and getting the same results, just after a much longer wait
- I have added prints into the firmware:
    - When I send message 4 9, the correct handler is called in the firmware.
    - When I do that via the send-command.ts script, it takes multiple seconds for the firmware printline to actually print.
    - When I execute the same command by just writing into the hidraw device, I get the printline instantly.

Furthermore, I have attempted to write the command directly via hidraw, and obtain reply directly via hidraw.
E.g.:
```
DEVICE="/dev/hidraw2"

timeout 3 cat $DEVICE | hexdump &

echo "Using device $DEVICE"
echo -e "\x4\x9" > $DEVICE
```

For UHK60, I am getting the answer.  
For UHK80, I am not.

Would you look into it @benedekkupper?

**Comment by ert78gb** [comment]
I tried to make Agent be compatible with the new UHK 80, but I can't manage it alone. I need someone help to describe protocol. If I read well the thread @benedekkupper will be that person :)

My assumption is the firmware does not write any response message, maybe it wait for the end of the communication byte(s) or something like that. The result is same as Karel's bash script.

## Facts
Have to use the 4 report id to be able to send message from Agent to firmware. If I use other than 4 as report Id then the write operation to the firmware will break and I can't write again until I restart the keyboard. I removed the battery and unplug and plugged the USB cable for the restart.

If I send more than 64 byte data in 1 write operation the it is failed.

I don't get any response from the firmware if I send exactly 64 byte data (fill the end of the array with 0) or send only the "main data"

## Simple tool
For faster iteration/testing the https://github.com/UltimateHackingKeyboard/agent80/pull/10 PR contains the `packages/usb/send-command-80.js` file. It uses the `node-hid` I provided more example how we could communicate with the firmware. It does not use the whole Agent ecosytsem so you don't have to rebuild the project every time when you change something. It is a simple js file so it must work always just run `node packages/usb/send-command-80.js`.
Every parameter is hardcoded, so feel free to modify.

I think the classic write and readTimeout should work in every case. It is the `Method 3` in the file.

**Comment by kareltucek** [comment]
Allright, this is on me after all. 

Pushed fix straight into master, it should communicate now.

**Comment by mondalaci** [comment]
Please provide an example Agent command that works with master.

**Comment by kareltucek** [comment]
```
agent80/packages/usb$ ./send-command-80.js 9
write: 4 9
read 5 second timeout
data:  [
  4, 0, 0, 0, 0, 0, 0, 0, 1, 5, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0
]
```

**Comment by kareltucek** [comment]
Or 
```
/opt/agent/packages/usb/send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 4 9
Error: Communications error with UHK. Response code: 4
```
with standard uhk60 agent for that matter.

Except here applies:

> The send-command script should write out response as it is without doing any validity checks.

**Comment by ert78gb** [comment]
if you run the usb scripts with `--log=all` then it prints the write and read bytes to

**Comment by ert78gb** [comment]
confirmed the new firmware communicates with the Agent.

**Comment by ert78gb** [comment]
I alway get empty response.

command: `./packages/usb/send-command.ts --log=usb 0 1` it should return with the protocol versions
returns: `04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00`

```bash
❯ ./packages/usb/send-command.ts --log=usb 0 1
[UhkHidDevice] USB[W]: 04 00 01 
[UhkHidDevice] USB[R]: 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Byte result:
4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

String result:
```

**Comment by kareltucek** [comment]
Well, are your versions defined in `shared/versions.h`? 

(At the moment, scripts/generate-versions-h.mjs generates 0 md5sums and 0 versions, which is pretty inconvenient. Ideally, it should be refactored so that without parameters it it generates 0 md5sums, but otherwise valid data, and then two options should be added `--withZeroVersions` and `--withMd5Sums`. And of course make-release adjusted accordingly.)

Otherwise I need to do some testing and as to that, I am confused - on which branch are you running this?

**Comment by mondalaci** [comment]
I've built Robert's UHK 80 firmware. I've just provided the app_update.bin file of the right half to him. I don't want Robert to deal with firmware builds and instead want him to focus on Agent. Let me make a new build for him.
