### ISSUE TITLE
Bootloader not visible as hid device

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/firmware#900]
Reproduction
- connect the UHK-80 right half with USB cable to the computer
- build the https://github.com/UltimateHackingKeyboard/agent80/pull/10 agent
- run the `npm run electron -- -- -- -- --log=all --print-usb-devices` It wil print every available usb hid device
- use the reset button of the keyboard. it will enumerate the bootloader
- run the `npm run electron -- -- -- -- --log=all --print-usb-devices` It should print the bootloader, but it not visible.

I tried it on linux and mac

**Comment by mondalaci** [comment]
The bootloader is not a HID but a DFU device. Feel free to reopen or comment.
