### ISSUE TITLE
Invalid deviceProtocolNumber

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/firmware#901]
- build the https://github.com/UltimateHackingKeyboard/agent80/pull/10 agent
- run the `./packages/usb/get-right-firmware-version.ts`. It should print the version numbers

I got a firmware from Laci
[uhk-firmware-11.1.0-c9f9f05b.tar.gz](https://github.com/user-attachments/files/15928099/uhk-firmware-11.1.0-c9f9f05b.tar.gz)

it prints 
```
firmwareVersion: 2816.256.0
deviceProtocolVersion: 1024.2560.0
moduleProtocolVersion: 1024.768.0
userConfigVersion: 1792.256.0
hardwareConfigVersion: 256.0.0
smartMacrosVersion: 512.1024.768
```

There are 2 thing in my mind. The edian encoding changed or the structure changed.

**Comment by mondalaci** [comment]
@kareltucek Please make this a priority.

**Comment by kareltucek** [comment]
@mondalaci sure, please provide instructions on how I can produce new firmware images for Robert.

**Comment by mondalaci** [comment]
@kareltucek Simply by running `scripts/make-release.mjs --allowSha`.

**Comment by kareltucek** [comment]
Ah, I see, I have to be in zephyr shell...

**Comment by kareltucek** [comment]
I guess the endianness chaned. But even after fixing it (in firmware), the scripts provide weird results:

uhk80:
```
(bell)me@L490:/opt/agent80/packages/usb$ ./get-right-firmware-version.ts
firmwareVersion: 3.0.0
deviceProtocolVersion: 0.0.0
moduleProtocolVersion: 0.0.0
userConfigVersion: 0.0.0
hardwareConfigVersion: 0.0.0
smartMacrosVersion: 0.0.0
(bell)me@L490:/opt/agent80/packages/usb$ ./execUhk80.sh send-command.ts 0 1
executing /opt/agent80/packages/usb/send-command.ts --vid 0x1d50 --pid 0x6125 --usb-interface 2 0 1
Byte result:
4 0 0 11 0 1 0 0 0 4 0 10 0 0 0 4 0 3 0 0 0 7 0 1 0 0 0 1 0 0 0 0 0 2 0 4 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

uhk60:
```
me@L490:/opt/agent/packages/usb$ ./get-right-firmware-version.ts
firmwareVersion: 11.0.0
deviceProtocolVersion: 4.10.0
moduleProtocolVersion: 4.3.0
userConfigVersion: 7.0.0
hardwareConfigVersion: 1.0.0
smartMacrosVersion: 2.4.0
me@L490:/opt/agent/packages/usb$ ./send-command.ts 0 1
Byte result:
0 11 0 0 0 0 0 4 0 10 0 0 0 4 0 3 0 0 0 7 0 0 0 0 0 1 0 0 0 0 0 2 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

String result:
```

Also, I am unable to flash uhk60 for some reason:
```
me@L490:/opt/foo/right/uhk60v1$ make flash
/bin/sh: 1: ../../lib/agent/node_modules/.bin/tsx: not found
make: *** [../../scripts/Makedefs.mk:191: flash] Error 1
```
Any ideas?

Here is firmware release:
- [uhk-firmware-11.1.0-a2f46463.tar.gz](https://github.com/user-attachments/files/15931564/uhk-firmware-11.1.0-a2f46463.tar.gz)

**Comment by ert78gb** [comment]
Did you run npm install? Looks like the tax package is missing

**Comment by kareltucek** [comment]
Npm install _where_?

I have ran it in scripts and lib/agent. I may have tried some other locations too, but got errors there. ~~Also, I find that between the agent and agent80 repo, there is some mismatch as to the required npm and node versions, but that is not a big issue.~~ Edit: Actually I guess the problem is maybe in firmware-uhk80 repo having outdated versions.

**Comment by kareltucek** [comment]
Uh, sorry, I think I have messed up above - the above is unified to big endian, while Agent I now believe expects little endian. The uhk80/.../get-right-... script still outputs 3 0 0 0 ..., although send-command scripts report data that look correct.

As to flashing, solved. Git submodules sometimes behave pretty non-intuitively. I changed the submodule's remotes incorrectly, and then thought I had reverted that change by deleting the submodule and reinitializing again 🤦.

Here is a little endian build: [uhk-firmware-11.1.0-fdd17447.tar.gz](https://github.com/user-attachments/files/15934088/uhk-firmware-11.1.0-fdd17447.tar.gz)

**Comment by ert78gb** [comment]
> Actually I guess the problem is maybe in firmware-uhk80 repo having outdated versions.

I upgraded few dependencies, but I will merge the agent into the agent80 repo.

use npm install in the root folder of the git repo.

yes agent uses little edian encoding like the old firmware :)
