### ISSUE TITLE
OLED left half connection display

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#902]
I think the current OLED layout is very good and almost production-ready, but I dislike the connection display of the left half, which currently features one of the following:
- `---`
- `left: bt`
- `left: uart`

Instead I'd use the following Font Awesome icons. The left-side icons have regular style, and right-side icons have sharp style.

unconnected: circle-xmark icon

![image](https://github.com/UltimateHackingKeyboard/firmware/assets/300402/3eeeaf2f-fa49-4391-ad96-91e3f5080685)

BLE: signal-stream icon

![image](https://github.com/UltimateHackingKeyboard/firmware/assets/300402/c511d91a-c47b-42c2-b54a-734ee28e27c0)

UART: plug icon

![image](https://github.com/UltimateHackingKeyboard/firmware/assets/300402/331debb5-c49b-4af4-8018-eef86f0c96d5)

I'm drawn to the sharp style, although I'm unsure which would look better on the OLED.

Alternatively, we could use the `-`, `B` and `U` characters, but I think they're less intuitive.

**Comment by kareltucek** [comment]
Above icons require the Pro plan, and I believe the license provided is valid only for the length of the subscription. Given this, can you provide either the relevant font files, or a plan "seat" as they call it?

**Comment by mondalaci** [comment]
Just sent you the access via email.

**Comment by kareltucek** [comment]
Done by UltimateHackingKeyboard/firmware-uhk80#171
