### ISSUE TITLE
Icon glitch

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#905]
My icon glitched over time. Can't explicitly reproduce it yet.

![IMG20240624162415](https://github.com/UltimateHackingKeyboard/firmware/assets/300402/3f8537f9-d858-4b9e-846c-2829b27ab9fe)

**Comment by kareltucek** [comment]
Have you checked out fresh master? I was additionally pushing a fix that may have fixed this. (If I am right, then the icon glitches when the left half is connected.)

**Comment by mondalaci** [comment]
I'm unsure which revision I've been running, but just pulled master, flashed it, and I'll be watching for this issue.

**Comment by kareltucek** [comment]
Closing this as I believe it is already fixed. Reopen jf it reappears.

**Comment by mondalaci** [comment]
Fixed by UltimateHackingKeyboard/firmware-uhk80#275.
