### ISSUE TITLE
Merge state reporting is broken

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#911]
GetDeviceState always reports an unmerged state, even when merging the UHK 60 or UHK 80.

**Comment by kareltucek** [comment]
If I read the code correctly, in uhk80, merge sensor is in left half only. _Why_?

**Comment by kareltucek** [comment]
Also, how exactly do you envision getting the information to the right half? Does it mean I will have to set up a timer in left half that will periodically test whether the halves are merged and sync the data to the right half?

**Comment by mondalaci** [comment]
> If I read the code correctly, in uhk80, merge sensor is in left half only. Why?

Because I originally envisioned the left half to be the master.

> Also, how exactly do you envision getting the information to the right half? Does it mean I will have to set up a timer in left half that will periodically test whether the halves are merged and sync the data to the right half?

Yes, exactly.
