### ISSUE TITLE
Bluetooth connection settings keys

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#917]
When connecting to BLE hosts, the connection often gets momentarily established and then disconnected. In such cases, after deleting the settings keys and rebooting the firmware, the connection works. The connection should work without this procedure.

**Comment by mondalaci** [comment]
Reproduction steps:

1. Pair your UHK with an Android phone.
2. Unpair your Android phone.
3. Try to pair your UHK to an iPhone. You should get connected and immediately disconnected.
4. Assuming that `01:23:45:67:89:AB` is your Android phone's address, run the following in the Zephyr shell:

```
settings delete bt/keys/0123456789ab0
kernel reboot cold
```

5. Now, you should be able to connect your iPhone.

@benedekkupper Please look into this issue. Having the `bt/keys/${address}` value of a device in the settings shouldn't prevent another device from connecting.

**Comment by benedekkupper** [comment]
So when a new pairing is about to happen, if the settings are full, drop the last used previous stored link key to make the pairing happen without error?

**Comment by mondalaci** [comment]
My settings partition shouldn't be full. I have merely a half dozen short keys on the entire 8K partition.

You can check free space [this way](https://devzone.nordicsemi.com/f/nordic-q-a/111040/maximum-settings-partition-size-estimation/488955). The last time I checked, it was plentiful.

Can you reproduce the issue?

**Comment by benedekkupper** [comment]
I have started a [discussion](https://github.com/zephyrproject-rtos/zephyr/discussions/75859) on this topic for now.

**Comment by mondalaci** [comment]
If you don't get a reply soon, I suggest posting to https://devzone.nordicsemi.com/ instead because it has way higher activity, and Nordic support engineers reply quickly. They're very familiar with Zephyr, and some/many of them are Zephyr contributors.

What's exactly the root cause of the issue? I don't quite get it.

**Comment by benedekkupper** [comment]
See the outcome of the discussion: https://github.com/zephyrproject-rtos/zephyr/discussions/75859
We need to enable at least `CONFIG_BT_KEYS_OVERWRITE_OLDEST`. Additionally, using `BT_KEYS_SAVE_AGING_COUNTER_ON_PAIRING` will increase flash wear, but it will make the overwriting more accurate, since it will update the aging counter on each reconnect.

**Comment by mondalaci** [comment]
@benedekkupper Thanks! I paired my UHK 80 with all five devices, and pairing worked as expected.
