### ISSUE TITLE
Include the user configuration into merged.hex

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#922]
See https://devzone.nordicsemi.com/f/nordic-q-a/113047/mapping-a-binary-file-to-a-flash-partition/495228 for the details.

Attached is [config.bin.zip](https://github.com/user-attachments/files/16394767/config.bin.zip) which contains the user configuration for testing purposes.

@benedekkupper You are by far the most experienced team member regarding this issue, specifically CMake, so I assign this to you.

**Comment by benedekkupper** [comment]
How do I find out at what address this config.bin content should be loaded to?

**Comment by mondalaci** [comment]
Here: https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/b2f0aa6e193cf8dd87231496de259d9f20d194cb/boards/arm/shared.dtsi#L87

**Comment by benedekkupper** [comment]
After another try with also no results, I posted my progress to the mentioned forum discussion, let's hope they can tell us something useful.

**Comment by mondalaci** [comment]
@benedekkupper Please open a private issue on Devzone, hoping one of them will take it seriously.

**Comment by mondalaci** [comment]
Closing this issue, as it's no longer needed due to how we factory-flash the firmware.
