### ISSUE TITLE
MCUboot DFU should only wait after hardware reset and bootloader jump

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#924]
Since the `CONFIG_BOOT_USB_DFU_WAIT=y` Kconfig option was added to `mcuboot.conf`, MCUboot always times out.

MCUboot should only time out when:
- the UHK was hardware-reset via its reset button
- when it's reenumerated by the application firmware, which uses `bootmode_set(BOOT_MODE_TYPE_BOOTLOADER); sys_reboot(SYS_REBOOT_WARM);`

@benedekkupper Can you modify `0001-Always-enter-serial-recovery-mode-upon-startup.patch` accordingly? The current patch makes MCUboot behave as desired but doesn't expose the DFU USB interface.

Please handle this issue as a priority.

**Comment by benedekkupper** [comment]
FYI I can only pick this up after 8th Sept, we are in vacation times now...

**Comment by mondalaci** [comment]
I ended up removing `CONFIG_BOOT_USB_DFU_WAIT` because it's unneeded. The timeout works as intended, so I'm closing this issue.
