### ISSUE TITLE
USB sleep and wake issues

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#927]
We need a callback for the USB wake event.

We also need a way to wake the host after it sleeps.

**Comment by benedekkupper** [comment]
I created `feature/usb-sleep-wake` branch as a starting step. The callback is just restoring what was removed in UltimateHackingKeyboard/firmware-uhk80#157, then there's the `USB_RemoteWakeup` call to bring the system back from suspend.

**Comment by kareltucek** [comment]
Well, I am not sure if this from your side is considered a work in progress, or done...

But in the latter case, how do we know that the host has put itself to sleep? (I.e., we received the `kUSB_DeviceEventSuspend` or something similar.)

**Comment by mondalaci** [comment]
@benedekkupper I also have some questions/requests.

1. If you want us to test something, please always create a PR. My workflow is optimized for PRs, so this would help a lot.
2. Please provide some context. Like Karel, I also have no idea whether this is a work in progress and what your implementation strategy is, considering this is the "starting step".
3. The related code was removed in UltimateHackingKeyboard/firmware-uhk80#157, which made power status information available. I'd assume that reverting this change would make power status information unavailable. Please elaborate on this.

**Comment by benedekkupper** [comment]
> Well, I am not sure if this from your side is considered a work in progress, or done...
> 
> But in the latter case, how do we know that the host has put itself to sleep? (I.e., we received the `kUSB_DeviceEventSuspend` or something similar.)

Since I have no idea about the overall FW design, nor was I given instructions where to integrate these functionality, I did what I could, that is give an entry point interface. If you want me to provide a full implementation, I need to know what to call in case of suspend and wake up events, and where to place the remote wakeup call.

**Comment by kareltucek** [comment]
> I did what I could, that is give an entry point interface

That's fine and thanks for it!

I am just requesting more information:

- I don't understand what the point of the empty power callback is. 
- Apart from waking up the host, we need to be able to recognize that the host has been suspended. Old firmware did it here: https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/ab8436eacf09ee4167352e435ff17b5e9c14e016/right/src/usb_composite_device.c#L212 .  If your branch contains a solution for this, then I haven't understood it (and that's also the reason why I am confused). If the old power callback is a solution to this problem, then what values indicate the suspend event?

It suffices to put an explicit comment or a printk at the sites of the suspend/wake calls, and I will take care of the rest.

**Comment by benedekkupper** [comment]
I updated the callback with some TODOs that I think are the necessary actions, don't hold back any further questions.

**Comment by kareltucek** [comment]
@benedekkupper can you please elaborate on this?

```
                    // TODO: stop battery charging, maybe only if dev.configured(),
                    // to distinguish between USB host and charger
```

I am not catching what battery charging has to do with the suspend state.

**Comment by benedekkupper** [comment]
> I am not catching what battery charging has to do with the suspend state.

The point of the suspend signalling is to put the USB device (the UHK) into a very low power consuming mode. If we still pull power for charging the battery out of the USB port, then we are violating the USB spec big time.

The tricky part is that USB chargers don't communicate on the USB data lines at all, which can mislead the USB peripheral into thinking that there is a suspend condition.

**Comment by kareltucek** [comment]
I see.

I guess another catch are powered usb hubs - as a user, I would expect the device to continue charging, but according to what you say, we should stop

**Comment by benedekkupper** [comment]
Maybe we will need to introduce a user configuration value that defines behavior in these ambiguous situations.

**Comment by mondalaci** [comment]
I like the idea of a "charge while suspend" user configurable variable, but when it's enabled, wouldn't we violate the USB spec according to the above?

**Comment by kareltucek** [comment]
Anyways, back to the original problem.

@benedekkupper it may have got lost in the discussion, but (on Laszlos Windows) the power_delegate seems to return data that just correspond to neither the sleep state of the host, nor the uhk60 implementation.

**Comment by benedekkupper** [comment]
Can we close this?

**Comment by kareltucek** [comment]
I think so.
