### ISSUE TITLE
Key cluster unmapped after firmware boot until configuration save

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#928]
After firmware bootup, the keys of my key cluster module function as if they were assigned to none actions, even though they aren't.

After I save my configuration in Agent, my key cluster keys behave according to their actual mappings, which are visible in Agent.

**Comment by mondalaci** [comment]
I put my PC to sleep for the night, woke it up, and my key cluster keys became unmapped. Re-saving my configuration in Agent fixed it, at least temporarily.

@kareltucek It's a significant usability issue. Any ideas about its cause?

**Comment by mondalaci** [comment]
This has just happened again. I'll monitor the Zephyr log and hope to see a related log line.

**Comment by kareltucek** [comment]
> @kareltucek It's a significant usability issue. Any ideas about its cause?
> 

Yes, and no worries, I will fix it.

**Comment by mondalaci** [comment]
This issue is not fully resolved yet. If the halves are connected and I press the reset button, the key cluster is unmapped after the bootloader timeouts.

**Comment by kareltucek** [comment]
Please retest and provide more detailed reproduction instructions.

I have the right half connected and powered via usb. Battery is disconnected. Left half is connected via the bridge cable.  I press right half's reset button, wait for the reboot to complete and tap the keycluster buttons. They work fine.

**Comment by mondalaci** [comment]
This issue seems to have been resolved. I haven't experienced it recently, and I can't reproduce it anymore. Closing it.
