### ISSUE TITLE
Windows 11: USB device not recognized

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#936]
When running uhk80-master on my UHK 60 v2, and Windows 11 tells me that the "USB device not recognized".

I restored the revision just before we changed the USB vendor ID, but it didn't make a difference.

Bisecting is very time-consuming due to various build errors and build-related issues, such as versions.h

When reverting to the latest official release, my UHK 60 v2 works on Windows, but only after downgrading user configuration by resetting it with Agent.

@kareltucek Do you have a Windows machine to reproduce and fix this?

**Comment by kareltucek** [comment]
Well, I have an almost clean Windows in dualboot on this machine, with no development environment or other tools. (I am using it as a fancy tool to upgrade laptop firmware...)

I can test whether the machine is affected, but I don't think I can efficiently deal with this issue.

I guess Benedek should have knowledge and tools to debug this without having to bisect this?

**Comment by kareltucek** [comment]
Anyways, this is probably caused by addition of the serial number that I did in june.
