### ISSUE TITLE
leftControl and leftShift are not working together

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#937]
I am trying to copy something from my terminal window. The shortcut for this is Ctrl+Shift+C.

I cannot copy if I use leftControl+leftShift+C. This will ignore leftControl and only input an uppercase *C*.

Any other combination will work correctly:
* leftControl+rightShift
* rightControl+rightShift
* rightControl+leftShift

The only combination that does not activate both Control+Shift is if I use both on the left side.

I've reproduced this after reseting the config to default.

**Comment by mhantsch** [comment]
And of course it's the same behaviour for Ctrl+Shift+V (paste)...

**Comment by kareltucek** [comment]
Interesting, will look into it!

**Comment by kareltucek** [comment]
Well, I  have resetted the config, but everything works fine. (Testing with https://keyboardchecker.com/ .)

**Comment by mondalaci** [comment]
I can't reproduce this either.

@mhantsch Please close all fancy keyboard manipulation software that may interfere and try to reproduce this.

**Comment by mhantsch** [comment]
Happens even when I stop Kanata. And why was this never an issue with my UHK60? And not when I type on the Laptop keyboard -- that goes to the same "fancy keyboard manipulation software"....

**Comment by mondalaci** [comment]
Well-rounded arguments :)

Please flash the latest firmware version, provide its link, and I'll try to reproduce it again.

**Comment by mhantsch** [comment]
```
Right keyboard half firmware: UltimateHackingKeyboard/firmware-uhk80: 11.1.0 #f651595
Left keyboard half firmware: UltimateHackingKeyboard/firmware-uhk80: 11.1.0 #f651595
Key cluster firmware: UltimateHackingKeyboard/firmware: 11.1.1  11.1.0
Touchpad is detected, and its firmware is implemented by the right keyboard half.
```

From here: https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/10984249681

Reset config, issue still occurring.

**Comment by mhantsch** [comment]
This may have to do with it: when I alt-Tab I can go forward by holding leftAlt and tapping Tab, but when I try to go backwards by also holding leftShift then it doesn't work. However, it works when I use rightShift.


So, while holding down leftAlt:
- Tab advances forward through the list of windows
- leftShift+Tab doesn't do anything
- rightShift+Tab advances backward through the list of windows

Something's weird with my leftShift!

**Comment by kareltucek** [comment]
Well, I would try the usual "weird behavior" troubleshooting:
- reseating the switches (pull out, bend the contacts a little, push back again)
- go through relevant steps of https://ultimatehackingkeyboard.com/repair/fixing-misbehaving-keys . Especially disconnect left module, disable backlight, try battery-powered operation, try usb-powered operation.

**Comment by mhantsch** [comment]
I don't think it's a connectivity issue with the switch (or I would have intermittent other faults with that shift key), but I'll do some checks over the next days. Disconnecting the left module (keycluster) made no difference.

**Comment by mhantsch** [comment]
Which other keys are on the same column in the keyboard matrix as leftShift? Could this be a wrong diode (= hardware issue)? I played with this issue a little, and it seems my leftShift is not recognised if typed together with any of the leftmost keys: leftControl, CapsLock, Tab, graveAccentAndTilde (and I'm not sure about Escape).

**Comment by mondalaci** [comment]
@mhantsch Thanks so much for your report! You made me realize that there's a schematic error affecting the ISO layout. This requires a minor PCB modification, and the affected PCBs can be reworked. I'll provide instructions regarding your PCB and contact testers with ISO UHKs.

**Comment by mhantsch** [comment]
So the current ISO UHK80 is "N-1" key rollover 😏 

Glad you found the cause!

**Comment by mondalaci** [comment]
Closing this issue in favor of https://github.com/UltimateHackingKeyboard/firmware/issues/951 which contains the fix.
