### ISSUE TITLE
fn-Tab mapped to alt-Tab doesn't release leftAlt when using holdLayer macro command

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#938]
`Tab` key is assigned to `leftAlt`+`Tab` on the *fn* layer.

A macro is assigned to the 'Fn' key and contains:

```
holdLayer fn
```

When I try to Alt-Tab through my windows using `Fn`+`Tab`, everything works until I release the keys. Then, leftAlt seems to be kept held down because the window list still stays there. If I briefly tap `Fn` (or `leftAlt`) then the list closes and the active window actually switches.

This is my previous setup from the UHK60. There it would release leftAlt when I let go of `Fn`.

**Comment by mondalaci** [comment]
@mhantsch Please test https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11128040138

**Comment by mhantsch** [comment]
@mondalaci I can confirm that this issue has been resolved with UltimateHackingKeyboard/firmware-uhk80: 11.1.0 #d01a9bb (the build you asked me to test).
