### ISSUE TITLE
shift gets held when using layered shifted key

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#943]
Bind this macro to rightSpace:

```
holdLayer fn4
```

On layer *fn4*, configure a key to send scancode `= +` with modifier LShift.
Save config.

Click with your mouse in a text editor somewhere in the middle of a text. Leave the mouse there.

Now hold rightSpace and press the key. Let go of all keys. You should get a **+** typed into your text.

Now use your mouse (real mouse, NOT UHK mouse!) to click somewhere else in the text. I can see that the text between your first click and this click gets selected, so it's a Shift-select. Click a few more times and see that the LShift is being held.

**Comment by mondalaci** [comment]
@mhantsch Does https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11145849044 resolve this issue?

**Comment by mhantsch** [comment]
As far as I can see, this one issue is indeed resolved in this build (UltimateHackingKeyboard/firmware-uhk80: 11.1.0 #790a47c).
