### ISSUE TITLE
Touchpad none actions in default configuration?

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#944]
The touchpad tap didn't register (not even after UltimateHackingKeyboard/firmware-uhk80#268) until I explicitly saved the configuration in Agent.

This suggests to me that the default configuration doesn't include the touchpad configuration, and the firmware uses none actions.

It'd be worth checking this issue for every module.

**Comment by kareltucek** [comment]
What do you mean by "default configuration"? Factory keymap in keymap.c, or something else?

**Comment by kareltucek** [comment]
Anyways, keymap.c contains the actions allright.

**Comment by kareltucek** [comment]
@mondalaci there is still this, which I suspect has the same cause as UltimateHackingKeyboard/firmware#928 ;

I too have experienced something similar, although it was that functional colors reverted to default, which should never happen (at least on the right half).

**Comment by mondalaci** [comment]
I've just reproduced this issue by removing the touchpad module, resetting the configuration in Agent, and attaching the touchpad module. Tapping didn't do anything.

**Comment by kareltucek** [comment]
Sorry! I thought  I did, but clearly I have tested just a weaker version of the same problem.  

Default UserConfig flashed by Agent indeed doesnt contain right module settings. But that's Agent's bug.

This PR still fixes a weaker version of the same problem - the one in which a valid config is flashed. (The rest of instructions remains the same.)

**Comment by ert78gb** [comment]
I tested uhk60 with the released Agent and "click" action of the touchpad does not work.

The Agent's default user config contains only left and right halves values. Agent extend the user config with module specific config when user connects a module to the half. 
If I remember well the reason is save space. I could change this behaviour if you want

**Comment by mondalaci** [comment]
I think saving space is a legit reason, and I'd expect the firmware to use the default config as hardcoded values if a module configuration is missing.

@kareltucek Can you implement this, too?

**Comment by kareltucek** [comment]
Allright.
