### ISSUE TITLE
uhk-60 firmware is not responding to usb communication command on Mac and Windows

### ISSUE THREAD

**Issue by ert78gb** [UltimateHackingKeyboard/firmware#945]
Reproduction
- Start the Agent80
- Connect uhk60 v2 to the computer
- Upgrade the firmware with [uhk-firmware-11.1.0-29a1fed.tar.gz](https://github.com/user-attachments/files/17119259/uhk-firmware-11.1.0-29a1fed.tar.gz)
- On windows or on Mac only the right half will be flashed, because the keyboard not responding any USB communication command. Only the Bootloader reenumeration works. So can't flash the left half.

If you have an UHK60 with the new uhk80 firmware and run the `./packages/usb/get-debug-info.ts --log=all` usb script you can see `00 0b` has been sent to the keyboard and not arrived any byte within the 1 second read timeout. (I set 5 sec read timeout, but did not help)

I don't experience any issue on linux. Agent could communicate with the keyboard and `./packages/usb/get-debug-info.ts --log=all` also working.

Laci also experiencing the same.

FYI: I am experiencing it from the beginning, but I thought the new firmware has not support the uhk60 yet, but Laci said the new firmware is uhk60 compatible.

The `./packages/usb/update-device-firmware.ts ./tmp/packages/firmware/devices/uhk60v2-right/firmware.hex` command flashes the uhk60 keyboard with the bundled firmware.

**Comment by kareltucek** [comment]
Is UHK60 recognized under Windows?

We've had a similar problem caused by addition of the serial number. Windows was picky about either its format or length, and wouldn't recognize UHK60. But on the referenced firmware, this should already be fixed.

**Comment by ert78gb** [comment]
Yes uhk60 recognised under windows. I can type it works as a keyboard.

The `--print-usb-devices` lists all usb interface and the serial number field has value.

Agent can open the USB communication and can send message but never got response

**Comment by rpnfan** [comment]
Oh, that is a bummer. I just made some updates to my UHK60, which need to be undone, because they did not work as expected...  Any idea how to fix the issue? I might get access to a Linux machine, but my son just deleted his Linux this morning and I do not use Linux any longer.

Edit: tried to reset the UHK60 and then connecting via the current Agent 4.2 release (public). That did not work.

**Comment by mondalaci** [comment]
@rpnfan Please try [unbricking](https://ultimatehackingkeyboard.com/knowledgebase?q=unbrick) your UHK 60 with the official Agent.

@kareltucek Should we bisect the firmware to see where it went wrong?

**Comment by kareltucek** [comment]
I guess the problem is still the serial number.

**Comment by mondalaci** [comment]
Just bisected this. The offending commit is c9f9f05b.

Would you fix this?

**Comment by mondalaci** [comment]
@benedekkupper Please help with this and make it a priority. We don't know the solution.

**Comment by kareltucek** [comment]
I will have a look...
