### ISSUE TITLE
Mod key sticking with firmware sha 8d79620

### ISSUE THREAD

**Issue by nazmulidris** [UltimateHackingKeyboard/firmware#947]
# Repro steps:

Create the following key binding for the Mod key.
![image](https://github.com/user-attachments/assets/fcd8efd7-230b-4134-96f3-d4ec68705b11)

Save it to agent.

When typing Mod+j, for eg, the Mod key sticks. This makes it very difficult to use. Pressing the Mod key without any 2ndary keys works just fine.

# Expected behavior

The Mod key should not be sticky. I have to press Mod again to release the Mod layer in order for the keyboard's base layer to be active again.

# Similar issue with Mouse layer
A similar behavior happens with the Fn key, when it is configured as such:
![image](https://github.com/user-attachments/assets/d9748662-026d-420b-bf1c-c98848bf7e93)

When doing a Fn+key combo, the layer sticks.

**Comment by mondalaci** [comment]
Thanks for reporting! I can reproduce this issue.

**Comment by nazmulidris** [comment]
@mondalaci Ok awesome! I can't wait to try out the updated firmware w/ this fix in it (whenever it is ready). Since this is preventing me from using the epic UHK80 as my daily driver 😄

**Comment by mondalaci** [comment]
@kareltucek This issue is still unfixed. It takes 2 to 7 taps to activate the Enter primary role.

**Comment by kareltucek** [comment]
🤨

Can't reproduce it (pulled and flashed fresh master, then tested with secondary roles bound to spaces in default config; tested with bindings on both halves). 

Please reflash&retest, or provide more detailed reproduction instructions, or send your UserConfig.

**Comment by mondalaci** [comment]
Sorry, my bad! I completely forgot to account for the timeout set. Works great!

@nazmulidris Please confirm that it's fixed.

**Comment by nazmulidris** [comment]
I just flashed the new firmware and it works! The mod, fn, mouse keys no longer stick (when they are in the secondary role).

![image](https://github.com/user-attachments/assets/6166960f-4e48-461b-b605-262918685e4c)

I can now use this keyboard as my daily driver! :) 

Thank you! 🎉
