### ISSUE TITLE
Backlight property changes don't propagate to left half

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#948]
1. Change the backlighting mode in Agent from functional backlighting to per-key backlighting.
2. Notice the right half changing key colors but not the left half.

Originally reported by @jwr.

**Comment by mondalaci** [comment]
Also, when changing the key backlight brightness (both USB-powered and battery-powered), it doesn't sync to the left half.

**Comment by rogermeletta** [comment]
Syncs occur whenever the halves are connected or disconnected via the spiral cable, or when the USB cable of the left half is plugged or unplugged.
