### ISSUE TITLE
Treat the OLED USB-powered when the right half is USB-powered

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#949]
The current logic is that both halves must be USB-powered for the UHK to be considered USB-powered. In practice, this means:
- USB-powering the right half and using the bridge cable, or
- USB-powering the left half and using the bridge cable, or
- USB-powering both halves (doesn't matter whether the bridge cable is used)

The above behavior is sensible to always keep the key brightness of the halves consistent.

But this logic shouldn't apply to the OLED display. Let's treat it USB-powered when only the right half is USB-powered, regardless of whether the left half is USB-powered.

Reported by @jwr.

**Comment by kareltucek** [comment]
Alright, that sounds sensible!
