### ISSUE TITLE
UHK 80 ISO hardware issue affecting early units

### ISSUE THREAD

**Issue by Zetaphor** [UltimateHackingKeyboard/firmware#951]
OS: NixOS 24.05 & Windows 11
Agent: CI build UltimateHackingKeyboard/firmware#900 from [5aaef90](https://github.com/UltimateHackingKeyboard/firmware-uhk80/commit/5aaef90251c36c6eed32c2f5ad0232cedffc9062)
Firmware: CI build UltimateHackingKeyboard/firmware#887

I'm unable to use shift with the backtick key in this layout:
![image](https://github.com/user-attachments/assets/b1b2344b-f145-4fb5-95e3-fbb9579720b0)

`SHIFT + 1` works and produces an exclamation point, but `SHIFT + backtick does not produce tilde

I can type use the backtick key without the shift modifier, so I know it's not a switch issue

**Comment by mondalaci** [comment]
This is probably a duplicate of UltimateHackingKeyboard/firmware#937, a newfound hardware issue. Can you solder? If not, we can recall your UHK 80 and fix it.

**Comment by Zetaphor** [comment]
Unfortunately I don't have any equipment for soldering as I'm in a small apartment, so I'll likely have to go the recall route 😞

**Comment by Zetaphor** [comment]
What is the level of difficulty with the repair? If it's a simple bodge wire I could consider picking up a solder pen.

However if it's something more complex that would require something more (as I lack experience) then I'll have to move forward with a recall

**Comment by mondalaci** [comment]
This fix should be easy.

![image](https://github.com/user-attachments/assets/2b6f6bd8-26c3-4eaf-b8cc-b44df0a04f1f)

- Cut the track along the red line with an X-Acto knife
- Connect the pads with a bodge wire along the blue line

I recommend the TS80P soldering iron.

Can you fix this, or should we recall your UHK?

**Comment by Zetaphor** [comment]
Oh perfect, I can handle this. I'll get everything ordered tonight. Thanks!

**Comment by Zetaphor** [comment]
I'm going to make this fix today. @mondalaci would this issue also be why I can't seem to CTRL+SHIFT+Any key?

**Comment by mondalaci** [comment]
@Zetaphor Assuming you're using the left shift, yes.

**Comment by Zetaphor** [comment]
This isn't going to win any beauty contests, but despite my subpar soldering skills this fixed it. Thanks!

![20240929_155139](https://github.com/user-attachments/assets/233ce6d9-0458-49e9-8633-aaf704cb721c)

**Comment by mondalaci** [comment]
Well done! Thanks for fixing it!

**Comment by mhantsch** [comment]
Let me join the repair crew:

![IMG_20241004_175435](https://github.com/user-attachments/assets/739aaa93-73e0-4b2c-9992-2297188d874b)
![IMG_20241004_173721](https://github.com/user-attachments/assets/5089958e-f3fb-4531-991e-6843b517df29)

I can confirm this solved UltimateHackingKeyboard/firmware#937.

**Comment by mondalaci** [comment]
@rogermeletta Just so you know, your UHK is also affected by this issue.
