### ISSUE TITLE
Dongle - Long typing macros are sending incomplete or out of order

### ISSUE THREAD

**Issue by Zetaphor** [UltimateHackingKeyboard/firmware#952]
I have a macro setup for a sequence I have to type regularly. When using the dongle I'm noticing that it's inconsistent in its ability to send fully and correctly. Sometimes it's typing characters out of order, other times it's missing characters, and then sometimes it's correct.

**Comment by mondalaci** [comment]
Closing as a duplicate of UltimateHackingKeyboard/firmware#1000.
