### ISSUE TITLE
Stuck modifiers

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#953]
@jwr reported

> When I use keys that are defined to generate a scancode with modifiers, like in the attached image, pressing that key results in modifiers being stuck for mouse clicks.
> 
> E.g. after I press the button, subsequent mouse clicks act as Shift-Command-mouseclick, until I press left shift or left command once, which gets the modifiers un-stuck. Verified in Safari and Emacs.
> 
> The modifiers are not stuck for keyboard presses, e.g. if I press 'q' right after the custom key, I get 'q', not Shift-Command-q.
> 
> This is on MacOS 14.7, firmware 5aaef90.

I can reproduce this on macOS and Windows 11, but not on Linux.

**Comment by mhantsch** [comment]
That sounds very much like UltimateHackingKeyboard/firmware#943.

**Comment by mondalaci** [comment]
@jwr Does https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11145849044 resolve this issue?

**Comment by pcooke9** [comment]
> @jwr Does https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11145849044 resolve this issue?

I'm having a similar issue in Windows 11. On my mouse layer, I have "ctrl+w" mapped to a key for closing browser tabs. After using it, the "ctrl" modifier continues to be applied to my physical (non-UHK) mouse. It doesn't apply the modifier to the trackpad module or any other keys, just my mouse. In fact, changing layers or tapping the trackpad or any other key on the UHK resumes normal behavior.

The version you linked here seems to solve the issue for me.

**Comment by jwr** [comment]
> Does https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11145849044 resolve this issue?

It does not. I am now running 1f96ea4, which should contain this fix, and I can reproduce the problem every time.

**Comment by mondalaci** [comment]
Please test https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11217140334 guys.

And read UltimateHackingKeyboard/firmware-uhk80#317 for details.

**Comment by jwr** [comment]
I can confirm that 8626873 resolves the issue. 🙂

**Comment by pcooke9** [comment]
Resolved for me as well.
