### ISSUE TITLE
Special Characters Not Displaying Correctly on UHK Keyboard Screen

### ISSUE THREAD

**Issue by rogermeletta** [UltimateHackingKeyboard/firmware#954]
**Agent:** [4580f42](https://github.com/UltimateHackingKeyboard/agent80/actions/runs/11084976462)
**UHK80 Firmware:** [5aaef90](https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11067773912)
**macOS:** Sequoia 15.0 (_24A335_)

Special characters are not shown correctly on the UHK keyboard screen, or they display as random characters.

Example 1:
<img src="https://github.com/user-attachments/assets/1b7941cb-17bb-4a6f-8fe1-5fc80c7a4d07" width="70%">  
![Screenshot 2024-09-30 at 22 44 53](https://github.com/user-attachments/assets/1c237d59-d526-46c3-b966-0e179055a5fe)

Example 2:
<img src="https://github.com/user-attachments/assets/e6477668-cf5c-47f9-b993-d050c3e22b32" width="70%">  
![Screenshot 2024-09-30 at 22 44 32](https://github.com/user-attachments/assets/0fc40d06-083b-4dd2-b74d-6ee090783597)

**Comment by mondalaci** [comment]
@kareltucek I suggest replacing the unsupported characters with `*` unless you have a better idea.

Related issue: UltimateHackingKeyboard/firmware#950

**Comment by kareltucek** [comment]
> unless you have a better idea.

Sure, just pick:
- snakes
- gift icon ("mystery box")
- a sequence of progressively angrier emoji faces, one per each non ascii character

**Comment by mhantsch** [comment]
@kareltucek The third option please. 😐🫤😢🥹😒😟😠🤕🤯
