### ISSUE TITLE
I added another user's user config json and it refuses to show up on the keyboard

### ISSUE THREAD

**Issue by nazmulidris** [UltimateHackingKeyboard/firmware#956]
I'm not sure if this is a firmware or agent issue. @NadiaIdris just got her keyboard today, and we thought of putting her user config json on my UHK80 (before setting her keyboard up). 

And it did not work. No matter what we did, we were unable to get her user config json on to my UHK80. We tried adding the latest firmware using the latest agent appimage. No matter what we tried, my old user config json was always on the UHK80. 

The strange thing is that at first, after saving Nadia's user config json on my UHK80, in agent, it looks like the correct user config is on the keyboard. However, as soon as the keyboard is disconnected and reconnected, the old user config shows up on agent. The old user config stays on the UHK80, the entire time.

Another strange thing is that resetting my UHK80 does not remove my user config from the device. It seems that it will not allow itself to be deleted, no matter what: device reset, or putting a new user config on there.

We also tried pressing the "reset" recessed buttons on the backs of the left and right halves of the keyboard to no avail. It didn't change any of these behaviors.

![image](https://github.com/user-attachments/assets/3c94fd45-1d08-4f27-a7dc-8c3af33f7b30)

> We haven't configured Nadia's UHK80 yet, this is just issues with her user config on my UHK80.

**Comment by mondalaci** [comment]
The reset button merely reboots the keyboard's processor but doesn't affect its configuration.

After importing the configuration on the Configuration page of Agent, did you click on the "Save to keyboard" button in the bottom right corner?

**Comment by nazmulidris** [comment]
@mondalaci I did press the "Save to keyboard" button on the bottom right corner. Thanks for the info about the reset button.

**Comment by mondalaci** [comment]
Can you attach Nadia's user config, so I can try to reproduce the issue?

**Comment by nazmulidris** [comment]
@mondalaci @NadiaIdris  Attached is her user config json file.
[NadiaUHKUserConfiguration.json](https://github.com/user-attachments/files/17217464/NadiaUHKUserConfiguration.json)

**Comment by nazmulidris** [comment]
@mondalaci Adding to this bug ... I tried to reset my uhk80 config and it does not work.

![image](https://github.com/user-attachments/assets/cf3e66b2-a703-48b4-93ac-07282b85ea1d)

I tried to remove the existing keymaps, and that does not work.

![image](https://github.com/user-attachments/assets/5d757c97-0eda-49f5-b3e4-f1142d3e756d)

In all these cases, Agent looks like the action that I asked it to perform worked. However, as soon as it is disconnected & reconnected to the uhk80, it is apparent that the data on the uhk80 isn't affected.

Also, I tried to change the existing keymap, by changing what a key does, and then clicked "Save to keyboard". And it does not affect the uhk80.

**Comment by kareltucek** [comment]
@ert78gb it looks like errors from config validation may be getting lost somewhere. Not sure if in firmware or in agent. (Noticed that in the target_parse ticket - there too, validation error occured, yet you didn't complain about the error code.)

**Comment by nazmulidris** [comment]
I also loaded the uhk60 config into agent80, and then saved it back to disk. Then I did a diff between the 2 files, and there were significant differences between these 2 different file formats. 

I'm totally speculating here, but it seems like agent80 is happy with loading and converting, then it goes to save the data to the uhk80. Then the uhk80 just says "no" and no error is reported in agent80.

**Comment by mondalaci** [comment]
I successfully imported Nadia's configuration and reconnected my UHK 80, and it restored the config with the Linux and Mac keymaps. I could also change the mapping, which was remembered, delete a keymap, and reset the config.

When importing Nadia's config, please watch the terminal output of Agent and copy-paste any errors that you see.

**Comment by nazmulidris** [comment]
@mondalaci I tried to do something simple. Just remap one of the keys to the mod layer.

![image](https://github.com/user-attachments/assets/f3c29469-324f-4fb6-9056-c1cdf714938f)

And it failed. Here's the console output.

<pre><font color="#88C0D0">13:11:31.181</font> › [DeviceOperation] right module deviceProtocolVersion: 4.10.0
<font color="#88C0D0">13:11:31.245</font> › [DeviceOperation] Read &quot;leftHalf&quot; version information
<font color="#88C0D0">13:11:31.277</font> › [DeviceOperation] Read &quot;leftHalf&quot; repo information
<font color="#88C0D0">13:11:31.309</font> › [DeviceOperation] Read &quot;leftHalf&quot; firmware checksum
<font color="#88C0D0">13:11:31.325</font> › [DeviceOperation] Read &quot;leftModule&quot; version information
<font color="#88C0D0">13:11:31.357</font> › [DeviceOperation] Read &quot;leftModule&quot; repo information
<font color="#88C0D0">13:11:31.389</font> › [DeviceOperation] Read &quot;leftModule&quot; firmware checksum
<font color="#88C0D0">13:11:31.405</font> › [DeviceOperation] Read &quot;rightModule&quot; version information
<font color="#88C0D0">13:11:31.437</font> › [DeviceOperation] Read &quot;rightModule&quot; repo information
<font color="#88C0D0">13:11:31.469</font> › [DeviceOperation] Read &quot;rightModule&quot; firmware checksum
<font color="#88C0D0">13:11:31.533</font> › [DeviceService] Device connection state changed to: {
  bootloaderActive: <font color="#EBCB8B">false</font>,
  communicationInterfaceAvailable: <font color="#EBCB8B">true</font>,
  hasPermission: <font color="#EBCB8B">true</font>,
  halvesInfo: {
    areHalvesMerged: <font color="#EBCB8B">false</font>,
    isLeftHalfConnected: <font color="#EBCB8B">true</font>,
    leftModuleSlot: <font color="#EBCB8B">2</font>,
    rightModuleSlot: <font color="#EBCB8B">3</font>
  },
  hardwareModules: {
    moduleInfos: [ <font color="#A3BE8C">&apos;[object]&apos;</font>, <font color="#A3BE8C">&apos;[object]&apos;</font>, <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    rightModuleInfo: {
      firmwareVersion: <font color="#A3BE8C">&apos;11.1.0&apos;</font>,
      deviceProtocolVersion: <font color="#A3BE8C">&apos;4.10.0&apos;</font>,
      moduleProtocolVersion: <font color="#A3BE8C">&apos;4.3.0&apos;</font>,
      modules: <font color="#A3BE8C">&apos;[object]&apos;</font>,
      userConfigVersion: <font color="#A3BE8C">&apos;7.1.0&apos;</font>,
      hardwareConfigVersion: <font color="#A3BE8C">&apos;1.0.0&apos;</font>,
      smartMacrosVersion: <font color="#A3BE8C">&apos;2.4.3&apos;</font>,
      firmwareGitRepo: <font color="#A3BE8C">&apos;UltimateHackingKeyboard/firmware-uhk80&apos;</font>,
      firmwareGitTag: <font color="#A3BE8C">&apos;cbd0b04&apos;</font>,
      firmwareChecksum: <font color="#A3BE8C">&apos;906e034f0b1228f188dab485b0905ec2&apos;</font>
    }
  },
  isMacroStatusDirty: <font color="#EBCB8B">false</font>,
  multiDevice: <font color="#EBCB8B">false</font>,
  udevRulesInfo: <font color="#A3BE8C">&apos;Ok&apos;</font>,
  connectedDevice: {
    id: <font color="#EBCB8B">4</font>,
    firmwareUpgradeMethod: <font color="#A3BE8C">&apos;mcuboot&apos;</font>,
    logName: <font color="#A3BE8C">&apos;UHK 80 right&apos;</font>,
    name: <font color="#A3BE8C">&apos;UHK 80&apos;</font>,
    keyboard: [ <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    bootloader: [ <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    buspal: [],
    reportId: <font color="#EBCB8B">4</font>
  }
}
<font color="#88C0D0">13:11:31.533</font> › [DeviceRendererService] dispatch action [device] connection state changed
<font color="#88C0D0">13:11:31.539</font> › [SmartMacroDocRendererService] downloadDocumentation
<font color="#88C0D0">13:11:31.550</font> › [SmartMacroService] start download firmware documentation {
  firmwareGitRepo: <font color="#A3BE8C">&apos;UltimateHackingKeyboard/firmware-uhk80&apos;</font>,
  firmwareGitTag: <font color="#A3BE8C">&apos;cbd0b04&apos;</font>
}
<font color="#88C0D0">13:11:31.551</font> › [SmartMacroService] firmware documentation downloading
<font color="#BF616A">13:11:31.614</font> › [SmartMacroService] download documentation failed HttpError: Not Found
    at /tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:8:888224
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Cn.pathExists.owner (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:647293)
    at async Object.handleDownloadDocumentation (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:647244)
    at async Dn.process (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:484734)
<font color="#88C0D0">13:11:31.677</font> › [DeviceRendererService] dispatch action [device] Status buffer changed
<font color="#88C0D0">13:11:38.779</font> › [AppService] set-config of &quot;application-settings&quot;: {&quot;errorPanelHeight&quot;:25.970446242171192,&quot;checkForUpdateOnStartUp&quot;:true,&quot;everAttemptedSavingToKeyboard&quot;:true,&quot;animationEnabled&quot;:true,&quot;appTheme&quot;:&quot;system&quot;,&quot;backlightingColorPalette&quot;:[{&quot;r&quot;:255,&quot;g&quot;:0,&quot;b&quot;:0},{&quot;r&quot;:0,&quot;g&quot;:255,&quot;b&quot;:0},{&quot;r&quot;:0,&quot;g&quot;:0,&quot;b&quot;:255},{&quot;r&quot;:255,&quot;g&quot;:0,&quot;b&quot;:218,&quot;a&quot;:1},{&quot;r&quot;:255,&quot;g&quot;:218,&quot;b&quot;:2,&quot;a&quot;:1}],&quot;keyboardHalvesAlwaysJoined&quot;:false,&quot;smartMacroPanelWidth&quot;:41}
<font color="#88C0D0">13:11:57.646</font> › [AppService] set-config of &quot;application-settings&quot;: {&quot;errorPanelHeight&quot;:37.4527009394572,&quot;checkForUpdateOnStartUp&quot;:true,&quot;everAttemptedSavingToKeyboard&quot;:true,&quot;animationEnabled&quot;:true,&quot;appTheme&quot;:&quot;system&quot;,&quot;backlightingColorPalette&quot;:[{&quot;r&quot;:255,&quot;g&quot;:0,&quot;b&quot;:0},{&quot;r&quot;:0,&quot;g&quot;:255,&quot;b&quot;:0},{&quot;r&quot;:0,&quot;g&quot;:0,&quot;b&quot;:255},{&quot;r&quot;:255,&quot;g&quot;:0,&quot;b&quot;:218,&quot;a&quot;:1},{&quot;r&quot;:255,&quot;g&quot;:218,&quot;b&quot;:2,&quot;a&quot;:1}],&quot;keyboardHalvesAlwaysJoined&quot;:false,&quot;smartMacroPanelWidth&quot;:41}
</pre>

**Comment by nazmulidris** [comment]
@mondalaci And this is the terminal output when I tried to import Nadia's user config JSON.

<pre><font color="#88C0D0">13:14:51.522</font> › [AppService] set-config of &quot;application-settings&quot;: {&quot;errorPanelHeight&quot;:37.4527009394572,&quot;checkForUpdateOnStartUp&quot;:true,&quot;everAttemptedSavingToKeyboard&quot;:true,&quot;animationEnabled&quot;:true,&quot;appTheme&quot;:&quot;system&quot;,&quot;backlightingColorPalette&quot;:[{&quot;r&quot;:255,&quot;g&quot;:0,&quot;b&quot;:0},{&quot;r&quot;:0,&quot;g&quot;:255,&quot;b&quot;:0},{&quot;r&quot;:0,&quot;g&quot;:0,&quot;b&quot;:255},{&quot;r&quot;:255,&quot;g&quot;:0,&quot;b&quot;:218,&quot;a&quot;:1},{&quot;r&quot;:255,&quot;g&quot;:218,&quot;b&quot;:2,&quot;a&quot;:1}],&quot;keyboardHalvesAlwaysJoined&quot;:false,&quot;smartMacroPanelWidth&quot;:41}
<font color="#88C0D0">13:14:51.623</font> › [DeviceService] stop poll UHK Device
<font color="#88C0D0">13:14:51.724</font> › [DeviceService] stopped poll UHK Device
<font color="#88C0D0">13:14:52.331</font> › [UhkHidDevice] Device communication closing.
<font color="#88C0D0">13:14:52.333</font> › [UhkHidDevice] Device communication closed.
<font color="#88C0D0">13:14:52.351</font> › [UhkHidDevice] Device communication closing.
<font color="#88C0D0">13:14:52.351</font> › [DeviceService] start poll UHK Device
<font color="#88C0D0">13:14:52.351</font> › [DeviceRendererService] dispatch action [user-config] Load user configuration history success
<font color="#88C0D0">13:14:52.364</font> › [DeviceRendererService] dispatch action [device] save configuration reply
<font color="#88C0D0">13:14:52.424</font> › [UhkHidDevice] Available devices unchanged
<font color="#88C0D0">13:14:52.483</font> › [UhkHidDevice] Used device: {&quot;vendorId&quot;:&quot;0x37A8&quot;,&quot;productId&quot;:&quot;0x9&quot;,&quot;path&quot;:&quot;/dev/hidraw4&quot;,&quot;serialNumber&quot;:&quot;1613767334&quot;,&quot;manufacturer&quot;:&quot;Ultimate Gadget Laboratories&quot;,&quot;product&quot;:&quot;UHK 80 right half&quot;,&quot;release&quot;:1,&quot;interface&quot;:2,&quot;usagePage&quot;:65280,&quot;usage&quot;:1}
<font color="#88C0D0">13:14:52.683</font> › [DeviceOperation] right module deviceProtocolVersion: 4.10.0
<font color="#88C0D0">13:14:52.747</font> › [DeviceOperation] Read &quot;leftHalf&quot; version information
<font color="#88C0D0">13:14:52.763</font> › [DeviceOperation] Read &quot;leftHalf&quot; repo information
<font color="#88C0D0">13:14:52.795</font> › [DeviceOperation] Read &quot;leftHalf&quot; firmware checksum
<font color="#88C0D0">13:14:52.891</font> › [DeviceOperation] Read &quot;leftModule&quot; version information
<font color="#88C0D0">13:14:52.907</font> › [DeviceOperation] Read &quot;leftModule&quot; repo information
<font color="#88C0D0">13:14:53.018</font> › [DeviceOperation] Read &quot;leftModule&quot; firmware checksum
<font color="#88C0D0">13:14:53.115</font> › [DeviceOperation] Read &quot;rightModule&quot; version information
<font color="#88C0D0">13:14:53.131</font> › [DeviceOperation] Read &quot;rightModule&quot; repo information
<font color="#88C0D0">13:14:53.162</font> › [DeviceOperation] Read &quot;rightModule&quot; firmware checksum
<font color="#88C0D0">13:14:53.307</font> › [DeviceService] Device connection state changed to: {
  bootloaderActive: <font color="#EBCB8B">false</font>,
  communicationInterfaceAvailable: <font color="#EBCB8B">true</font>,
  hasPermission: <font color="#EBCB8B">true</font>,
  halvesInfo: {
    areHalvesMerged: <font color="#EBCB8B">false</font>,
    isLeftHalfConnected: <font color="#EBCB8B">true</font>,
    leftModuleSlot: <font color="#EBCB8B">2</font>,
    rightModuleSlot: <font color="#EBCB8B">3</font>
  },
  hardwareModules: {
    moduleInfos: [ <font color="#A3BE8C">&apos;[object]&apos;</font>, <font color="#A3BE8C">&apos;[object]&apos;</font>, <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    rightModuleInfo: {
      firmwareVersion: <font color="#A3BE8C">&apos;11.1.0&apos;</font>,
      deviceProtocolVersion: <font color="#A3BE8C">&apos;4.10.0&apos;</font>,
      moduleProtocolVersion: <font color="#A3BE8C">&apos;4.3.0&apos;</font>,
      modules: <font color="#A3BE8C">&apos;[object]&apos;</font>,
      userConfigVersion: <font color="#A3BE8C">&apos;7.1.0&apos;</font>,
      hardwareConfigVersion: <font color="#A3BE8C">&apos;1.0.0&apos;</font>,
      smartMacrosVersion: <font color="#A3BE8C">&apos;2.4.3&apos;</font>,
      firmwareGitRepo: <font color="#A3BE8C">&apos;UltimateHackingKeyboard/firmware-uhk80&apos;</font>,
      firmwareGitTag: <font color="#A3BE8C">&apos;cbd0b04&apos;</font>,
      firmwareChecksum: <font color="#A3BE8C">&apos;906e034f0b1228f188dab485b0905ec2&apos;</font>
    }
  },
  isMacroStatusDirty: <font color="#EBCB8B">true</font>,
  multiDevice: <font color="#EBCB8B">false</font>,
  udevRulesInfo: <font color="#A3BE8C">&apos;Ok&apos;</font>,
  connectedDevice: {
    id: <font color="#EBCB8B">4</font>,
    firmwareUpgradeMethod: <font color="#A3BE8C">&apos;mcuboot&apos;</font>,
    logName: <font color="#A3BE8C">&apos;UHK 80 right&apos;</font>,
    name: <font color="#A3BE8C">&apos;UHK 80&apos;</font>,
    keyboard: [ <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    bootloader: [ <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    buspal: [],
    reportId: <font color="#EBCB8B">4</font>
  }
}
<font color="#88C0D0">13:14:53.307</font> › [DeviceRendererService] dispatch action [device] connection state changed
<font color="#88C0D0">13:14:53.311</font> › [SmartMacroDocRendererService] downloadDocumentation
<font color="#88C0D0">13:14:53.414</font> › [SmartMacroService] start download firmware documentation {
  firmwareGitRepo: <font color="#A3BE8C">&apos;UltimateHackingKeyboard/firmware-uhk80&apos;</font>,
  firmwareGitTag: <font color="#A3BE8C">&apos;cbd0b04&apos;</font>
}
<font color="#88C0D0">13:14:53.415</font> › [SmartMacroService] firmware documentation downloading
<font color="#BF616A">13:14:53.660</font> › [SmartMacroService] download documentation failed HttpError: Not Found
    at /tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:8:888224
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Cn.pathExists.owner (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:647293)
    at async Object.handleDownloadDocumentation (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:647244)
    at async Dn.process (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:484734)
<font color="#88C0D0">13:14:53.707</font> › [DeviceRendererService] dispatch action [device] Status buffer changed
<font color="#88C0D0">13:14:54.011</font> › [DeviceOperation] right module deviceProtocolVersion: 4.10.0
<font color="#88C0D0">13:14:54.074</font> › [DeviceOperation] Read &quot;leftHalf&quot; version information
<font color="#88C0D0">13:14:54.091</font> › [DeviceOperation] Read &quot;leftHalf&quot; repo information
<font color="#88C0D0">13:14:54.123</font> › [DeviceOperation] Read &quot;leftHalf&quot; firmware checksum
<font color="#88C0D0">13:14:54.139</font> › [DeviceOperation] Read &quot;leftModule&quot; version information
<font color="#88C0D0">13:14:54.154</font> › [DeviceOperation] Read &quot;leftModule&quot; repo information
<font color="#88C0D0">13:14:54.187</font> › [DeviceOperation] Read &quot;leftModule&quot; firmware checksum
<font color="#88C0D0">13:14:54.203</font> › [DeviceOperation] Read &quot;rightModule&quot; version information
<font color="#88C0D0">13:14:54.219</font> › [DeviceOperation] Read &quot;rightModule&quot; repo information
<font color="#88C0D0">13:14:54.251</font> › [DeviceOperation] Read &quot;rightModule&quot; firmware checksum
<font color="#88C0D0">13:14:54.315</font> › [DeviceService] Device connection state changed to: {
  bootloaderActive: <font color="#EBCB8B">false</font>,
  communicationInterfaceAvailable: <font color="#EBCB8B">true</font>,
  hasPermission: <font color="#EBCB8B">true</font>,
  halvesInfo: {
    areHalvesMerged: <font color="#EBCB8B">false</font>,
    isLeftHalfConnected: <font color="#EBCB8B">true</font>,
    leftModuleSlot: <font color="#EBCB8B">2</font>,
    rightModuleSlot: <font color="#EBCB8B">3</font>
  },
  hardwareModules: {
    moduleInfos: [ <font color="#A3BE8C">&apos;[object]&apos;</font>, <font color="#A3BE8C">&apos;[object]&apos;</font>, <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    rightModuleInfo: {
      firmwareVersion: <font color="#A3BE8C">&apos;11.1.0&apos;</font>,
      deviceProtocolVersion: <font color="#A3BE8C">&apos;4.10.0&apos;</font>,
      moduleProtocolVersion: <font color="#A3BE8C">&apos;4.3.0&apos;</font>,
      modules: <font color="#A3BE8C">&apos;[object]&apos;</font>,
      userConfigVersion: <font color="#A3BE8C">&apos;7.1.0&apos;</font>,
      hardwareConfigVersion: <font color="#A3BE8C">&apos;1.0.0&apos;</font>,
      smartMacrosVersion: <font color="#A3BE8C">&apos;2.4.3&apos;</font>,
      firmwareGitRepo: <font color="#A3BE8C">&apos;UltimateHackingKeyboard/firmware-uhk80&apos;</font>,
      firmwareGitTag: <font color="#A3BE8C">&apos;cbd0b04&apos;</font>,
      firmwareChecksum: <font color="#A3BE8C">&apos;906e034f0b1228f188dab485b0905ec2&apos;</font>
    }
  },
  isMacroStatusDirty: <font color="#EBCB8B">false</font>,
  multiDevice: <font color="#EBCB8B">false</font>,
  udevRulesInfo: <font color="#A3BE8C">&apos;Ok&apos;</font>,
  connectedDevice: {
    id: <font color="#EBCB8B">4</font>,
    firmwareUpgradeMethod: <font color="#A3BE8C">&apos;mcuboot&apos;</font>,
    logName: <font color="#A3BE8C">&apos;UHK 80 right&apos;</font>,
    name: <font color="#A3BE8C">&apos;UHK 80&apos;</font>,
    keyboard: [ <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    bootloader: [ <font color="#A3BE8C">&apos;[object]&apos;</font> ],
    buspal: [],
    reportId: <font color="#EBCB8B">4</font>
  }
}
<font color="#88C0D0">13:14:54.315</font> › [DeviceRendererService] dispatch action [device] connection state changed
<font color="#88C0D0">13:14:54.318</font> › [SmartMacroDocRendererService] downloadDocumentation
<font color="#88C0D0">13:14:54.332</font> › [SmartMacroService] start download firmware documentation {
  firmwareGitRepo: <font color="#A3BE8C">&apos;UltimateHackingKeyboard/firmware-uhk80&apos;</font>,
  firmwareGitTag: <font color="#A3BE8C">&apos;cbd0b04&apos;</font>
}
<font color="#88C0D0">13:14:54.332</font> › [SmartMacroService] firmware documentation downloading
<font color="#BF616A">13:14:54.396</font> › [SmartMacroService] download documentation failed HttpError: Not Found
    at /tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:8:888224
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Cn.pathExists.owner (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:647293)
    at async Object.handleDownloadDocumentation (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:647244)
    at async Dn.process (/tmp/.mount_UHK.AgHLMbHO/resources/app.asar/electron-main.js:2:484734)
<font color="#88C0D0">13:14:54.587</font> › [DeviceRendererService] dispatch action [device] Status buffer changed

</pre>

![image](https://github.com/user-attachments/assets/11eb31ac-466f-44e1-bd15-be3e086fe585)

**Comment by mondalaci** [comment]
Please retry the latest Agent **master** build.

**Comment by nazmulidris** [comment]
@mondalaci Will do. Any specific firmware that I should be using as well?

**Comment by mondalaci** [comment]
The latest master as well.

**Comment by nazmulidris** [comment]
@mondalaci Whew! Installing the latest master builds of firmware and agent seems to have fixed the issues!

https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11131833967/artifacts/2002607597
https://github.com/UltimateHackingKeyboard/agent80/actions/runs/11114628893/artifacts/1997884809

**Comment by mondalaci** [comment]
So glad to hear!

Generally, it's always a good idea to keep Agent and the firmware up to date, especially in these turbulent times.

**Comment by nazmulidris** [comment]
@mondalaci Sounds good! Thanks for your help in getting this resolved 👍🏽
