### ISSUE TITLE
`tapKeySeq return` doesn't produce output but `tapKeySeq enter` does

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#957]
Given a macro **test-return-enter** bound to some key:

```
tapKeySeq a b c return return d e f return
delayUntil 2000
tapKeySeq a b c enter enter d e f enter
delayUntil 2000
tapKeySeq d o n e dotAndGreaterThanSign
```

When I run it, the output shows that `return` did not produce any output, but `enter` did actually create line breaks.

I was under the impression that `return` should also generate line breaks, but it didn't.

**Comment by kareltucek** [comment]
Funny thing:
```
        #define HID_KEYBOARD_SC_RETURN                            0x9E
        #define HID_KEYBOARD_SC_ENTER                             0x28
```

![2024-10-19-221812_1021x1106_scrot](https://github.com/user-attachments/assets/c59a2f22-2f24-46e8-a3bc-ae151dab21e4)

I.e., no idea if I should call it a bug or a feature.

**Comment by mondalaci** [comment]
@mhantsch Is this behavior specific to the UHK 80? In other words, can you reproduce it on the UHK 60 with the latest official firmware?

**Comment by mhantsch** [comment]
@mondalaci You are correct; I can reproduce this on the UHK60 as well with firmware 11.2.0. 
(I used rightaditya's highres build, but that's based on 11.2.0, so I guess it still counts as a valid test for this issue.)

**Comment by kareltucek** [comment]
Yes (its the same for all three firmwares) and it is irrelevant @mondalaci. The two are two different scancodes, which is why neither of them does what the other does.

**Comment by kareltucek** [comment]
The question is, should we rename the scancodes to be more intuitive, or call it a feature?

**Comment by mondalaci** [comment]
I don't see all the use cases across OSes and applications, and I think it's possible that it's a feature. Unless @mhantsch has objections, I'd close this issue.

**Comment by mhantsch** [comment]
Give me until after the weekend. I want to test one more thing but don't have time during this work week.

**Comment by mhantsch** [comment]
What I find interesting (confusing?) is that in the scancode selection pop-up in Agent, *Enter* is also listed as *Return*, but it's not the same. In fact, I cannot select *Return* (with its specific other scancode) in this pop-up; but in `tapKeySeq` and `tapKey` there are both `enter` and `return` -- with different semantics (producing different scancodes).

Side note: there is also `keypadEnter` and its equivalent in the scancode selection pop-up *Numpad Enter*.

![image](https://github.com/user-attachments/assets/c051838e-6357-495f-87e6-731a935e8661)

Should *Return* in the sense of the return scancode get added to the scancode selection pop-up?

**Comment by mondalaci** [comment]
It'd be worth examining whether Return has any function on any OS. If not, maybe we could remove it from the scancode list.

**Comment by mhantsch** [comment]
> It'd be worth examining whether Return has any function on any OS. If not, maybe we could remove it from the scancode list.

It's really not available as a scancode in the Agent pop-up scancode list.

There are three scancodes that have to do with "end-of-line":

- Enter
- Return
- Keypad/Numpad Enter

Enter and Numpad Enter are available to be selected as a scancode in Agent. Return cannot be selected in Agent, but the string "Return" is shown as a Description for the Enter scancode (see screenshot above).

From the smartMacros language, all three scancodes can be sent. They are called `enter`, `return`, and `keypadEnter`.

My personal recommendation would be to remove the "Return" description in Agent, because it may lead to confusion. Also **"Enter"** is shown on the physical keycap of the UHK.

If anyone really needs to send the Return scancode, they can use a macro. I don't think it's a likely use case, or else people would already have complained that they can't select a useful Return in Agent.

**Comment by mondalaci** [comment]
Thanks, we'll remove the Return description as suggested.

The return scancode should also be specifiable via [custom scancodes](https://ultimatehackingkeyboard.com/blog/2021/10/31/production-progress-spare-parts-bonanza-new-agent-release#custom-scancodes).
