### ISSUE TITLE
can't use KEYID_ABBREV with `set backlight.keyRgb`

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#959]
Seems like KEYIDs are not properly parsed in `set backlight.keyRgb` commands. I was able to specify an integer, and it would then refer to the hardware keyId, but could  not make it work with KEYID_ABBREVs. And no, $keyId.capsLock wouldn't work either.

```
Error at maxtend 1/15/26: Parsing failed, did you mean '$ZI '?
> 15 | [set backlight.keyRgb.mod.capsLock 0 0 0](https://github.com/UltimateHackingKeyboard/firmware-uhk80/issues/new#/macro/55?actionIndex=0&lineNr=15&columnNr=26&inlineEdit=true)
>    |                          ^
Error at maxtend 1/15/26: Unrecognized command: capsLock
> 15 | [set backlight.keyRgb.mod.capsLock 0 0 0](https://github.com/UltimateHackingKeyboard/firmware-uhk80/issues/new#/macro/55?actionIndex=0&lineNr=15&columnNr=26&inlineEdit=true)
>    |                          ^
Error at maxtend 1/16/26: Parsing failed, did you mean '$ZI '?
> 16 | [set backlight.keyRgb.mod.apostropheAndQuote 0 0 0](https://github.com/UltimateHackingKeyboard/firmware-uhk80/issues/new#/macro/55?actionIndex=0&lineNr=16&columnNr=26&inlineEdit=true)
>    |                          ^
Error at maxtend 1/16/26: Parsing failed, did you mean '$ZI '?
> 16 | set backlight.keyRgb.mod.apostropheAndQuote 0 0
```

Side question: how do you distinguish between `set backlight.keyRgb.1` meaning `KEYID(INT 1)` (hardware key id) and KEYID_ABBREV(1) (the key with the US QWERTY label **`1`**)?

Again, lowpri, seeing what you guys are currently working on...

**Comment by mhantsch** [comment]
Yeah, these seem to work now. I can use the syntax. But light on the left half of the UHK80 don't seem to change. I can only affect the right half.

**Comment by mondalaci** [comment]
`set backlight.keyRgb.mod.capsLock 0 0 0` works for me with https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11743848104

**Comment by mhantsch** [comment]
Yes, it works on that build.
