### ISSUE TITLE
reset all parameters to defaults when config is reloaded

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#960]
I overloaded the behaviour for caret mode to test something. So I had this in **$onInit**:

```
set navigationModeAction.caret.left macro window-forward
set navigationModeAction.caret.right macro window-backward
```
(with `Fn` mapped to caret)

After saving the config, the keyboard executed those macros on `Fn`+movement. So far, so good.

I then ended the test, and commented out the two commands from **$onInit**. Saved the config.

After that, the keyboard still executed those macros. I did not get back the default behaviour of caret movement. I had to reset the right half (paperclip & reset button).

I think whenever a new config is reloaded, then the keyboard must apply defaults first before initialising the new config. This is especially important because you can't just pull out and reconnect USB to restart the keyboard. It's always on. It will never forget your RAM config.

**Comment by mondalaci** [comment]
@mhantsch Does https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11288821496 fix the issue?

**Comment by mhantsch** [comment]
Yes, it does fix it.
