### ISSUE TITLE
Disable sleep-wake OLED debugging

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#961]
The fix may take a while for Benedek, and in the meantime, it'd be worth disabling the sleep-wake OLED logging.

**Comment by kareltucek** [comment]
Done, on master.

**Comment by mhantsch** [comment]
General question: instead of enabling/disabling debug output by installing different builds, what would you think about having a "debug flag" or "debug level" which turns the logs on and off in the same build? Testers could use this to drill down in the case of unexpected problems (by enabling more log output).

**Comment by mondalaci** [comment]
I don't think it's worth allocating resources for OLED logging now.

**Comment by mhantsch** [comment]
I wouldn't add any new debugging. I was under the impression you are now removing the L0, L2 etc. state logging, and I would suggest to leave it but put it behind a "debug" switch that can be set via a macro parameter, e.g. `set globalProperty.debug 1`.

**Comment by mondalaci** [comment]
We could potentially log a million things on the OLED, and this option wouldn't be useful once the issue is fixed.

**Comment by mhantsch** [comment]
I'll rest my case.

**Comment by kareltucek** [comment]
If you write or figure out how to use some existing logging solution in a reasonable way, I am happy to use it.

With current infrastructure in place, just recompiling the firmware is a relatively quick thing to do, while constantly adding and removing log-configuration-management code whenever I want to log something is not.

One of the issues is ease of use - ideally, such a solution should ideally be fully dynamic - I just write a logging "tag" to every log line, and then turn that "tag" on or off.

But the second concern is performance. Any fully dynamic solution is going to be a serious performance drain, so what we would need is a solution somewhere inbetween...
