### ISSUE TITLE
Left half key backlight goes out one minute after resetting it

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#962]
My right UHK 80 half is connected via USB. The two halves are connected via the bridge cable. This is my LED configuration:

![image](https://github.com/user-attachments/assets/e590b295-26ec-4651-8a4e-ec622be8c563)

After resetting my left keyboard half, its lights get enabled as expected, but one minute afterward, the lights of the left keyboard half go out, which shouldn't happen.

**Comment by kareltucek** [comment]
~Is your left half also connected via USB?~

Sorry, stupid question.

**Comment by kareltucek** [comment]
Is solved. 

Closes hook didn't take 🤨
