### ISSUE TITLE
Read BLE device name upon pairing

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#963]
Upon BLE host pairing, retrieve the device name using GATT discovery and save it under the `uhk/bleName/${bleAddr}` settings key.

Then, Agent will query the individual BLE names via new getBleHostName getDeviceProperty call, providing the BLE address.

**Comment by benedekkupper** [comment]
This isn't possible in any standard way, unless the phone/computer is active in both client and server roles.
