### ISSUE TITLE
UPS warning pops up

### ISSUE THREAD

**Issue by jwr** [UltimateHackingKeyboard/firmware#965]
After updating the firmware to c75c97f, this warning sometimes pops up. It's usually after resuming from sleep or after connecting the keyboard. Obviously, I do not have a UPS.

This is on Mac OS Sonoma 14.7 (23H124).

<img width="303" alt="SCR-20241016-issg" src="https://github.com/user-attachments/assets/a630a4c5-6bbf-4700-9934-30b31ea4bd8a">

**Comment by mondalaci** [comment]
@benedekkupper Any ideas why this happens? Seems USB-related.

**Comment by rogermeletta** [comment]
I have a similar issue on macOS Sequoia 15.0.1 (_24A348_)
**UHK80 Firmware:** [usb-battery-if](https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11353183296)

Without the UHK connected:
![Screenshot 2024-10-18 at 08 52 10@2x](https://github.com/user-attachments/assets/500c6ea9-28a0-4438-a9f5-5575722f80e1)

With UHK connected via USB (connection to either left or right half produces the same result):
![Screenshot 2024-10-18 at 08 52 39@2x](https://github.com/user-attachments/assets/5c9ddb95-9180-4159-baa2-c7726c479249)

When I disconnect the UHK, it just reverts back to the original power source view (without showing any error message though).

**Comment by benedekkupper** [comment]
I cannot reproduce the pop-up warning on macOS, I do see the UPS show up in the status bar. I don't have a battery in my UHK, so I can't quickly test why the battery level doesn't correspond to the actual value. I pushed a new commit on this branch that makes all of this disappear.

**Comment by jwr** [comment]
Another amusing side effect of this issue was that my computer started locking the screen far too frequently, even when connected to power. I eventually discovered that a new setting had appeared in system preferences, related to how long the display should remain on when using UPS power. 
<img width="481" alt="SCR-20241018-oyle" src="https://github.com/user-attachments/assets/0d4dbc3b-c0dc-40a6-8e77-28cfc3d14d45">

**Comment by mondalaci** [comment]
Please try https://github.com/UltimateHackingKeyboard/firmware-uhk80/actions/runs/11403998385 guys. For me, it resolves the mentioned issue, although I can't reproduce the popup.

**Comment by jwr** [comment]
Firmware d19ec47 resolves these problems for me.

**Comment by mondalaci** [comment]
Closing resolved issue.
