### ISSUE TITLE
bluetooth connection not listed in "Connections" in Agent

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#969]
I'm not sure if this a firmware issue or an Agent issue.

I've paired my UHK 80 via bluetooth. It shows as "connected" in the bluetooth UI of my host laptop. I have also connected it via USB so I can run Agent.

When I look at the Connections screen in Agent, it only shows USB and Dongle, but not the bluetooth connection.

![image](https://github.com/user-attachments/assets/249460a1-763a-4f97-b7d3-aaa4d6b88e49)

**Comment by mondalaci** [comment]
Duplicate of https://github.com/UltimateHackingKeyboard/agent/issues/2451
