### ISSUE TITLE
Left and right halves don't want to talk wirelessly

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/firmware#970]
When I disconnect the spiral cable, my left half does not connect to the right half. The OLED display shows the crossed-out circle.

This used to work previously, but one day it just didn't work anymore. I usually use the spiral cable,, so I don't know exactly what change made it fail. I've had numerous updates of firmware and agent before I again tried without the spiral cable.

I've rebooted both halves; no change.

It doesn't matter whether I run the host connection over USB or bluetooth. I haven't tried the dongle yet.

**Comment by mondalaci** [comment]
Click seven times on the Agent logo on the About page. Then, go to the Advanced Settings page and re-pair the halves. Does it work?

**Comment by mhantsch** [comment]
Clicking seven times on the Agent logo on the About page doesn't do anything. No new Advanced Settings page appears. Is this the right Agent logo that I should be clicking?

![image](https://github.com/user-attachments/assets/9efba784-8c11-4f08-8c5e-308d2eb4b79c)

**Comment by mhantsch** [comment]
Update: I stand corrected. I did not realise this would appear quite far on the top of the tree list on the left. I found it now.

**Comment by mhantsch** [comment]
> Does it work?

Yes, this worked. The halves now work again wirelessly.

**Comment by mondalaci** [comment]
Excellent! I'm closing this now, assuming that one of the many work-in-progress builds screwed the wireless connection of your UHK.

**Comment by kareltucek** [comment]
> Update: I stand corrected. I did not realise this would appear quite far on the top of the tree list on the left. I found it now.

Yeah, that tricked me too. I would expect the advanced settings to appear in the bottom menu...

**Comment by mondalaci** [comment]
The submenus of the Agent main menu item, such as settings, are specific to Agent, unlike per-device settings. This distinction will be significant when multi-device support is implemented.

**Comment by mhantsch** [comment]
Yeah, I get that, but how about giving the user some kind of indication that the seven clicks were successful? Agent could scroll the left side to the new advanced settings section (it's quite close to the beginning anyway, so maybe it's enough to scroll it to the top) and highlight the new entry.

**Comment by mondalaci** [comment]
https://github.com/UltimateHackingKeyboard/agent/issues/2307 will likely solve this issue.

**Comment by mhantsch** [comment]
OK, that kind of makes sense. And even with #2307, scroll left side to top as soon as the new entry appears and user will definitly see it. (For example, I have quite a long list of keymaps and macros and I never see the whole list. I would still miss a new entry high up on the list.)

**Comment by mondalaci** [comment]
We can tweak the behavior, but let's make #2307 happen first.
