### ISSUE TITLE
All LEDs must be white after factory flashing

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#971]
When we receive the PCBs from our contract manufacturer, we want to test all the LEDs. After flashing the left and right firmware with J-Links, all LEDs must be lit white and at full brightness.

- According to the factory keymap, some LEDs are not white. All must be white.
- After flashing the firmware, the LEDs of the right half are bright momentarily. Then, they become dim and go off after about a minute. They must always be lit at full brightness.

At this point, the hardware and user configuration area is empty. The firmware could detect the empty hardware configuration area to implement the above behavior.

**Comment by kareltucek** [comment]
@mondalaci how do you recommend to clear the flash for testing purposes?

**Comment by kareltucek** [comment]
Is this request aimed at uhk60 as well?

**Comment by mondalaci** [comment]
> @mondalaci how do you recommend to clear the flash for testing purposes?

For now, `nrfjprog --eraseall` is the only solution I can think of for the UHK 80. There must be a relevant J-Link-related command for the UHK 60 as well. I can look into it if needed. But it'd be useful to have a delete configuration Agent script for both the user and hardware config. Agreed?

> Is this request aimed at uhk60 as well?

Yes.

**Comment by kareltucek** [comment]
> For now, nrfjprog --eraseall is the only solution I can think of for the UHK 80. There must be a relevant J-Link-related command for the UHK 60 as well. I can look into it if needed. But it'd be useful to have a delete configuration Agent script for both the user and hardware config. Agreed?

I haven't needed such command in the last 6 years, and I would strongly prefer to skip uhk60 testing on my side and let you/factory test that, so from my side I don't feel I need it.

**Comment by mondalaci** [comment]
Ok, I'll test it.
