### ISSUE TITLE
Mouse pointer slowness

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#99]
A [seemingly harmless code change](https://github.com/UltimateHackingKeyboard/firmware/commit/a84b883e40d626f53235f0b252d62d1a58cb03d8) causes the mouse pointer to move very slowly when using the release build. When I put `EmptyFunction()` in `usb_command_apply_config.c`, the mouse pointer doesn't get slow. My guess is that GCC unoptimizes something when a function is referenced from a different compilation unit.

I also tested the debug build, and it seems that the mouse pointer is already slow with it, even in the master branch regardless of this commit. So the root cause of this issue is something else. Nevertheless, it'd be interesting to figure out why GCC behaves this way, but the root cause must be solved, too.

It's worth nothing that when the mouse pointer is slow, it's not evenly slow but rather the speed slightly fluctuates. This suggests to me that other, non-mouse related interrupt handlers may be too heavy, and insufficient CPU time is available for mouse updates.

**Comment by Lauszus** [comment]
I can reproduce this issue on Mac as well.

**Comment by Lauszus** [comment]
https://github.com/Lauszus/firmware/commit/d2acfba65987a80c24f2481f49573ca1cb2d9aed?w=1 should fix this issue.

I have just set the update rate to 100 Hz. How does the agent map the speed to px/s?

**Comment by mondalaci** [comment]
The raw configuration values are multipied by 25 for mouse movement and 1 for mouse scroll events, hence the relevant `mouse_kinetic_state_t.intMultiplier` values.
